### ISSUE TITLE
如图所示，对象引用和静态是什么关系（如图）？？

### ISSUE THREAD

**Issue by Mr-Loevan** [buaa21/summer2020#100]
![QQ截图20200828215306](https://user-images.githubusercontent.com/70183000/91571670-fd1b6600-e978-11ea-9c14-e26e5a8c256b.png)

**Comment by crclz** [comment]
解决方案：在13行的private后面加static。

static是静态的意思，静态的意思就是和当前对象无关，可以理解为全局变量。
