### ISSUE TITLE
数据库中的列的名称和实体类中的名称不同，导致从数据库中获取不到数据

### ISSUE THREAD

**Issue by xmx6665** [buaa21/summer2020#101]
比如实体类中的对象为
```
public class User {
    private int userId;
    private String username;
    private int userType;
}
```
而对应的数据库中列名分别为
```
user_id
username
user_type
```
则执行SQL语言
```
@Select(SELECT * FROM user WHERE username = #{username})
public List<User> query(@Param("username") String username)
```
时, 获取到的数据中`userId`和`userType`属性均为`0`, 除非将实体类中的属性名改成`user_id`和`user_type`, 但是这样不符合驼峰命名法.
在网上尝试过在属性的上面加上`@Column`注解但是不知道为什么过不了编译
有什么简单有效的办法吗0.0

**Comment by crclz** [comment]
> 一直以来，在sqlmap文件中，对于数据库中的下划线字段转驼峰，我们都是通过resultmap来做的，如下：
...
这是件挺无聊的事情，其实mybatis是支持自动转的，只要在mybatis-config.xml中加上mapUnderscoreToCamelCase setting即可，如下：

https://www.cnblogs.com/zhjh256/p/5814414.html
https://blog.csdn.net/weixin_42707253/article/details/86152665

**Comment by xmx6665** [comment]
```
@Select(SELECT * FROM user WHERE username = #{username})
@Results(id = "xxx" values = {
             // id 表示主键, 默认为 false, 更换主键名时需要将 id = true
            @Result(id = true, column = "user_id", property = "userId"),
            @Result(column = "user_type", property = "userType")
    })
public List<User> query(@Param("username") String username)
```
如此可以解决
