### ISSUE TITLE
C语言怎么使用graphics.h这个图形库

### ISSUE THREAD

**Issue by 19373759** [buaa21/summer2020#102]
想给游戏加上贴图 但是需要这个库 在Easy-x搜到的版本没有检测到DEVc++开发平台，所以还是用不了

想知道怎么解决？或者说有没有自带这种图形库的开发平台？

**Comment by PineZhuo** [comment]
可以参考这个教程：
https://www.cnblogs.com/geore/p/5914664.html
换IDE吧

**Comment by 19373759** [comment]
> 可以参考这个教程：
> https://www.cnblogs.com/geore/p/5914664.html
> 换IDE吧

可是我看这个教程后面好像只能支持cpp不能支持c啊

**Comment by Innovator-h** [comment]
DEVc++只能用ege库，需要下载ege安装配置一下，另外图形库都是对cpp文件适用的，c不能运行成功。
只需要把文件设为cpp格式就好了，语法之类不用改，c语言用法在cpp都是适用的。
图形库还有easyx，对vc、vs适用。

**Comment by Zehong3351** [comment]
graphics.h是TC里面的图形库，如果要用的话应该用TC来编译，VC++有他自己的另外图形库。分为:像素函数、直线和线型函数、多边形函数、填充函数等。
具体使用的方法，可以参照这篇博客：https://blog.csdn.net/F_hawk189/article/details/80681819
