### ISSUE TITLE
pygame的event.get()机制

### ISSUE THREAD

**Issue by buaa-gavin** [buaa21/summer2020#103]
` for event in pygame.event.get():# 获取事件

              if event.type == QUIT:# 判断事件是否为退出事件

                  pygame.quit()# 退出pygame

                  sys.exit()# 退出系统`

这段代码有点理解不能，不知道退出for循环的机制是怎样的，官方文档关于event.get()讲的太少了

**Comment by dwr2001** [comment]
每一次从 pygame.event.get()中获取一个事件，如果是事件类型pygaem.QUIT，就结束

**Comment by orixing** [comment]
This will get all the messages and remove them from the queue. If a type or sequence of types is given only those messages will be removed from the queue.

get会获取当前队列中的每一个事件，包括QUIT，键盘输入等等，get返回一个事件list（Eventlist），for循环遍历list中的每一个事件（event）并作出相应操作，所有事件遍历完就结束循环

下面是官方给出的一个根据键盘按下松开进行处理的一个实例

for event in pygame.event.get() :
  if event.type == pygame.KEYDOWN :
    if event.key == pygame.K_SPACE :
      print "Space bar pressed down."
    elif event.key == pygame.K_ESCAPE :
      print "Escape key pressed down."
  elif event.type == pygame.KEYUP :
    if event.key == pygame.K_SPACE :
      print "Space bar released."
    elif event.key == pygame.K_ESCAPE :
      print "Escape key released."

**Comment by orixing** [comment]
退出for循环结束后的其他事件会在队列中等待，直到完成一次大循环，进入while TRUE的下一次循环再取出
