### ISSUE TITLE
qt怎么为.h和.cpp文件创建.ui文件？

### ISSUE THREAD

**Issue by Eunice-grow** [buaa21/summer2020#104]

**Comment by PineZhuo** [comment]
一种思路是：
1、将.ui文件复制到与uic.exe同一文件夹中
2、在计算机开始中打开cmd
3、输入一下命令：
cd ***(文件夹位置路径)
uic ***.ui -o ***.h (生成.h文件)
uic ***.ui -o ***.cpp(生成.cpp文件)
4、生成的文件会保存在uic.exe所在文件夹中
