### ISSUE TITLE
追求代码量，还是使用简洁的函数，忍痛割爱

### ISSUE THREAD

**Issue by Alex-Mufeng** [buaa21/summer2020#105]
我这几天一直边学opencv边尝试提取识别目标区域，我按照工具书和官方文本和一堆博客写了将近100行来实现计算不规则图形轮廓周长的功能。结果今晚往后看书发现这就一句函数（cv2.approxPolyDP）的事,而且函数用的DP算法更准确。 换了这个函数或许这一百行py代码就省了。
随着学习，我发现opencv这个库太强大了，我感觉我这个项目要是全用里面的函数很难达到1k行。
现在纠结到底用库里的现成的函数，还是用自己写的。

**Comment by orixing** [comment]
你要是100行能写出1000行的效果你的分不会比1000行低
相比于造轮子，程序设计和实现更为重要
快速搞定你已设计的内容然后后续有时间可以继续添加新内容新功能

**Comment by orixing** [comment]
最早说的C语言1000行是为了让你们对做多少内容有一个基本的了解，不是硬性要求1000行，但如果不到1000行内容也过于单调肯定是不行的

**Comment by Alex-Mufeng** [comment]
> 你要是100行能写出1000行的效果你的分不会比1000行低
> 相比于造轮子，程序设计和实现更为重要
> 快速搞定你已设计的内容然后后续有时间可以继续添加新内容新功能

明白了，没那么绝望了

**Comment by crclz** [comment]
在任何的开发阶段，同学们都可以录制一个视频上传bilibili，然后到github来提issue，让助教和老师帮你参考一下是否符合要求、功能复杂度够不够。
