### ISSUE TITLE
面向对象是python参数问题

### ISSUE THREAD

**Issue by dwr2001** [buaa21/summer2020#106]
现在我使用了类的继承，把一些公有的方法放在超类中，具体的方法放在子类中，但是现在在超类中的一个公有的方法（假定为function）中我需要调用一个外部函数，这个外部函数需要一个在子类创建了的变量（这个变量需要在子类中，假定是number），现在我无法在超类中调用我需要的外部函数，不知道这时候是需要临时在超类中随便创建一个number然后再在子类创建时覆盖掉，还是为了这一个变量把整个function放到子类中？？？
```python
class A():
    def __init__(self):
        do something
    def public_function(self):
         do something
         onefunction#这里需要一个变量去调用一个函数，但这个变量是在子类中创建的
class subA(A):
    def __init__(self):
        super().__init__()
        do something
    def private_function(self):
         #创建一个变量，

```

**Comment by Withinlover** [comment]
（这和我昨天踩的坑一模一样

在写公共类的时候，首先得想明白究竟哪些变量是可以公用的，哪些是特殊的
包括函数的功能也是，在写代码之前首先要设计好， 确定每个函数所需要调用的参数

我最后选择了重构这两个类（

我重构时变量的定义基本没有变化，把这个起了冲突的函数功能一分为三，两个写在子类里面一个写在公共类
供参考

<del>再次提醒了我们思维导图的鲁棒性</del>

**Comment by dwr2001** [comment]
现在快好了我已经，方案就是直接传个参数，然后修改下这个函数就行，也主要不怎么会面向对象的东西，重构也得学下:smile:

**Comment by Withinlover** [comment]
昨天的口胡成功了（

**Comment by dwr2001** [comment]
对我目前就是你当时的想法，觉得这样类之间有比较大的区别

**Comment by dwr2001** [comment]
为什么不用qq说？hzy是吗？

**Comment by Lighten-w** [comment]
有余力的话，可以了解一下面向对象的设计原则
