### ISSUE TITLE
sublime插件开发，功能和代码量

### ISSUE THREAD

**Issue by zwx2238** [buaa21/summer2020#107]
代码量现在只有250＋，按预期计划扩展后估计代码量也不会超过500行，请问是否有功能建议？
视频地址：https://youtu.be/wuXcsasrwO4

**Comment by PineZhuo** [comment]
建议上传b站，youtube有可能翻墙失败（比如本人），助教不一定能看到视频。。。

**Comment by zwx2238** [comment]
b站审核忒慢了，现在还没过。。

**Comment by PineZhuo** [comment]
或者退而求其次，也可以用北航云盘来分享。很久不翻墙辽。。。VPN过期了（捂脸）

**Comment by zwx2238** [comment]
![image](https://user-images.githubusercontent.com/61327648/91600523-ab83d300-e99a-11ea-94b3-2298be219309.png)
遇到网站bug，只买了一个月，给我续费100年了😂

**Comment by zwx2238** [comment]
https://bhpan.buaa.edu.cn:443/link/B94E37FA7832E7E688CBB87D7F640DB6
Valid Until: 2020-09-27 23:59

**Comment by songyou21** [comment]
没有太看懂做得啥？加点说明啥，或视频中带语音讲解，就好了。

**Comment by zwx2238** [comment]
最前面写了一页，就是txt导图的搜索和修改

**Comment by iceryang** [comment]
最好再想想扩展功能，现在才第六天。还有时间。

**Comment by iceryang** [comment]
最好再想想扩展功能，现在才第六天。还有时间。

**Comment by iceryang** [comment]
最好再想想扩展功能，现在才第六天。还有时间。

**Comment by iceryang** [comment]
最好再想想扩展功能，现在才第六天。还有时间。

**Comment by iceryang** [comment]
最好再想想扩展功能，现在才第六天。还有时间。

**Comment by havesomecolo** [comment]
可以找个xml的文档编辑器参考下，看看人家怎么做树形结构的文本编辑的。比如下个xmlspy看看

**Comment by zwx2238** [comment]
> 没有太看懂做得啥？加点说明啥，或视频中带语音讲解，就好了。
做了一个有语音的视频，可能太啰嗦了点。。
链接：https://pan.baidu.com/s/1WIxbLpnJXQM62DFZdPCmGQ 
提取码：or9v

**Comment by Roycent** [comment]
建议添加可视化功能（直接可视化编辑可能工作量略大，但是至少要从txt生成脑图）。说实话从目前功能来看，与普通的文本编辑器相比，并没有发现一些明显减少工作量的亮点。

**Comment by zwx2238** [comment]
> 建议添加可视化功能（直接可视化编辑可能工作量略大，但是至少要从txt生成脑图）。说实话从目前功能来看，与普通的文本编辑器相比，并没有发现一些明显减少工作量的亮点。

不会减少编辑的工作量，但是可以大大减少编辑的启动过程。传统导图需要分成多个文件存储，需要先找到导图文件，在找到节点，最后还要按一下快捷键收级上级目录。
核心的点就是搜索页面只展示到预定义的分界线处，屏蔽了无关信息。比如搜索数学，我不希望看到微积分内部的具体内容。

**Comment by zwx2238** [comment]
txt转导图是天然支持的，直接复制粘贴即可
