### ISSUE TITLE
c++如何实现音乐播放

### ISSUE THREAD

**Issue by Innovator-h** [buaa21/summer2020#108]
c++播放音乐需要应用什么函数

**Comment by SeventhGX** [comment]
PlaySound()，mciSendString()，以及更加专业的DirectX，都可以用来播放音频

**Comment by Zehong3351** [comment]
第一种方式：
在.h加入
#include "mmsystem.h"
#include "windows.h"
#pragma comment(lib,"winmm.lib")//導入聲音頭文件庫

.cpp写
//播放内部资源(.wav格式)音乐，异步方式播放，指定是WAVE资源标识符，不播放缺省声音，音乐循环
PlaySound(MAKEINTRESOURCE(IDR_WAVE1),AfxGetResourceHandle(), SND_ASYNC|SND_RESOURCE|SND_NODEFAULT|SND_LOOP);

只支持.wav格式音乐文件,mp3、flac等格式可百度寻找方法转换成wav格式

一些用过这个函数的人一般都会碰到一些问题：
1.内部资源wav如何导入？ 答:ResourceView->右击根目录->引入->选中.wav格式文件
2.出现无法编译通过错误，一般由导入库文件的方式有误引起.
解决方案:(1)一定要是在头文件中加入，上面3个。(2)检查是否写错了（3）添加库文件方式稳妥方法可用:工程->设置->连接->对象/库模块:加上WINMM.LIB 若有多个，打个空格再加上去 按确认，这个操作后 相当于#pragma comment(lib,"winmm.lib")
3.若无法播放声音，检查PlaySound()的第三个参数序列，SND_RESOURCE在加载内部资源的时候必须要加上，其他次要。

第二种方式:
使用绝对路径加载音乐 前面步骤一样，改写PlaySound()函数参数
PlaySound("音乐路径",AfxGetResourceHandle(), SND_ASYNC|SND_NODEFAULT|SND_LOOP);

**Comment by Innovator-h** [comment]
> PlaySound()，mciSendString()，以及更加专业的DirectX，都可以用来播放音频

我用mciSendString()，代码文件能够编译成功，但是运行时没有音乐播放，音乐文件未打开。代码如下：

（头文件）
#include<graphics.h>
#include<conio.h>
#include<stdio.h>
#include<stdlib.h>
#include<windows.h>
#include<mmsystem.h>    //用于加载音乐
#pragma comment(lib,"Winmm.lib")    //加载windows文件

（主程序）
mciSendString(TEXT("open E:\\Vscode\\mishitaotuo\\Music\\music_bk.mp3 alias musicbk"),NULL,0,NULL); //打开mp3文件并命名
mciSendString(TEXT("open musicbk repeat"),NULL,0,NULL); //循环播放musicbk

**Comment by SeventhGX** [comment]
> > PlaySound()，mciSendString()，以及更加专业的DirectX，都可以用来播放音频
> 
> 我用mciSendString()，代码文件能够编译成功，但是运行时没有音乐播放，音乐文件未打开。代码如下：
> 
> （头文件）
> #include<graphics.h>
> #include<conio.h>
> #include<stdio.h>
> #include<stdlib.h>
> #include<windows.h>
> #include<mmsystem.h> //用于加载音乐
> #pragma comment(lib,"Winmm.lib") //加载windows文件
> 
> （主程序）
> mciSendString(TEXT("open E:\Vscode\mishitaotuo\Music\music_bk.mp3 alias musicbk"),NULL,0,NULL); //打开mp3文件并命名
> mciSendString(TEXT("open musicbk repeat"),NULL,0,NULL); //循环播放musicbk

#include "stdafx.h"
#include <iostream>
#include <windows.h>
#include <mmsystem.h>
#pragma comment(lib,"winmm.lib")
using namespace std;

void test()
{
	mciSendString(TEXT("open E:/音乐/不老梦重置南北.mp3"), NULL, NULL, NULL);//打开音乐文件
		mciSendString(TEXT("play E:/音乐/不老梦重置南北.mp3"), NULL, NULL, NULL);//播放音乐
			int a = 0;
	while (1)
	{
		cout << "音乐已经播放了" << a << "秒" << endl;
		Sleep(1000);
		a++;
	}
	mciSendString(TEXT("close E:/音乐/不老梦重置南北.mp3"), NULL, NULL, NULL);//关闭文件,当然这句话是执行不到的
}

int main()
{
	test();
	return 0;
}
我这样是可以运行的，你的文件路径用 \ 确定可行吗，我印象中c++的路径要用 \\ 或者 / 来着

**Comment by Innovator-h** [comment]
> > > PlaySound()，mciSendString()，以及更加专业的DirectX，都可以用来播放音频
> > 
> > 
> > 我用mciSendString()，代码文件能够编译成功，但是运行时没有音乐播放，音乐文件未打开。代码如下：
> > （头文件）
> > #include<graphics.h>
> > #include<conio.h>
> > #include<stdio.h>
> > #include<stdlib.h>
> > #include<windows.h>
> > #include<mmsystem.h> //用于加载音乐
> > #pragma comment(lib,"Winmm.lib") //加载windows文件
> > （主程序）
> > mciSendString(TEXT("open E:\Vscode\mishitaotuo\Music\music_bk.mp3 alias musicbk"),NULL,0,NULL); //打开mp3文件并命名
> > mciSendString(TEXT("open musicbk repeat"),NULL,0,NULL); //循环播放musicbk
> 
> #include "stdafx.h"
> #include
> #include <windows.h>
> #include <mmsystem.h>
> #pragma comment(lib,"winmm.lib")
> using namespace std;
> 
> void test()
> {
> mciSendString(TEXT("open E:/音乐/不老梦重置南北.mp3"), NULL, NULL, NULL);//打开音乐文件
> mciSendString(TEXT("play E:/音乐/不老梦重置南北.mp3"), NULL, NULL, NULL);//播放音乐
> int a = 0;
> while (1)
> {
> cout << "音乐已经播放了" << a << "秒" << endl;
> Sleep(1000);
> a++;
> }
> mciSendString(TEXT("close E:/音乐/不老梦重置南北.mp3"), NULL, NULL, NULL);//关闭文件,当然这句话是执行不到的
> }
> 
> int main()
> {
> test();
> return 0;
> }
> 我这样是可以运行的，你的文件路径用 \ 确定可行吗，我印象中c++的路径要用 \\ 或者 / 来着

已解决，我的TEXT中播放的那行代码写了“OPEN”，改为“PLAY”就可以了，谢谢。
