### ISSUE TITLE
pygame怎么添加用户注册功能

### ISSUE THREAD

**Issue by 19231219lsm** [buaa21/summer2020#109]
我想再添加一个注册功能，想的比较简单，就把每次分数保存到一个文档后，匹配对应用户。
要用到啥模块？我在网上搜了一圈，没看到我想的那种功能实现，不知道是不是我搜索的关键词不对？

**Comment by Lighten-w** [comment]
最简单的一种实现，是把注册信息保存在一个本地文档里，登录的时候再读取检查
可以参考这里-->[Python文件读写](https://www.runoob.com/python3/python3-file-methods.html)

或者可以注册时信息保存到数据库，登陆时查询检查，python的话可以简单了解一下[sqlite](https://www.runoob.com/sqlite/sqlite-python.html)，或者Mysql

**Comment by Zehong3351** [comment]
需要独立出一个登陆注册的模块儿。可以采用两种方式，一是读写文件，即将用户的信息写入文件中，每次读写都调用这个文件；二是读写数据库，可以利用mysql,创建一个表，设定好对应的属性值即可。
