### ISSUE TITLE
eclipse怎么安装

### ISSUE THREAD

**Issue by starrrrgazer** [buaa21/summer2020#11]
已经安装了 jdk-11.0.8 , 并且设置好了环境变量JAVA_HOME，CLASSPATH，Path，但打开eclipse-inst-win64.exe 还是跳转到网页，显示我并没有安装jdk

**Comment by crclz** [comment]
1. 我不知道你的这些环境变量配置对了没。我建议你使用AdoptOpenJDK，它的安装程序里面有配置PATH、JAVA_HOME的选项。
2. 也可以多看几个安装Eclipse的教程，因为某个教程可能有问题。
3. 还可以换IDEA。IDEA比Eclipse好用，并且学生有edu邮箱，可以免费享受Ultimate版

**Comment by starrrrgazer** [comment]
> 1. 我不知道你的这些环境变量配置对了没。我建议你使用AdoptOpenJDK，它的安装程序里面有配置PATH、JAVA_HOME的选项。
> 2. 也可以多看几个安装Eclipse的教程，因为某个教程可能有问题。
> 3. 还可以换IDEA。IDEA比Eclipse好用，并且学生有edu邮箱，可以免费享受Ultimate版

emmm，谢谢，不过我最后也没发现哪里出问题，从同学那获得了JDK和eclipse后重新安装成功了
