### ISSUE TITLE
为什么有些属性明明官方网站上有，而且我也在指令集中引用了，vs还一直报错

### ISSUE THREAD

**Issue by Ocean326** [buaa21/summer2020#110]
例如这个属性https://docs.microsoft.com/zh-cn/dotnet/api/system.windows.forms.richtextbox.selectionfont?view=netframework-4.7.2

我在项目的引用中也包含了using System.Windows.Forms;

错误	CS1061	'“RichTextBox”未包含“fin”的定义，并且找不到可接受第一个“RichTextBox”类型参数的可访问扩展方法“fin”(是否缺少 using 指令或程序集引用?)

**Comment by crclz** [comment]
你的代码里面里面是否有`xxx.fin`?

**Comment by Ocean326** [comment]
没有（那是啥orz

**Comment by Lighten-w** [comment]
建议发下代码截图和错误信息

**Comment by crclz** [comment]
这是你的错误信息
> 错误 CS1061 '“RichTextBox”未包含“fin”的定义，并且找不到可接受第一个“RichTextBox”类型参数的可访问扩展方法“fin”(是否缺少 using 指令或程序集引用?)

显然你调用了`xxx.fin`方法，(xxx是一个`RichTextBox`实例)。
你看编译的错误信息，然后点进去就看得到哪里有问题了。

**Comment by Zehong3351** [comment]
你需要看一下，自己是不是哪里调用了这个RichTextBox里面的fin方法啊。

**Comment by Ocean326** [comment]
（当时手滑，fin是个意外
应该是Richtextbox.SelectionFont
引用了System.window.Forms和WindowsFormsIntegration后还是缺少指令集
