### ISSUE TITLE
Android Studio如何直接连接SQLserver数据库

### ISSUE THREAD

**Issue by Cirtl** [buaa21/summer2020#111]
如题，需要下载哪些内容？手机可以通过网络直接连接此数据库吗？

**Comment by Lighten-w** [comment]
可以参考[这篇博客](https://www.cnblogs.com/panqiaoyan/p/12869971.html)

PS：理论上来说数据库链接应该放在服务端，客户端负责发送请求和读取结果等

**Comment by Cirtl** [comment]
参照那篇博客，我在修改SQLserver登录名密码时卡住了，感觉就是一直不能保存我修改后的密码

**Comment by Cirtl** [comment]
修改密码问题已解决（原因：未勾选 映射到凭据 ）
