### ISSUE TITLE
VS code的报错

### ISSUE THREAD

**Issue by shensanfei** [buaa21/summer2020#112]
![image](https://user-images.githubusercontent.com/56460719/91627652-591ed280-e9eb-11ea-8d8a-b18907cc0fe9.png)
如图，个人感觉应该不会报错

**Comment by orixing** [comment]
放一下报错的代码？

**Comment by shensanfei** [comment]
![image](https://user-images.githubusercontent.com/56460719/91627792-9fc0fc80-e9ec-11ea-8386-fe2d3afd8209.png)
![image](https://user-images.githubusercontent.com/56460719/91627797-ac455500-e9ec-11ea-9e69-c22f495227a6.png)

**Comment by PineZhuo** [comment]
可以尝试这个教程：
https://blog.csdn.net/qq_42780289/article/details/88354802

**Comment by Lighten-w** [comment]
如果能跑就没有问题，pylint有时无法识别一些运行时创建的方法

**Comment by Roycent** [comment]
Pylint只是代码规范检查工具
