### ISSUE TITLE
VS2017软件运行报错

### ISSUE THREAD

**Issue by notgoodpeople** [buaa21/summer2020#113]
由于找不到OpenAL32.dll，无法继续执行代码。重新安装程序可能会解决此问题。  这种错误每次都莫名其妙的出来，有时候报错有时候不报错，请问这种错误怎么解决？

**Comment by Roycent** [comment]
由于你没有提供源码，不能确定是不是你的代码调用了相关API。可以去网上搜索下载一个这个dll文件，放到系统文件夹里

**Comment by Zehong3351** [comment]
首先确认如果是引用外部程序，确保文件是否隐藏在外部资源包内，查找，在程序属性中常规里添加外部资源位置，直接简单粗暴将需要的文件放入安装目录：C盘-----Program Files(x86)-----Windows------System32.

**Comment by songoku1994** [comment]
可以找一下这个dll文件放到安装目录里

**Comment by SeventhGX** [comment]
是qt吗，或许可以看下这个？https://bbs.csdn.net/topics/392711015

**Comment by notgoodpeople** [comment]
问题已解决，我把缺失的文件放到安装目录里就不报错了。谢谢。
