### ISSUE TITLE
pygame在游戏界面上输入文字

### ISSUE THREAD

**Issue by xiazaiba7** [buaa21/summer2020#114]
想用pygame做一个界面，让玩家可以在这个界面上输入文字，具体该用到哪些函数和模块呢？
大致效果是，界面的中央出现文字：“请输入xxx”，然后玩家可以输入一些东西，再按回车跳转到下一界面

**Comment by Zehong3351** [comment]
自带的好像真的没有啊。除非就是弹出新的窗口。你可以看看这个例子啊~
https://github.com/Mekire/pygame-textbox、

**Comment by SeventhGX** [comment]
试试这个？ https://blog.csdn.net/qq_39687901/article/details/104684429
**3.用法
用法很简单

1.创建一个TextBox对象

TextBox参数说明：

w:输入框的宽

h:输入框的高

x:输入框左上角x坐标

y:输入框左上角y坐标

font:字体（可以不传）

callback:按下回车之后的回调函数，这个函数必须有一个参数用来接收文本框中的字符串

 

2.在键盘按下事件时调用TextBox对象的safe_key_down(event)方法，记住要把pygame的event传进去

3.记得调用TextBox的draw(surface)方法，显示输入框**
