### ISSUE TITLE
如何将一个类的属性与另一个类的属性关联起来

### ISSUE THREAD

**Issue by lzy248** [buaa21/summer2020#115]
比如我有一个地图类，属性有坐标x和y，地图是移动的；然后是一个小球类，属性也是坐标m和n，小球要运动，但是是相对移动的地图而移动，所以要把地图的坐标属性和小球的坐标属性相关联，怎么实现（python）

**Comment by lzy248** [comment]
python语言

**Comment by Zehong3351** [comment]
根据你的描述，是相对地图的移动而言。那么就可以将小球的坐标，设成地图坐标+或-你想移动的位置。这样就可以关联了啊

**Comment by lzy248** [comment]
> 根据你的描述，是相对地图的移动而言。那么就可以将小球的坐标，设成地图坐标+或-你想移动的位置。这样就可以关联了啊

噢，我可以在输出的时候转换坐标，我之前一直想的是在小球的move方法中实现，就变成每一次输出都要加上地图坐标了
