### ISSUE TITLE
pycahrm 运行相同代码同样操作有时有时不报错

### ISSUE THREAD

**Issue by abc12399** [buaa21/summer2020#116]
添加一个功能后，影响到其他功能，报错时出现这样的问题，之前设置的屏幕滚动也不滚了，添加的功能有时正常有时不正常
![image](https://user-images.githubusercontent.com/70189650/91631071-57fc9e00-ea09-11ea-927b-9ab15cac5640.png)

**Comment by SeventhGX** [comment]
单看这个错误信息（实例tuple中没有属性y）我也看不出啥，只能暂时认为你添加的代码里有bug...

**Comment by abc12399** [comment]
> 单看这个错误信息（实例tuple中没有属性y）我也看不出啥，只能暂时认为你添加的代码里有bug...

但是运行有时不报错，有时报错

**Comment by SeventhGX** [comment]
> > 单看这个错误信息（实例tuple中没有属性y）我也看不出啥，只能暂时认为你添加的代码里有bug...
> 
> 但是运行有时不报错，有时报错

代码里有用到随机数吗，或者调用的某些函数包含随机要素

**Comment by iceryang** [comment]
用debug打断点看一下。

**Comment by abc12399** [comment]
> > > 单看这个错误信息（实例tuple中没有属性y）我也看不出啥，只能暂时认为你添加的代码里有bug...
> > 
> > 
> > 但是运行有时不报错，有时报错
> 
> 代码里有用到随机数吗，或者调用的某些函数包含随机要素

别的函数有用到

**Comment by abc12399** [comment]
> 用debug打断点看一下。

pycharm该怎样用debug工具呢

**Comment by SeventhGX** [comment]
> > > > 单看这个错误信息（实例tuple中没有属性y）我也看不出啥，只能暂时认为你添加的代码里有bug...
> > > 
> > > 
> > > 但是运行有时不报错，有时报错
> > 
> > 
> > 代码里有用到随机数吗，或者调用的某些函数包含随机要素
> 
> 别的函数有用到

那就先尝试固定随机数种子，百度可以找到方法，例：https://blog.csdn.net/weixin_43283397/article/details/100567216 
pycharm断点调试百度能搜到很多教程博客，例：https://blog.csdn.net/huang_shao1/article/details/82251658
