### ISSUE TITLE
c语言设置多选项弹窗

### ISSUE THREAD

**Issue by c-hn** [buaa21/summer2020#117]
我在网上看到的关于c语言弹窗的建议是用messagebox，但是这个的弹窗好像只有是否，确定取消之类的选项，请问一下有没有方法能做出一个有多选项的弹窗。

**Comment by Lighten-w** [comment]
提供一个思路：建一个空白弹窗，向里面添加按钮

**Comment by c-hn** [comment]
那请问空白弹窗怎么建呢……是有一个特定的函数吗

**Comment by Lighten-w** [comment]
不确定你用的是什么，可以看一下qt，里面的图形界面相对比较简单，文档也比较详细

**Comment by c-hn** [comment]
我在网上搜到的qt好贵啊...我用的vs2019,有什么方法可以用vs2019建空白弹窗吗
