### ISSUE TITLE
VS code Python 这样报错是为什么

### ISSUE THREAD

**Issue by mengliuchang** [buaa21/summer2020#118]
哎呀，出现问题。请在报告此 Bug 时添加 
以下详细信息。
在 GitHub 上报告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------     
上 200 个密钥:
 i c r o s o f t \ W i n d o w s A p p s \ p y t h o n . e x e ' Space ' c : \ U s e r s \ l e n o v o \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 8 . 1 0 5 0 4 5 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 5 1 7 5 1 ' Space ' - - ' Space ' c : \ U s e r s \ l e n o v o \ D e s k t o p \ S u p e r M a r i o \ m a i n . p y ' Space Enter

异常:
System.ArgumentOutOfRangeException: 该
值必须大于或等于零，且必须小于控制台缓
冲区在该维度的大小。
参数名: left
实际值是 -1。
   在 System.Console.SetCursorPosition(Int32 left, Int32 top)
   在 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   在 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   在 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   在 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   在 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   在 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   在 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   在 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)       
-----------------------------------------------------------------------     
PS C:\Users\lenovo\Desktop\SuperMario>

**Comment by mengliuchang** [comment]
重启了一下电脑和软件，又不报错了。是因为控制台信息太多了吗？

**Comment by songoku1994** [comment]
可以看下这个https://www.zhihu.com/question/349626964，有可能是控制台东西太多了

**Comment by songoku1994** [comment]
可以看下这个，可能是控制台东西太多了：https://www.zhihu.com/question/349626964
