### ISSUE TITLE
关于小游戏测试的问题

### ISSUE THREAD

**Issue by 1921zzk** [buaa21/summer2020#119]
已经写了小游戏雏形，目前试了几次是正常运行，但还是担心有没有其他的bug，所以想问一下一般可以从哪些方面去测试自己的小游戏代码有没有bug。

**Comment by SeventhGX** [comment]
测试bug最好的办法就是穷举...
从一个状态出发，列出此时可以进行的全部操作，分别执行，进入不同的状态，然后重复之前的流程
尽量覆盖程序所有可能的状态，把所有可能进行的操作都试几下，看有没有问题
