### ISSUE TITLE
应该如何实现网页的重定向

### ISSUE THREAD

**Issue by fa-yuanyu** [buaa21/summer2020#120]
例如, 我希望当用户访问www.example.com时会自动被重定向至www.example.com/index.html

**Comment by SeventhGX** [comment]
试试这个？ https://www.feiniaomy.com/post/196.html

**Comment by Lighten-w** [comment]
不知道你现在用的什么框架，也可以在后端设置访问www.example.com时重定向www.example.com/index.html，django的具体实现可以看下[这个链接](https://zhuanlan.zhihu.com/p/41547331)
