### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by 1921zzk** [buaa21/summer2020#124]
怎么将小游戏以及要用到的背景图片和音乐等打包成exe文件。

**Comment by Lighten-w** [comment]
python的话，可以看一下pyinstaller

**Comment by 1921zzk** [comment]
但是用pyinstaller打包完以后总是spec文件，还有图片，背景音乐怎么转化成py文件一起打包。

**Comment by Lighten-w** [comment]
打包图片音乐等资源，以及spec文件的用法，可以参考下[这个博客](https://blog.csdn.net/sinat_27382047/article/details/81304065)

**Comment by Withinlover** [comment]
官方文档里面其实给出了写法 
[--add-data 以及 --add-binary](https://pyinstaller.readthedocs.io/en/v4.0/man/pyinstaller.html?highlight=--add-data#what-to-bundle-where-to-search)

不过你在引用图片或者目录时如果是 import os 获取的路径，此方法可能会失效

将你的代码中导入图片，音频的地址写死为 相对 / 绝对地址， 就可以直接打包了
