### ISSUE TITLE
用SFML库如何在窗口中显示文本？

### ISSUE THREAD

**Issue by notgoodpeople** [buaa21/summer2020#125]
如题。已经自己查了一些资料，但依然无法在窗口中显示文本。  下面是我写的代码。
        Text score;               //本来想用score来显示分数
	score.setString("hello");
	score.setFillColor(Color::Black);                      //背景图是白色
	score.setPosition(258, 45);                             
        score.setCharacterSize(30);
	window.draw(score);

**Comment by Roycent** [comment]
文字需要字体（sf::Font）来初始化。https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Text.php

**Comment by notgoodpeople** [comment]
已解决，谢谢~
