### ISSUE TITLE
关于C语言使用remove函数删除文件无法删除的问题

### ISSUE THREAD

**Issue by 19373759** [buaa21/summer2020#126]
我先用fclose关闭了要删除的文件，然后使用remove函数对其进行删除，但是根据返回值判断我并没有删除掉这个文件。但是这个问题在我另外编写的一个程序中并没有出现。这可能是什么原因呢？或者说有没有别的方法来将文件删除？

**Comment by SeventhGX** [comment]
不应该啊，检查一下路径、文件是否为只读，以及所有打开这个文件的地方都关闭了？
除了remove，c语言也可以用system函数，通过系统命令删除文件

**Comment by 19373759** [comment]
> 不应该啊，检查一下路径、文件是否为只读，以及所有打开这个文件的地方都关闭了？
> 除了remove，c语言也可以用system函数，通过系统命令删除文件

谢谢，确实是文件关闭的问题 已经解决了
