### ISSUE TITLE
pygame输出元素不全，出现幽灵元素，有相互作用但不显示，而其他同类元素输出正常

### ISSUE THREAD

**Issue by lzy248** [buaa21/summer2020#127]
视频：第15秒出出现bug现象，吃到一个幽灵球球，最后也因为找不到最后一个球而无法结束
https://www.bilibili.com/video/BV1qv41117vH/
源码
[desktop.zip](https://github.com/buaa21/summer2020/files/5145057/desktop.zip)

**Comment by orixing** [comment]
emm还是先通过代码检查一下，控制台输出一下所有小球的位置，看看是不是绘制的问题。
我个人更倾向于用排除法来改bug，直接看代码有的时候看不出问题，搞不定qq找我
