### ISSUE TITLE
随着元素减少，界面速度变快的问题，无法解决

### ISSUE THREAD

**Issue by lzy248** [buaa21/summer2020#129]
如视频：https://www.bilibili.com/video/BV1PK4y1a7Jx/
源码
[game.zip](https://github.com/buaa21/summer2020/files/5145059/game.zip)

**Comment by orixing** [comment]
原因可能是每次主循环一次循环所花费的时间越来越短，两个解决方案：1根据上次循环时间调整移动距离。2.用delay保证每次主循环耗时一致

**Comment by lzy248** [comment]
> 原因可能是每次主循环一次循环所花费的时间越来越短，两个解决方案：1根据上次循环时间调整移动距离。2.用delay保证每次主循环耗时一致
我用时间戳看过，每一次循环几乎都是0.017秒左右

**Comment by orixing** [comment]
emm这个问题蛮麻烦的，你试试控制台输出一下每次移动的距离，移动前后坐标和当前时间，看能不能发现问题，不行的话qq找我

**Comment by lzy248** [comment]
我又仔细看过了，当我设置出两个球的时候每隔0.02秒输出一次，但是吃掉一个球之后，另一个球就变成0.01秒输出一次了，这应该是变快的原因，但是为什么会变快呢输出时间

**Comment by lzy248** [comment]
啊 ，我解决了，问题是我先设置了一个数量，但是被吃掉的时候那个数没有减一，然后我的for循环就会多循环一次，某些球就会一次输出两次运动，越少就越明显
