### ISSUE TITLE
有哪些能做出好看的GUI的方法？

### ISSUE THREAD

**Issue by cynic-1** [buaa21/summer2020#13]
用Java的swing或者Javafx做的GUI太丑了，没眼看

**Comment by crclz** [comment]
1. 对于开发Windows桌面app，WPF和Winform是非常好的选择。WPF有组件库，例如 [MaterialDesignInXamlToolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit)。但是WPF需要一定的学习成本（WPF是MVVM的始祖），而且学习资料不多。
2. 开发应用程序还是应当以**业务**功能为主要目标。对于学生来说，跨平台、好看的UI等需求，大多数情况下可以称作为洁癖。所以我的建议是就使用你最熟悉的技术，例如swing，来开发一个APP。
3. 一个可选的方案：可以去开发交互式网站。因为网站开发的学习资料和生态是最好的，界面也有相应的UI库。

**Comment by Roycent** [comment]
Java也有GUI的组件库，不过就像再漂亮的网页也是基于js/css/html一样，这些组件其实还是依赖于Swing或者JavaFX等等。比如ControlsFX等等，你也可以在搜索引擎、github查找其他组件库。
