### ISSUE TITLE
pygame中如何实现随机

### ISSUE THREAD

**Issue by zyqzyq007** [buaa21/summer2020#131]
使用random函数会在每一次的屏幕update中变成不同的东西，我想让它random一次（绘制一个随机地图）并在之后的屏幕update中保持不变，一直到我设计的某个变量改变再新一次random

**Comment by lzy248** [comment]
可以建一个地图类用属性保存生成的随机地图

**Comment by orixing** [comment]
random完了之后找个地方存起来，直到下一次random

**Comment by songoku1994** [comment]
那你就不能在每一次update中都进行一次地图的随机了，具体方法可以找一些随机地图的案例来看看
