### ISSUE TITLE
qt，程序异常结束

### ISSUE THREAD

**Issue by Eunice-grow** [buaa21/summer2020#132]
出现提示：*** Fault tolerant heap shim applied to current process. This is usually due to previous crashes. ***
程序异常结束。
查询得知，这类问题的本质是内存泄露。
将实现具体功能部分的代码都注释掉，只留下窗口的设置后，依旧如此。
那请问，可能是什么情况导致的，内存泄漏？

**Comment by Roycent** [comment]
https://blog.csdn.net/llazy123/article/details/80763448 尝试一下修改注册表的方法
