### ISSUE TITLE
2048游戏ai模式应该用什么算法

### ISSUE THREAD

**Issue by jianhong1009** [buaa21/summer2020#133]
试着写了个fake ai，ai玩到128的方块出来就死局了，网上找了些但是那些算法大部分都看不懂，有什么比较简单能自己实现的算法吗

**Comment by IAmParasite** [comment]
可以在github上找一下是否有类似的项目，阅读一下项目的README，算法的应该是没有简单的算法，类似于贪心等等的算法可以自己尝试写一写，但是可能效果不是很好

**Comment by Lighten-w** [comment]
可以参考一下[这个](https://blog.csdn.net/sky_j123/article/details/37832803)，不过也有些复杂

**Comment by songoku1994** [comment]
这篇也可以参考一下：https://blog.csdn.net/qq_32767041/article/details/80634244
