### ISSUE TITLE
【开发进度】恳请各位助教和老师提下建议

### ISSUE THREAD

**Issue by longzhenren** [buaa21/summer2020#134]
https://www.bilibili.com/video/av754459767
（突然感到力不从心）

**Comment by songyou21** [comment]
感觉可以呀！接下来几天继续完善下去，应该是不错的作品。
作品介绍的视频太长了（13min），控制的5甚至3min之内，则最佳。
期待接下来几天看到更大的进步。

**Comment by longzhenren** [comment]
> 感觉可以呀！接下来几天继续完善下去，应该是不错的作品。
> 作品介绍的视频太长了（13min），控制的5甚至3min之内，则最佳。
> 期待接下来几天看到更大的进步。

好的 谢谢老师！
（就怕自己弄偏题了）
