### ISSUE TITLE
Java开发的游戏如何部署在网络上实现联机对战

### ISSUE THREAD

**Issue by cynic-1** [buaa21/summer2020#139]
如题

**Comment by crclz** [comment]
1. 采用minecraft的模式：某个人的游戏充当服务器，其他人的都与这个人通信
2. 通信方式：socket
3. 传输的数据：举个例子，客户端向服务端发送操作数据（向上、向下）或者本人坐标，服务端向客户端发送必要游戏数据以供客户端渲染。
