### ISSUE TITLE
微信小程序开发的代码量怎么计算呢

### ISSUE THREAD

**Issue by RaymondKevin** [buaa21/summer2020#14]
微信小程序也是像HTML那样有.html .css .js .json这样好几个文件，怎么来衡量这其中的工作量呢？

**Comment by havesomecolo** [comment]
主要计算手工编写的代码量，系统生成的不计入

**Comment by RaymondKevin** [comment]
也是按1k行的标准来衡量，是这样的吗？

**Comment by havesomecolo** [comment]
是的。1K不是硬条件，是一个参考标准
