### ISSUE TITLE
visual studio 2019自带的sql server如何配置使用

### ISSUE THREAD

**Issue by Z8232000** [buaa21/summer2020#140]
如题
网上没有找到适用的教程

**Comment by Z8232000** [comment]
或者，是否更建议安装数据库？

**Comment by songoku1994** [comment]
自带的localDB也可以比较轻量，但也可以使用，可以参考一下：https://www.cnblogs.com/Traveller-Lee/p/5776312.html
当然，安装一个数据库也是可以的

**Comment by crclz** [comment]
自己安装数据库吧（或者使用sqlite），教程比较好找
