### ISSUE TITLE
我想游戏界面可以拉伸（使用pygame）

### ISSUE THREAD

**Issue by 19231219lsm** [buaa21/summer2020#141]
怎么使游戏中的元素同比例的拉伸缩小（背景，角色这类的东西），伸缩完后总有一些黑色的部分

**Comment by orixing** [comment]
用屏幕长款的百分比控制元素大小

**Comment by 19231219lsm** [comment]
> 用屏幕长款的百分比控制元素大小

不是很明白，感觉现在是我那个背景图的问题，它的尺寸固定，拉伸后就会出来一块黑色的区域

**Comment by Lighten-w** [comment]
> 不是很明白，感觉现在是我那个背景图的问题，它的尺寸固定，拉伸后就会出来一块黑色的区域

尺寸固定的话大小就不会变，你要让他随着窗口拉伸而变化，就要让尺寸变化
