### ISSUE TITLE
在使用pyinstaller打包py程序的时候，总是会报错，找不到第三方库的某个文件，有什么解决办法

### ISSUE THREAD

**Issue by lhzforever** [buaa21/summer2020#142]
![QQ图片20200830101636](https://user-images.githubusercontent.com/68690819/91649773-05bf8980-eaaa-11ea-91ca-00d57140aa93.png)
如图

**Comment by Roycent** [comment]
pyinstaller的[Wiki](https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages)中写了目前不兼容pyecharts,是会报错的。其他博客有一些尝试解决的方法，比如https://blog.csdn.net/weixin_43865152/article/details/93781051以及https://www.cnblogs.com/YannisChou/p/10338518.html 。这些方法都没法解决的话可以继续用关键字pyinstaller + pyecharts搜索其他解决方法。
