### ISSUE TITLE
Unity中做好的游戏如何导入Android studio呢？

### ISSUE THREAD

**Issue by Cashiion** [buaa21/summer2020#143]
unity如何与Android studio联动呢？想由Android studio 设置界面，最后由Android studio 进行导出apk。

**Comment by Roycent** [comment]
Unity是可以直接导出APK或者调用安卓API的，但是从 Android 端并不能直接调用 Unity 脚本，而是通过消息发送或者接口回调的方式实现。参考 https://www.jianshu.com/p/b5e3cfcdf081

**Comment by songoku1994** [comment]
应该要用到Gradle，可以参考一下这个：https://www.jianshu.com/p/31b8877de531

**Comment by Cashiion** [comment]
谢谢！
