### ISSUE TITLE
Android Studio中设置了对Button的点击事件却无响应

### ISSUE THREAD

**Issue by Cirtl** [buaa21/summer2020#144]
![image](https://user-images.githubusercontent.com/70183047/91650074-859b2300-eaad-11ea-9163-db57a147ef73.png)
![image](https://user-images.githubusercontent.com/70183047/91650081-95b30280-eaad-11ea-82bd-d96d506f07a0.png)

**Comment by Roycent** [comment]
Toast的用法是不是有问题？应该是要先Toast toast = Toast.maketText(...);然后再toast.show();吧
