### ISSUE TITLE
python中关于类的继承问题

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#145]
如题，发现自己对类有点不太理解。例如pygame.sprite和pymunk.body这些都是类吗？点后面的内容是不是代表着类里面的方法？
那么如果我想要建立一个新的类，使他既能通过pygame中的键盘输入控制，又能具有pymunk中的物理属性，是否可以新建一个类来继承他们呢？

**Comment by orixing** [comment]
pygame.sprite是模块（pygame module with basic game object classes）
其中包含许多类和方法http://www.pygame.org/docs/ref/sprite.html
pygame.sprite.Sprite是类：Simple base class for visible game objects.
这个类中又包含了类的方法：https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.Sprite

python是可以多继承的，但不鼓励多继承。你说的这个方法可以尝试，我也没试过XD

**Comment by orixing** [comment]
另，如果多继承能较好的解决pymunk和pygame的结合的话qq联系我一哈

**Comment by hrx20000209** [comment]
好的。那一般想要将两者结合的话是使用什么方法呢
