### ISSUE TITLE
c语言如何进行游戏的时间限制

### ISSUE THREAD

**Issue by Rander-sun** [buaa21/summer2020#146]
如题，c语言该怎么一边进行游戏一边设置一个定时器，由于我的游戏是一个while循环，需要在循环内设置一个不受循环影响的定时器，在60s后自动退出循环，该怎么做到？

**Comment by Rander-sun** [comment]
还需要实现一个功能：每隔一秒就要有一个int变量（计时器）变一下数字，用来在游戏窗口上记录时间

**Comment by crclz** [comment]
可以使用`Windows.h`的`GetTickCount`函数实现。
文档：https://docs.microsoft.com/zh-cn/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount

> The return value is the number of milliseconds that have elapsed since the system was started.

思路：
不用timer。而是采用不断检测时间的方式。
另外，采用非阻塞的方式来读取键盘：`kbhit`函数
```c++
#include <Windows.h>
#include <conio.h>
#include <stdio.h>

int main() {
	UINT64 start_time = GetTickCount64();

	const UINT64 TIME_LIMIT = 5 * 1000;// 5 seconds

	while (1) {

		if (_kbhit()) {
			char ch = _getch();
			printf("input: [ %c ]\n", ch);
		}

		UINT64 now = GetTickCount64();
		if (now - start_time > TIME_LIMIT) {// 5 seconds
			break;
		}

		Sleep(10);// sleep 10 ms to lower cpu usage
	}

	printf("Program end\n");
	return 0;
}
```
