### ISSUE TITLE
关于项目的难度，需要较复杂的算法来展现吗？

### ISSUE THREAD

**Issue by pinepalm** [buaa21/summer2020#148]
关于项目的难度，需要较复杂的算法来展现吗？
现在感觉自己的项目里并不需要用到特别复杂的算法。。

**Comment by crclz** [comment]
增加复杂度的途径有几种，使用复杂的算法只是其中一种。
还可以为游戏添加新玩法、添加新功能、添加联机功能、添加AI……这些途径都可以增加项目的功能复杂度。

**Comment by crclz** [comment]
增加复杂度的途径有几种，使用复杂的算法只是其中一种。
还可以为游戏添加新玩法、添加新功能、添加联机功能、添加AI……这些途径都可以增加项目的功能复杂度。

**Comment by Roycent** [comment]
当然不需要，是否需要复杂的算法仅取决于你项目的功能。比如涉及到电脑AI对战的往往需要较为复杂的算法，其他软件往往不需要。
