### ISSUE TITLE
【关于文件编码】

### ISSUE THREAD

**Issue by longzhenren** [buaa21/summer2020#149]
以下代码实现FTP+ADB双线程上传文件到手机的功能
手机端FTP部分工作正常，单独使用FTP上传没有问题
py文件均使用utf-8编码 FTP服务器也使用FTP编码
但是系统powershell使用gbk编码 怎样同时兼顾两种功能？
（ADB是通过popen管道加.read方法调用系统命令行进行调用的，所以能否从popen的编码角度解决这个问题？或者有什么其他方法吗？）
`
'''
Target: Python AndroidToolBox Basic Customized System Methods Module
Author: LZR@BUAA
Date:   08/26/2020
'''
import io
import os
import re
import sys
import tarfile
from tkinter import Tk, filedialog

from ADBMethods import *
from main import mainmenu

def cmd(command):
    r = os.popen(command).read()
    return r

def unziptar(filename, dirs):
    t = tarfile.open(filename)
    t.extractall(path=dirs)
    t.close()

def InputJudge(num):
    if num == 2:
        while True:
            command = input()
            if command not in ['Y', 'y', 'N', 'n']:
                # if(input != "Y" and input != "N"and input != "y"and input != "n"):
                print("输入有误，请检查输入！")
            else:
                if command in ['y', 'Y']:
                    return True
                else:
                    return False
    else:
        while True:
            command = input()
            if command.isdigit():
                intput = int(command)
                if intput not in range(1, num+1):
                    print("输入有误，请检查输入！")
                else:
                    return intput
            else:
                print("输入有误，请检查输入！")

def NewProgram(pyFileName):
    os.system('cls')
    # print("Press Enter to Continue……")
    print(cmd("python "+pyFileName))

def dragtoWindowGetName():
    filedir = input("请将文件拖动到窗口，并点击窗口后按下Enter")
    return filedir

def exitProgram(num):
    if num == 0:
        print("操作已成功完成，程序退出中……")
    elif num == 1:
        print("用户终止操作，程序退出中……")
    elif num == 3:
        print("出现异常，程序退出中……")
`
`
'''
Target: Python AndroidToolBox ADB Plugin Methods Module
Author: LZR@BUAA
Date:   08/26/2020
'''
import os
import io
import sys
import re
from SysMethods import *

IP = ""
MobileInfo = {}

'''
Check Connections:
'''

def getFastbootConnection():
    cmd("fastboot devices")

def USBConnected():
    echo = cmd("adb devices").split("\n")
    return echo[1] != ''

def BLConnected():
    echo = cmd("fastboot devices").find("fastboot")
    return echo != -1

def WLANConnected():
    if powerStatus():
        IP = getIPaddress()
        r = cmd("adb devices")
        if r.find(IP) == -1:
            return False
        else:
            return True

'''
Reboot:
'''

def rebootUI():
    if BLConnected():
        cmd("fastboot reboot")
    if(USBConnected):
        cmd("adb reboot")

def rebootBL():
    cmd("adb reboot fastboot")

def rebootRec():
    cmd("adb reboot bootloader")

def fastbootReboot():
    cmd("fastboot reboot")

'''
Get Info:
'''

def getInfo():
    model = cmd("adb shell getprop ro.product.model").replace(
        '\n', '').replace('\r', '')
    manufacturer = cmd("adb shell getprop ro.product.brand").replace(
        '\n', '').replace('\r', '')
    lockstatus = cmd("adb shell getprop ro.secureboot.devicelock").replace(
        '\n', '').replace('\r', '')
    APIver = cmd("adb shell getprop ro.build.version.sdk").replace(
        '\n', '').replace('\r', '')
    wlandevice = cmd("adb shell getprop wifi.interface").replace(
        '\n', '').replace('\r', '')
    Serial = cmd("adb shell getprop ro.boot.serialno").replace(
        '\n', '').replace('\r', '')
    version = cmd("adb shell getprop ro.build.version.release").replace(
        '\n', '').replace('\r', '')

    MobileInfo.update({'model': model})
    MobileInfo.update({'API': APIver})
    MobileInfo.update({'brand': manufacturer})
    MobileInfo.update({'Wlan': wlandevice})
    MobileInfo.update({'serial': Serial})
    MobileInfo.update({'lock': lockstatus})
    MobileInfo.update({'android': version})

    return MobileInfo

def lockStatus():
    rebootBL()
    while True:
        if BLConnected():
            break
    r = cmd("fastboot oem device-info | findstr unlocked")
    if r.split(":")[-1].replace(" ", "") == "true":
        return True
    else:
        return False

def getBattery():
    r = cmd("adb shell dumpsys battery | findstr \"level\"").split(": ")[-1].replace(
        '\n', '').replace('\r', '')
    MobileInfo.update({'battery': r})
    return r

def getIPaddress():
    netstatus = cmd("adb shell ip addr | findstr \"wlan0\"")
    # print(netstatus)
    IP = re.findall(r"\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b", netstatus)
    return IP[0]

def powerStatus():
    PowerStat = cmd("adb shell getprop sys.boot_completed")
    if PowerStat == "\n":
        return False
    else:
        return True

'''
File Operations:
'''

def pushFile(sourcedir, rmpath):
    print(cmd("adb push " + sourcedir + " " + rmpath))

def pullFile(rmpath, destdir):
    print(cmd("adb pull " + rmpath + " " + destdir))

def dragtoPush(rmpath):
    dir = dragtoWindowGetName()
    pushFile(dir, rmpath)

def touchPoint(x, y):
    cmd("adb shell input tap "+x+" "+y)

def slidePoint(x1, y1, x2, y2):
    cmd("adb shell input swipe "+x1+" "+y1+" "+x2+" "+y2)

# if __name__ == "__main__":
#     getBattery()
`
`'''
Target: Python AndroidToolBox FileTransfer Module
Author: LZR@BUAA
Date:   08/30/2020
'''
import os
import sys
import threading
import time
from ftplib import FTP
from tkinter import Tk, filedialog, messagebox
# import _thread

from ADBMethods import *

Update = Tk()
Update.withdraw()
Update.title("选择要上传到远程的文件")
Down = Tk()
Down.withdraw()
Down.title("选择要下载到本地的文件")
FTPlist = []
ADBlist = []
Selectlist = []

IP = ""
path = os.getcwd()
fport = 1921
fuser = "LZR"
fpass = "BUAA21"
ftp = FTP()
rmpath = "/AndroidToolBox/"
localpath = path + "\\TransferredFiles\\"

class mThread (threading.Thread):
    def __init__(self, threadID, name, op):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
        self.op = op

    def run(self):
        print("开始线程：" + self.name)
        UPlist(self.op)

def openFileWindow():
    cur = filedialog.askopenfilenames()

def downloadfile(ftp, remotepath, localpath):
    bufsize = 1024
    fp = open(localpath, 'wb')
    ftp.retrbinary('RETR ' + remotepath, fp.write, bufsize)
    ftp.set_debuglevel(0)
    fp.close()

def uploadfile(ftp, remotepath, localpath):
    bufsize = 1024
    fp = open(localpath, 'rb')
    ftp.storbinary('STOR ' + remotepath, fp, bufsize)
    ftp.set_debuglevel(0)
    fp.close()

def divide(list):
    '''
    Test Passed
    '''
    ADBlist.clear()
    FTPlist.clear()
    lenl = len(list)
    if lenl == 0:
        print("列表空！")
        exitProgram(2)
    for i in range(lenl // 2):
        FTPlist.append(list[i])
    for i in range((lenl // 2) + 1, lenl):
        ADBlist.append(list[i])

def UPlist(op):
    if op == 1:
        global ftp
        for i in FTPlist:
            uploadfile(ftp, i.split("/")[-1], i)
    else:
        os.system("chcp 65001")
        for i in ADBlist:
            pushFile(i, rmpath+i.split("/")[-1])
        os.system("chcp 936")
        
            

def Upload():
    global ftp
    print("请选择：\n[1]打开文件对话框选择文件(适用于少量文件上传)\n[2]打开文件夹添加文件(适用于大量文件上传)\n[3]退出程序")
    op = InputJudge(3)
    if op == 1:
        cur = filedialog.askopenfilenames()
        # print(cur)
        divide(cur)
        # try:
        Thread1 = mThread(1,"FTPUP",1)
        Thread2 = mThread(2,"ADBUP",0)
        Thread1.start()
        Thread2.start()
        # except:
        #     print("Error: 无法启动线程")
        #     exitProgram(2)
        # print("/AndroidToolBox/"+i)
        # uploadfile(ftp, i.split("/")[-1], i)
    elif op == 2:
        os.startfile(localpath)
        input("复制完成后请按Enter继续")
        print("正在启动传输……")
        list_dir = os.listdir(localpath)
        for i in list_dir:
            print("正在传输文件：" + i)
            uploadfile(ftp, i, localpath+i)
        print("传输完成！")
        exitProgram(0)
    elif op == 3:
        exitProgram(1)

# def Download():
#     global ftp
#     cur = filedialog.askopenfilenames()
#     for i in cur:
#         uploadfile(ftp, "/AndroidToolBox/", i)

def StartFTP():
    print("启动FTP服务中……")
    ftp.set_debuglevel(2)
    ftp.connect(IP, fport)
    ftp.login(fuser, fpass)
    ftp.set_pasv(False)
    ftp.encoding = "utf-8"
    print(ftp.getwelcome())
    if "AndroidToolBox" not in ftp.nlst():
        ftp.mkd("/AndroidToolBox/")
    ftppath = "AndroidToolBox"
    ftp.cwd(ftppath)

if __name__ == "__main__":
    print("########################################")
    print("")
    print("                文件传输")
    print("              By:LZR@BUAA")
    print("")
    print("########################################")
    # cmd("adb disconnect")

    print("程序采用FTP共享+ADB方式突破USB速率限制进行文件传输\n请打开调试和安全设置，USB连接稳定，WLAN在同一局域网下")
    input("文件名称请不要出现特殊字符 按Enter继续")
    while True:
        if USBConnected():
            if powerStatus():
                IP = getIPaddress()
                getInfo()
                print("手机连接成功！当前设备： " +
                      MobileInfo['brand'] + " " + MobileInfo['model'])
                break
            else:
                print("手机开机状态异常，是否重新开机？(Y/N)")
                if InputJudge(2):
                    cmd("adb reboot")
        time.sleep(2)
# ?????
    if cmd("adb shell pm list package").find("com.my.ftpdemo") == -1:
        print("正在安装FTP客户端 请稍候……")
        r = cmd("adb install FtpClient.apk")
        if r.find("Success"):
            print("安装成功！")
    print("正在启动FTP客户端……")
    os.system("adb shell am start com.my.ftpdemo/.MainActivity")
    print("是否打开FTP界面？(Y/N)")
    if InputJudge(2):
        messagebox.showinfo("登录信息", "服务器：" + IP + "\n端口号：" +
                            str(fport)+"\n账号："+fuser+"\n密码："+fpass)
        print("登录信息\n服务器：" + IP + "\n端口号：" +
              str(fport)+"\n账号："+fuser+"\n密码："+fpass)
        os.startfile("ftp://"+IP+":"+str(fport))
    StartFTP()
    print("功能列表：\n[1]批量上传文件\n[2]批量下载文件\n[3]退出\n")
    op = InputJudge(3)
    if op == 1:
        Upload()
    elif op == 2:
        Download()
    elif op == 3:
        exitProgram(1)
`

**Comment by crclz** [comment]
执行命令并获取输出：
实例：执行`java`这个命令
```python
import subprocess

data = subprocess.check_output(['java'])

print(data.decode('gbk'))

```

**Comment by longzhenren** [comment]
> 执行命令并获取输出：
> 实例：执行`java`这个命令
> 
> ```python
> import subprocess
> 
> data = subprocess.check_output(['java'])
> 
> print(data.decode('gbk'))
> ```

改了之后整个程序都跑不起来了……
还是取消这个功能好了……
