### ISSUE TITLE
如何预估要写程序的代码量？

### ISSUE THREAD

**Issue by Rander-sun** [buaa21/summer2020#15]
在没有什么写软件经验的情况下，该怎么预估代码量？

**Comment by havesomecolo** [comment]
方法很多。比如网上找找同类的工程项目，下载下来看看他们的代码量
或者动手写一些模块的伪代码，看看代码行数
代码量主要指手工写的代码，不包括IDE自动生成的代码

**Comment by crclz** [comment]
关于代码量： #8

**Comment by songyou21** [comment]
自己感觉达到了训练效果，未辜负这金秋时节的十天，即可！
