### ISSUE TITLE
将一个文件插入已经编写好的Dev c++程序中

### ISSUE THREAD

**Issue by wysnjjq** [buaa21/summer2020#151]
就是把菜品的价格表这个文件导进去，让程序能读这个文件

**Comment by Roycent** [comment]
如果是要读取并处理excel中的数据的话，有很多第三方库可以使用，比如xlnt，比如libxl。微软官方也提供了一套接口。

**Comment by crclz** [comment]
建议了解一下读c语言的文件读写方法
