### ISSUE TITLE
请问这段代码中为什么使用invoke，而非直接用DoQuit调用，这样有什么好处

### ISSUE THREAD

**Issue by lkswrr** [buaa21/summer2020#152]
private void OnCheckDevice()
    {
 `if(Session.Status` == SessionStatus.ErrorSessionConfigurationNotSupported)
        {
            ShowAndroidToastMessage("ARCore在本机上不受支持或配置错误！");
            Invoke("DoQuit", 0.5f);
        }
        else if (Session.Status == SessionStatus.ErrorPermissionNotGranted)
        {
            ShowAndroidToastMessage("AR应用的运行需要使用摄像头，现无法获取到摄像头授权信息，请允许使用摄像头！");
            Invoke("DoQuit", 0.5f);
        }
    }
    private void DoQuit()
    {
          Application.Quit();
    }

**Comment by Lighten-w** [comment]
初步判断，由于DoQuit是个私有函数，所以这里使用了反射调用
