### ISSUE TITLE
半成品建议

### ISSUE THREAD

**Issue by lhzforever** [buaa21/summer2020#154]
[](url)https://www.bilibili.com/video/BV1zD4y1m7Nh/
想知道在这些功能以及ui上继续完善是否能达到基本要求

**Comment by crclz** [comment]
wait，建议你修改一下视频，介绍一下“弹幕”是什么意思，不然老师可能不知道，导致无法给出正确的建议

**Comment by crclz** [comment]
重新录制视频后再新开一个问题吧
