### ISSUE TITLE
想问一下关于代码规范的问题

### ISSUE THREAD

**Issue by 19373759** [buaa21/summer2020#155]
就是这个代码规范具体指的是什么？或者说有哪些方面是应该考察的?

**Comment by laneseal** [comment]
程序设计课上我们应该都有讲过基本规范，目前也不太要求特别高级的代码水平和高规格规范，至少基本命名的规范，可读性（适当的注释，空行，空格等）规范，比较好维护不至于碰到问题推翻了重新coding。

**Comment by 19373759** [comment]
> 程序设计课上我们应该都有讲过基本规范，目前也不太要求特别高级的代码水平和高规格规范，至少基本命名的规范，可读性（适当的注释，空行，空格等）规范，比较好维护不至于碰到问题推翻了重新coding。

好的谢谢
