### ISSUE TITLE
关于模块调用

### ISSUE THREAD

**Issue by longzhenren** [buaa21/summer2020#157]
现在情况是这样：
Main.py是主入口，导入了所有的模块（自己的模块用的是from xxx.py import *，系统库直接import xxx）
每个可执行的模块都有一个主方法 如：A.py :  def Amain(): ;B.py : def Bmain(); ... 每一个模块单独运行这个py文件没有问题（加了if __name__ == "__main__": Amain()这种形式） 
不可执行的自己写的库没有主方法，只有全局变量和函数 如：Methods.py ： def function():
且每个可执行模块都在开头 from Method import *
但是在Main.py中调用Amain方法时候 会报错缺少function操作
困扰了我很久的问题 希望能够得到解决
Traceback (most recent call last):
  File "d:\Git\AndroidToolBox-branch\main.py", line 95, in <module>
    mainmenu()
  File "d:\Git\AndroidToolBox-branch\main.py", line 34, in mainmenu
    Screenmain()
  File "d:\Git\AndroidToolBox-branch\Screen.py", line 108, in Screenmain
    cmd("adb disconnect")
NameError: name 'cmd' is not defined

**Comment by crclz** [comment]
`cmd`这个函数在哪个文件的第几行定义的？

**Comment by longzhenren** [comment]
> `cmd`这个函数在哪个文件的第几行定义的？

SysMethods.py 19行

**Comment by crclz** [comment]
那 `Screen.py`在里面有import SysMethods吗

**Comment by longzhenren** [comment]
> 那 `Screen.py`在里面有import SysMethods吗

有的

**Comment by crclz** [comment]
那把源代码打包发我邮箱，我仔细看看 crucialize@foxmail.com

**Comment by crclz** [comment]
只发python文件就可以了 刚刚发的太大了 下载不下来

**Comment by crclz** [comment]
你的代码存在循环引用的问题。
SysMethods.py `from ADBMethods import *`
ADBMethods.py `from SysMethods import *`

这样写是危险的。（看看其他地方是否存在这种问题）
建议：
1. 破除循环引用。可以把2个文件合成为一个文件。也可以将低层级的（常常是被调用的）拆分到一个文件，再把高层级的（常常是调用者）放到另一个文件。
2. 尽量不要`from xxx import *`。直接`import xxx`，然后调用的时候`xxx.func`。

**Comment by longzhenren** [comment]
> 你的代码存在循环引用的问题。
> SysMethods.py `from ADBMethods import *`
> ADBMethods.py `from SysMethods import *`
> 
> 这样写是危险的。（看看其他地方是否存在这种问题）
> 建议：
> 
> 1. 破除循环引用。可以把2个文件合成为一个文件。也可以将低层级的（常常是被调用的）拆分到一个文件，再把高层级的（常常是调用者）放到另一个文件。
> 2. 尽量不要`from xxx import *`。直接`import xxx`，然后调用的时候`xxx.func`。

好的 我试一试
那么 全局变量部分
如；list_dir = os.listdir(path+"\\images\\")
我在import这个模块的时候 赋值会自动执行吗

**Comment by crclz** [comment]
你可以在搜索引擎查一下，或者做一个实验试一下
