### ISSUE TITLE
关于Python获取文件绝对路径

### ISSUE THREAD

**Issue by longzhenren** [buaa21/summer2020#16]
如题，使用Powershell运行.py程序 在程序中需要这样一个功能：
拖拽一个文件到当前运行的窗口【不是图标，是powershell或cmd窗口】，使得程序能够正确获取该文件的绝对路径（用于后续的命令行操作）
环境：windows10 python3.8
请问应该如何实现？

**Comment by crclz** [comment]
以我现有的知识来看，拖拽文件到命令行并获取信息这种功能无法被实现（但是还是请充分查阅资料）。如果想要实现拖拽文件、获取文件信息相关的功能，可以考虑桌面app。

**Comment by longzhenren** [comment]
> 以我现有的知识来看，拖拽文件到命令行并获取信息这种功能无法被实现（但是还是请充分查阅资料）。如果想要实现拖拽文件、获取文件信息相关的功能，可以考虑桌面app。

使用其他语言呢 可以解决吗……（因为在别人的程序里看到了拖拽传送文件到外部设备这样的功能，也是通过命令行窗口实现的）

**Comment by Matrix53** [comment]
可以直接拖拽进入命令行界面，会出现路径字符串，不知道是不是你想要的

**Comment by cynic-1** [comment]
感觉这问题问的有点奇怪，你拖拽文件到cmd本来就会出现绝对路径。你的意思是想要通过代码来实现拖拽的功能？

**Comment by longzhenren** [comment]
> 感觉这问题问的有点奇怪，你拖拽文件到cmd本来就会出现绝对路径。你的意思是想要通过代码来实现拖拽的功能？

对的 我是想在程序里获取这段绝对路径

**Comment by longzhenren** [comment]
> 可以直接拖拽进入命令行界面，会出现路径字符串，不知道是不是你想要的

对的 我是想在程序里获取这段绝对路径……用来调用

**Comment by Matrix53** [comment]
> > 可以直接拖拽进入命令行界面，会出现路径字符串，不知道是不是你想要的
> 
> 对的 我是想在程序里获取这段绝对路径……用来调用

可以当成字符串输入，不过会多按一个回车
