### ISSUE TITLE
C语言用putimage放置图片，图片不显示

### ISSUE THREAD

**Issue by c-hn** [buaa21/summer2020#160]
我用loadimage加载图片，putimage贴图，没有编译错误但运行出来是黑的，相关的代码是这样的，是哪里出了问题吗
![屏幕截图(29)](https://user-images.githubusercontent.com/70204364/91659871-236e0c80-eb05-11ea-8db8-90035654a7f2.png)
![屏幕截图(30)](https://user-images.githubusercontent.com/70204364/91659883-31239200-eb05-11ea-83ee-8642b85494e2.png)

**Comment by Roycent** [comment]
loadimage部分的代码检查过了吗？

**Comment by c-hn** [comment]
loadimage部分是这样的，感觉也没啥问题啊...
![屏幕截图(32)](https://user-images.githubusercontent.com/70204364/91675821-5699b580-eb70-11ea-871a-71417bcd5a5a.png)

**Comment by PineZhuo** [comment]
图片用.jpg试试

**Comment by PineZhuo** [comment]
来自百度：
jdp文件：jdp文件是JDPaint（既精雕软件）的文件格式，文件大小在几百kb到几百mb不等，包含了图形文件（矢量）和所用的刀具等，用精雕即可打开。
是不是写错文件扩展名啦？.jdp看起来不像是图片呀

**Comment by c-hn** [comment]
确实是我打错了...谢谢
