### ISSUE TITLE
pycharm出现了没见过的报错，看不懂具体是哪里出了问题

### ISSUE THREAD

**Issue by TheSaint-LazareStation** [buaa21/summer2020#161]
![批注 2020-08-30 212307](https://user-images.githubusercontent.com/68428430/91660145-0df9e200-eb07-11ea-91c6-3d3a31fa9ceb.jpg)

error: No comment text / valid description?

网上也搜不到..

**Comment by crclz** [comment]
貌似是那个播放声音的组件内部的bug。会影响游戏正常运行吗？

**Comment by TheSaint-LazareStation** [comment]
嗯会的qwq 程序读到track = pygame.mixer.music.load()的时候就直接停止继续运行了

**Comment by PineZhuo** [comment]
track = pygame.mixer.music.load()和它附近的代码贴一下吧
