### ISSUE TITLE
半成品再评审

### ISSUE THREAD

**Issue by huahuaxiaomuzhu** [buaa21/summer2020#162]
还是四子棋（
第一版：https://www.bilibili.com/video/BV1Df4y1Q7YC
第二版：https://www.bilibili.com/video/BV1AC4y1b7KM
最新版：https://www.bilibili.com/video/BV1jZ4y1T7sV
仔细想了想，还是没有加入倒计时功能，毕竟是需要思考的棋牌类游戏。
想知道目前的复杂度和功能是否足够，以及UI是否足够美观，请多多批评指正。

**Comment by laneseal** [comment]
目前看已经能完整跑通一个python程序，很棒！但界面UI及其人性化操作还有较大改进空间，可以参考一些产品的设计。功能上除了AI之外可以考虑加入一些关卡，增加用户粘性，趣味性。
一个程序的好坏主要考虑用户的体验，能让用户满意是最有挑战的，让用户亲自体验效果更好，更容易发现深层次需求。

**Comment by havesomecolo** [comment]
过4号答辩是可以了，但是还有四天，可以再好好改进下申个优啥的。比如界面美化，做些球下落弹跳的动画，以及消除的特效啥的
