### ISSUE TITLE
用QTcpServer、QTcpSocket实现的网络对战是什么情况？

### ISSUE THREAD

**Issue by Eunice-grow** [buaa21/summer2020#164]
用qt做的五子棋程序，试图学习实现联网对战，但是不太明白怎么弄。
参考别人做的程序的时候，也搞不懂他们用了QTcpServer、QTcpSocket究竟实现了什么效果。
里面的客户端和服务器让人好迷

**Comment by PineZhuo** [comment]
首先应该要先明白计算机网络中的TCP连接的原理。可以通过这篇教程先把客户端和服务器的在TCP中的关系搞明白
https://www.cnblogs.com/beiluowuzheng/p/9655100.html
