### ISSUE TITLE
【Tip】前排兜售一份markdown语法

### ISSUE THREAD

**Issue by Lighten-w** [buaa21/summer2020#165]
[点击这里](https://www.runoob.com/markdown/md-tutorial.html)，简单了解即可漂亮的在github评论区使用等宽代码，标题，引用等等功能

**Comment by Roycent** [comment]
上面那一排按钮以及Preview按钮已经给了接近可视化编辑的功能了..想排版的同学就算不会markdown也有办法排，不想排版的话....
