### ISSUE TITLE
python Tkinter Label的位置

### ISSUE THREAD

**Issue by Neal2020GitHub** [buaa21/summer2020#168]
![微信截图_20200831094307](https://user-images.githubusercontent.com/70187327/91675364-a4adb980-eb6e-11ea-9095-0b3a30c0caf0.png)
![微信图片_20200831094446](https://user-images.githubusercontent.com/70187327/91675374-aecfb800-eb6e-11ea-8c6b-aacc72b29350.jpg)
不知道怎么将Label放到红圈位置

**Comment by SeventhGX** [comment]
看一下这里面提到的部分，看行不行？ https://www.zhihu.com/question/375056961

**Comment by Neal2020GitHub** [comment]
> 看一下这里面提到的部分，看行不行？ https://www.zhihu.com/question/375056961

知道了，谢谢
