### ISSUE TITLE
半成品

### ISSUE THREAD

**Issue by 19231136** [buaa21/summer2020#169]
https://www.bilibili.com/video/BV1eT4y1w7w3/
dev-c++ C语言

**Comment by PineZhuo** [comment]
作为一个黑窗口游戏来说已经可以了，操作不够便利以及界面不够好看是黑窗口的通病。还有3-4天的时间，可以努努力，试试看能不能做出GUI。

**Comment by havesomecolo** [comment]
时间应该够的，努努力做个GUI版本吧

**Comment by 19231136** [comment]
谢谢助教和老师，我试一试。
