### ISSUE TITLE
半成品建议

### ISSUE THREAD

**Issue by lhzforever** [buaa21/summer2020#171]
[](url)https://www.bilibili.com/video/BV1Uh41197mj/
希望知道在已有功能上以及ui上继续优化，不写新的功能能否达到基本要求

**Comment by PineZhuo** [comment]
（助教看法）总体挺好的，如果可视化能够做得再好一些就更好了（指分析结果的展示）。个人认为达到基本要求了，可以等一波老师的建议。

**Comment by havesomecolo** [comment]
弹幕是有接口读取吗，还是通过图像识别从屏幕上读取

**Comment by lhzforever** [comment]
有接口读取

**Comment by havesomecolo** [comment]
噢好。那就从数据分析入手吧，多丰富一下分析的主题，多做些数据可视化效果，给出有价值的分析结果
