### ISSUE TITLE
pygame在加载图片（png格式）后，运行时不断警告“libpng warning: iCCP: known incorrect sRGB profile”，这有影响吗？或者如何解决

### ISSUE THREAD

**Issue by buaadzr** [buaa21/summer2020#173]
pygame在加载图片（.png）后，运行时不断警告“libpng warning: iCCP: known incorrect sRGB profile”，这有影响吗？或者如何解决

**Comment by songoku1994** [comment]
这是libpng加强了对png格式检测导致，不影响程序运行，可参考https://blog.csdn.net/u010212648/article/details/82191419
