### ISSUE TITLE
JAVA GUI问题

### ISSUE THREAD

**Issue by DragonnZhang** [buaa21/summer2020#174]
目前在使用java gui，希望写一个按钮，点一下按钮，某图片可以沿直线缓慢移动到某特定坐标，当图片移动到该地方后，沿原路返回。我想知道如何实现这个图片的移动。

**Comment by Roycent** [comment]
一个思路是不断更新图片坐标并重绘，到达指定坐标后再执行相反的代码。具体实现的话要看你使用的是哪种GUI框架了

**Comment by DragonnZhang** [comment]
我用的是swing。我就是这么做的，“不断更新图片坐标并重绘”，每次更新坐标后，延时一会，再重复，再执行相反的代码，在我的程序上却只作了去到那个坐标的部分，没有做返回的部分。延时用的是Timer。我不知道问题在哪里。

**Comment by Roycent** [comment]
打断点或者打印一些辅助调试的信息，看看返回部分的代码执行了没有，如果没有再检查原因
