### ISSUE TITLE
Android Studio提供的虚拟机连接电脑本地数据库一直闪退

### ISSUE THREAD

**Issue by Cirtl** [buaa21/summer2020#175]
参考了这位博主的代码https://blog.csdn.net/yaoneng119/article/details/8859326
想重写学习一下，结果在运行时点击测试按钮一直闪退，是因为虚拟机不能连接网络吗

**Comment by Roycent** [comment]
打断点试试是在哪里出了错闪退的，比较好定位错误出现在哪里

**Comment by havesomecolo** [comment]
连的sqlserver？这个有点复杂，先写个桌面版的jdbc程序连接数据库看看能不能连上吧。
不如改成sqlite版的，直接访问本地数据库，没有那么多问题。

**Comment by Cirtl** [comment]
关于jdbc,我看网上的文章下载了jtds-1.2.7和sqlitejdbc4两个jar包，不知道能不能用
关于本地数据库，是指手机本地的数据库吗，我最终其实想实现不同设备间数据的共享，请问sqlite能在电脑本地建一个数据库然后供其他安卓设备访问吗 @havesomecolo

**Comment by Cirtl** [comment]
话说sqlite连接是要简单一些吗

**Comment by havesomecolo** [comment]
噢你是多手机共享，那还是sqlserver吧。sqlite一个手机用用是简单的，但是不适合多手机共享数据

**Comment by havesomecolo** [comment]
你先写个桌面版的java程序，远程访问你的sqlserver，看能不能连上。调通了以后，再把连接串什么的移植到手机上。这样一步一步可以更好的定位错误
