### ISSUE TITLE
Java swing做GUI 中文显示乱码

### ISSUE THREAD

**Issue by cynic-1** [buaa21/summer2020#176]

**Comment by cynic-1** [comment]
已试过cmd参数改encoding的方法，没有解决

**Comment by buaa21** [comment]
请详细描述

**Comment by cynic-1** [comment]
![image](https://user-images.githubusercontent.com/68074066/91707288-28d56080-ebb2-11ea-86c9-a285ff35f1ce.png)
网上的解决方案，比如改VM Argument 为-Dfile.encoding=gbk 或者UTF-8都没有用
