### ISSUE TITLE
如何在已获取窗口句柄的情况下使窗口居中？

### ISSUE THREAD

**Issue by Rander-sun** [buaa21/summer2020#177]
如题，我查到了可以使用movewindow函数，但是对于如何设置居中没想明白（因为不同的屏幕大小不一样），或者还有其他函数可以实现这一功能吗？
软件平台是vs+easyx

**Comment by SeventhGX** [comment]
那想办法获取屏幕的分辨率，在根据窗口大小进行计算要把窗口放到哪就好啊
这里是c++获取屏幕分辨率的一种方法  https://blog.csdn.net/yp18792574062/article/details/88351342
