### ISSUE TITLE
半成品

### ISSUE THREAD

**Issue by cc1121** [buaa21/summer2020#178]
目前人人对战部分已经写完，人机对战简单模式也写完了，困难模式暂时没看懂需要利用到极大极小搜索以及α-β剪枝的算法，想知道如果加上困难模式以现在的这些功能能否通过，或者如果不能有没有什么改进的建议，麻烦老师助教看一看啦。
链接：https://www.bilibili.com/video/BV1854y1272U

**Comment by PineZhuo** [comment]
目前的功能比较基础，如果困难模式写得精彩、写得好的话，个人觉得是可以通过评审的。想办法让机器更智能、更有趣。（以及人人对战是不是就是自己和自己玩啊hhhhhh如果有精力的话，还可以考虑写一下远程的人人对战，实现真·人人对战）

**Comment by crclz** [comment]
个人观点：现在看来，感觉做棋类游戏比较吃亏... 飞机大战可以很容易就想到如何添加一些新的东西，例如新的关卡、技能。但是棋类游戏，规则是已有的，要创新就只能写AI来创新。你用C/C++写的，这上面也吃亏。

就像楼上说的，你展示的功能比较基础。你可以尝试增加远程对战，这个需要你学习socket、多线程。

另外，我刚刚不是说棋类游戏吃亏（因为规则是定好的）。你可以尝试魔改一下你的游戏，跳出“五子棋”这个框架的局限，像“飞机大战”一样，给玩家增加很多技能，例如一次放置某种pattern的多个棋子，或者增加一个技能让玩家能够让某一块（NxN）区域的棋子重新排列（或者旋转、转置……），或者增加一种棋子，能够炸掉某个区域……尽可能丰富地发挥想象力

**Comment by songyou21** [comment]
过关应该问题不大。实践课能自己完成这样一个作品也是很不错的。
但这种特别经典的题目，得高分不容易，需要讲出自己如何超越过去的若干学长，这不容易。

**Comment by 19231136** [comment]
好的 谢谢老师
