### ISSUE TITLE
关于C语言播放音乐的问题

### ISSUE THREAD

**Issue by 19373759** [buaa21/summer2020#180]
想用C语言播放音乐。 但是按照如下代码运行时会出现：Untitled-1.c:(.text+0x29): undefined reference to `__imp_PlaySoundA'。
无法运行程序。这种大概是个什么情况
代码：
#include<stdio.h>
#include<time.h>
#include<stdlib.h> 
#include<windows.h>
#pragma comment(lib,"Winnmm.lib")
#include<mmsystem.h>

int main(int argc, char *argv[])

{
	PlaySound(TEXT("bgm.wav"), NULL, SND_FILENAME | SND_ASYNC | SND_LOOP);   //bgm是我电脑里的一个wav格式的音乐文件
	Sleep(50000);
	return 0;

}

**Comment by Roycent** [comment]
大概率是编译时的链接问题，由于引入了一个新的"winnmm"库，因此编译的时候编译器找不到这个库。可以试试在编译选项中加入"-lwinmm"

**Comment by 19373759** [comment]
> 大概率是编译时的链接问题，由于引入了一个新的"winnmm"库，因此编译的时候编译器找不到这个库。可以试试在编译选项中加入"-lwinmm"

改成用mcisendstring方式后解决了。谢谢！
