### ISSUE TITLE
半成品

### ISSUE THREAD

**Issue by Xieyufengdd** [buaa21/summer2020#181]
https://www.bilibili.com/video/BV1mV41127zC/

**Comment by PineZhuo** [comment]
GUI很好看，基础功能也已经完善了。可以尝试做不同难度的关卡，设置更多有趣的道具、或者不同类型的敌机等等。

**Comment by orixing** [comment]
未来可以考虑在关卡，敌人种类，敌人路线，敌人弹幕，道具等方面加入新内容

**Comment by iceryang** [comment]
这个可以加些功能。目前看着不完备

**Comment by songyou21** [comment]
及格问题不大，想得高分的话还需要讲出亮点、难点、创新点来。
