### ISSUE TITLE
AI的调试问题（Python 常数优化？？

### ISSUE THREAD

**Issue by Withinlover** [buaa21/summer2020#183]
背景

```text
写了个贪吃蛇，然后又写了个人工智障，现在让这个人工智障自己去跑

他跑了十几分钟了只跑满了场地的一半（

应该不是性能的问题，这个人工智障每走一步的时间复杂度都是O(1)级别的

后续可能还会优化他的路线寻找，但是这么调试一次实在是太花时间了（因为大多数问题都只能在跑满大多数空地后才能体现出来

比如说最开始写的暴力寻路 + 一点点优化后愣是走了20分钟才进入死循环（
```
CPU，GPU显然是没有跑满的，所以特来寻求优化/调试的方法。。。

一点猜测：

- 代码本身可能存在优化空间，目前的最快只能做到20 - 30ms进行一次移动。但是大部分时间都花在渲染上。
- 有没有可能通过外界手段给程序进行加速（类似用CE对游戏内存进行修改...？

<del>难怪大型游戏都不拿Python写....（</del>
<del>为啥蛇越长渲染越慢啊</del>

**Comment by crclz** [comment]
先验证你的猜测吧。你可以把核心的代码抽离出来（只保留核心的贪吃蛇+算法，去掉渲染）。看一看是渲染慢还是算法慢。

然后，如果是渲染慢，你可以每隔几步才进行一次渲染。

> 因为大多数问题都只能在跑满大多数空地后才能体现出来

1. 可以减小场地的长宽
2. 可以让游戏开始的时候就让蛇拥有很长的长度（用于调试）。

**Comment by Withinlover** [comment]
渲染和核心代码的时间是用pygame.time算出来的，应该是渲染太慢了（

场地的长宽的话最开始写的时候没有用常量，为了判断蛇的状态还不经意间用了一些魔术数，还没加注释（

发现的时候已经晚了（
现在应该是来不及重构了（（（

我试一下调整长度吧

话说最终做演示的时候，需要控制时间嘛？这个东西目前还挺难做到短时间跑完的（

**Comment by crclz** [comment]
最终演示是需要控制时间的，详情见群公告
