### ISSUE TITLE
关于使用py爬取动态页面数据的问题

### ISSUE THREAD

**Issue by Ritine** [buaa21/summer2020#184]
[https://bebd.bevol.com/#/home/productDetails?mid=263620a8602158d6450c965e762b0f2b](url)
比如这个网址，需要提取商品的成分表信息，不知道操作。
（这个网站需要注册登录，输入手机号填入验证码即可）

**Comment by PineZhuo** [comment]
网上教程很多，可以看看，比如：
https://blog.csdn.net/qq_30242609/article/details/53788228
https://blog.csdn.net/qq_30242609/article/details/53925298

**Comment by Ritine** [comment]
> 网上教程很多，可以看看，比如：
> https://blog.csdn.net/qq_30242609/article/details/53788228
> https://blog.csdn.net/qq_30242609/article/details/53925298

嗯好像比这个教程要复杂一点，教程里没有提到如何模拟用户登录...

**Comment by crclz** [comment]
模拟用户登录，我知道几种解决方案：
1. F12逆向分析请求（有难度）
2. 用浏览器人工进行登录，然后将浏览器的cookie给python。“将cookie给python”的部分，python好像有开源的library可以做到；如果熟悉浏览器F12的话，也可以用其他方式做到。
3. 使用selenium。相当于利用代码控制浏览器。
4. 其他方法请搜索

**Comment by Ritine** [comment]
> 模拟用户登录，我知道几种解决方案：
> 
> 1. F12逆向分析请求（有难度）
> 2. 用浏览器人工进行登录，然后将浏览器的cookie给python。“将cookie给python”的部分，python好像有开源的library可以做到；如果熟悉浏览器F12的话，也可以用其他方式做到。
> 3. 使用selenium。相当于利用代码控制浏览器。
> 4. 其他方法请搜索

![image](https://user-images.githubusercontent.com/70203179/91726273-8f6a7680-ebd2-11ea-9617-601fe9716aa1.png)
response headers里面并没有找到cookie？

**Comment by crclz** [comment]
你要看发往本站的请求。跨域的请求一般不会携带cookie。
如果对这方面不熟悉，建议使用 开源的library

**Comment by Ritine** [comment]
> 你要看发往本站的请求。跨域的请求一般不会携带cookie。
> 如果对这方面不熟悉，建议使用 开源的library

好的谢谢助教，确实不熟悉qwq，我先找找，换个好爬的网站好了，有空再研究这个。

**Comment by Lighten-w** [comment]
```python
import urllib

url = "https://saas2-api.bevol.com/auth/goods/detail/ingredient"


# 发送时加上Request headers，可以直接复制f12里的信息
headers = {
    'sessid': 'xxxxxxxxxxxxxxx',
    'token': 'xxxxxxxxxxxxxxxxxxxxxxx',
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
}

# 同样要加上data，直接复制request payload里的内容，同时字符串前面加b转成bytes
data = b'{"goodsMid":"263620a8602158d6450c965e762b0f2b","ingredientActive":"","current":1,"pageSize":10,"total":0}'

request = urllib.request.Request(url=url,headers=headers, data=data)

response = urllib.request.urlopen(request).read().decode("utf-8","ignore")


print(response)
```
