### ISSUE TITLE
python象棋棋子跟着鼠标移动问题

### ISSUE THREAD

**Issue by jingyou574066976** [buaa21/summer2020#186]
![微信图片_20200831203043](https://user-images.githubusercontent.com/70198335/91720120-229eae80-ebc9-11ea-8f51-8bd127651be9.png)
这个图是实现不了棋子跟着鼠标移动 只能移动棋子 但是棋子不跟着走
![微信图片_20200831203220](https://user-images.githubusercontent.com/70198335/91720145-30543400-ebc9-11ea-85da-a172323f7e0d.png)
这个图上面是跟上一张图片一样的 就是把移动鼠标换了位置 但是就会让棋子一直跟着鼠标移动但是无法落子
想问问这个问题应该怎么解决呢

**Comment by buaa21** [comment]
抱歉，助教们可能没有足够的上下文来解决问题。
