### ISSUE TITLE
如何将多个python文件打包成exe

### ISSUE THREAD

**Issue by xiazaiba7** [buaa21/summer2020#187]
需要将多个文件打包成exe,其中有一个是运行的主文件，还有一些包含一些模块和函数的附文件。并且我用到了pygame，是否也需要一起打包？

**Comment by SeventhGX** [comment]
https://www.cnblogs.com/jackzz/p/9431923.html

**Comment by xiazaiba7** [comment]
但是我的涉及到pygame库应该怎么操作呢

**Comment by SeventhGX** [comment]
> 但是我的涉及到pygame库应该怎么操作呢

自己试一下不就知道了，这又不是只有一次机会...
而且这个相关的内容很好找的  https://blog.csdn.net/frostime/article/details/90523062

**Comment by xiazaiba7** [comment]
好的，谢谢学长
