### ISSUE TITLE
pygame设置血量条时能运行但是有警告

### ISSUE THREAD

**Issue by Nevermind-sudo** [buaa21/summer2020#188]
#当生命大于20%显示绿色，否则显示红色
                    energy_remain = each.energy/enemy.BigEnemy.energy
                    if energy_remain > 0.2:
                        energy_color = GREEN
                    else:
                        energy_color = RED
                    pygame.draw.line(screen,energy_color,\
                                     (each.rect.left,each.rect.top - 5),\
                                     (each.rect.left + each.rect.width * energy_remain,\
                                      each.rect.top - 5),2)

Warning (from warnings module):
  File "C:\高工\Python\飞机大战\main.py", line 365
    pygame.draw.line(screen,energy_color,\
DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.

试过在if和else语句里分别画，把energy_color直接换成（0，255，0）和（255，0，0），还是同样有警告，不知道该从什么地方改了

**Comment by PineZhuo** [comment]
猜测：会不会是each.rect.width * energy_remain有浮点数导致它警告？试试显示类型转换成int

**Comment by Nevermind-sudo** [comment]
原来是这样，谢谢，现在已经解决了
