### ISSUE TITLE
提交问题

### ISSUE THREAD

**Issue by 1921zzk** [buaa21/summer2020#195]
python小游戏一定要打包成exe吗还是可以只交源文件就行。

**Comment by PineZhuo** [comment]
最好有exe

**Comment by 1921zzk** [comment]
如果实在转换不了呢

**Comment by Roycent** [comment]
最好有exe，方便助教和老师们查看效果。如果因为引用的组件过多，因为组件本身的问题无法使用pyinstaller等打包成exe，最好说明一下原因。
