### ISSUE TITLE
半成品

### ISSUE THREAD

**Issue by nameless-cat1** [buaa21/summer2020#198]
https://www.bilibili.com/video/BV1ZV411U7BK/

**Comment by nameless-cat1** [comment]
这算是前后端分离吗？

**Comment by crclz** [comment]
> 这算是前后端分离吗？

前后端分离一般指的是要用vue react angular等框架

**Comment by crclz** [comment]
进行图像处理、词云生成等代码，是自己写的吗？

**Comment by nameless-cat1** [comment]
词云调用wordcloud库可实现，部分代码参考过网上的算法，我认为效果一般并重新编写。有些写的代码效果不如直接调库所以直接调库了

**Comment by nameless-cat1** [comment]
使用bootstrap框架属于前后端分离吗

**Comment by iceryang** [comment]
图像和词云是分离的？好像两个不算一个小作品，并接直接调用库，代码会少很多。这个作业多少行代码？

**Comment by iceryang** [comment]
图像和词云是分离的？好像两个不算一个小作品，并接直接调用库，代码会少很多。这个作业多少行代码？

**Comment by nameless-cat1** [comment]
> 图像和词云是分离的？好像两个不算一个小作品，并接直接调用库，代码会少很多。这个作业多少行代码？

一个网站有7种图片处理功能，不止生成词云，有的功能实现依靠一定的算法，如果不算十多个HTML和django路由配置等，还是有三四百行pyhton

**Comment by crclz** [comment]
> 使用bootstrap框架属于前后端分离吗

不属于，但不采用前后端分离的架构问题也不大。

**Comment by songyou21** [comment]
视频展示时没有语音讲解。答辩时把亮点好好讲讲。
