### ISSUE TITLE
选题方向是不是填完那个在线表格就可以了？

### ISSUE THREAD

**Issue by Matrix53** [buaa21/summer2020#20]
如题，是不是只用完成图1内容？
![Z68Y9(~RVZH2RHL{LMD_X(S](https://user-images.githubusercontent.com/55696968/91251634-72771300-e78e-11ea-8dd4-1d1985254917.png)
![Q GH4JDC71_F7D35WQ}C6PP](https://user-images.githubusercontent.com/55696968/91251650-799e2100-e78e-11ea-882b-77d8ca525ad0.png)

**Comment by havesomecolo** [comment]
是的，填在线表格就行
