### ISSUE TITLE
C语言为何播放音乐失败，头文件书写应该也没有问题

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#201]
![image](https://user-images.githubusercontent.com/70250586/91792421-0aba3f80-ec48-11ea-9b1a-260c1fc2da9d.png)
![image](https://user-images.githubusercontent.com/70250586/91792459-1b6ab580-ec48-11ea-91cd-be304304bdb6.png)

**Comment by PineZhuo** [comment]
还要链接windows的动态链接库WINMM.LIB。在编译器的设置中，添加链接-lwinmm

**Comment by Roycent** [comment]
参考 #180
