### ISSUE TITLE
手机通过ip地址直接连接sqlserver数据库问题

### ISSUE THREAD

**Issue by Cirtl** [buaa21/summer2020#202]
我在Eclipes上面写了段代码成功连接了电脑本地的sqlserver数据库
![image](https://user-images.githubusercontent.com/70183047/91792855-16f2cc80-ec49-11ea-8ed5-92478c4294cc.png)
但是在Android Studio中，类似的代码却总是无法连接
![image](https://user-images.githubusercontent.com/70183047/91792932-57eae100-ec49-11ea-9d9d-834b94eba135.png)
请问这是AS上面的代码的问题还是什么？
PS：关于ip地址，本地ip地址同样试过，但是也不行

**Comment by Roycent** [comment]
1、连接字符串问题，sqlserver://127.0.0.1 ，你把那个斜线放到后面了
2、安卓虚拟机的地址问题。安卓虚拟机和本机不在一个网段。可以尝试一下“10.0.2.2”这个IP，如果无法解决的话就再去搜索其他解决方法看看。

**Comment by Cirtl** [comment]
更换之后还是不行，而且我用127.0.0.1这个ip在手机上试了试，结果也是闪退

**Comment by Roycent** [comment]
127.0.0.1是本机IP，在手机上试是肯定不行的。可以查看电脑端的IP，然后再用手机连电脑的那个IP（前提是二者在同一个局域网环境下，且防火墙没有拦截连接，因为数据库运行在电脑上）。

**Comment by Cirtl** [comment]
![image](https://user-images.githubusercontent.com/70183047/91811466-20d4f980-ec62-11ea-8d6e-a381d0efeb75.png)
虚拟机还是连不上，一直卡在getConnection这个语句处，心态有点炸...

**Comment by Cirtl** [comment]
![image](https://user-images.githubusercontent.com/70183047/91811686-7f9a7300-ec62-11ea-9b16-33c315155cab.png)
虚拟机还是连不上数据库，一直卡在getConnection语句这里，心态有点炸...

**Comment by Cirtl** [comment]
![image](https://user-images.githubusercontent.com/70183047/91811849-bbcdd380-ec62-11ea-962a-a061d0633a6e.png)

**Comment by Roycent** [comment]
打开CMD，输入`ipconfig`查看电脑的IP地址，比如我的：
```
C:\Users\Roycent>ipconfig

Windows IP 配置


以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::513a:1dc8:1882:6305%4
   IPv4 地址 . . . . . . . . . . . . : 192.168.3.4
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.3.1

无线局域网适配器 WLAN:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . 
```
可以看到我电脑的IP地址是192.168.3.4. 可以通过这个地址访问到电脑上的资源。
