### ISSUE TITLE
刚才提问的C语言为何无法播放音乐，加了-lwinmm没啥效果，用mciSendString也没啥用

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#203]
![image](https://user-images.githubusercontent.com/70250586/91795866-65a46480-ec51-11ea-907d-4d92e1112e58.png)

**Comment by PineZhuo** [comment]
emmm这不是没啥效果，这是报错链接加错了报错了，两个链接不能写在同一行，以及把音乐路径里的中文换成英文吧

**Comment by PineZhuo** [comment]
以及devc++应该还存在一些其他的问题，devc++ 编译用*.a库，对于*.lib库默认情况下会有问题。如果还报错的话，这个教程在教怎么用devc++编译链接.lib库：https://blog.csdn.net/ljq900/article/details/4335047

**Comment by Fat-Fat-Lee** [comment]
成功了成功了！！！！！谢谢助教！
