### ISSUE TITLE
半成品2048

### ISSUE THREAD

**Issue by jianhong1009** [buaa21/summer2020#204]
不好意思，没弄成视频
拥有的功能和界面都在pdf里有介绍
因自己基础不是很好，选了c语言来写代码
关于界面：会在剩下的时间内尽可能美化界面，弄出更好看的界面出来
[2048.pdf](https://github.com/buaa21/summer2020/files/5154095/2048.pdf)

**Comment by songyou21** [comment]
挺好。这个思路是对的，就按这个继续下去就可以了。
