### ISSUE TITLE
c#根据用户兴趣推送不同内容的问题

### ISSUE THREAD

**Issue by lxybh05** [buaa21/summer2020#207]
请问如何通过改变c# winform 中checkedlistbox中的勾选状态来改变页面的内容
例如通过客户选择checkedlistbox中兴趣爱好来为他们推送不同的内容，并且内容能够从上到下依次显示

**Comment by crclz** [comment]
![image](https://user-images.githubusercontent.com/54950573/91811875-c5573b80-ec62-11ea-9a81-73561f7b07b3.png)
可以用ItemChecked事件

**Comment by lxybh05** [comment]
请问如何将一块内容在某一选项选中的时候显示，未选中的时候屏蔽但是不留空白，能让选中的内容从上到下不留空位置的显示出来

**Comment by crclz** [comment]
> 请问如何将一块内容在某一选项选中的时候显示，未选中的时候屏蔽但是不留空白，能让选中的内容从上到下不留空位置的显示出来

写一个函数`updateDisplayList`，这个函数根据checklist的状态来计算出需要展示哪些项目，然后在每一次`ItemCheck`事件的时候，调用这个函数。

**Comment by lxybh05** [comment]
可不可以麻烦函数内部给一些提示啊，对于空白的处理我还是不太理解
（每次调用完都有空白部分，就是不该显示的只是内容不显示但是位置不变显示一片空白）

**Comment by crclz** [comment]
假设这是一个电影搜索程序，用户通过勾选不同的电影类别，来搜索电影。假设你要显示的是一个电影列表，用的控件是listview。

`updateDisplayList`函数里面，你首先获取用户勾选的项目（这里假如用户勾选了 悬疑、科幻 ）

那么，第二步就是，创建一个List，然后将悬疑、科幻类的电影加入到这个list中。

最后，将原先的listview中的数据清空，然后把刚刚的list中的数据加入listview。
