### ISSUE TITLE
一般网络游戏如何debug

### ISSUE THREAD

**Issue by dwr2001** [buaa21/summer2020#208]
现在有一个双人联机游戏，想测试游戏，就得需要两台电脑两边都开着，如何一台电脑解决问题？

**Comment by orixing** [comment]
能详细说一下你是用什么开发的游戏，如何进行联机通信的吗

**Comment by dwr2001** [comment]
emmpython pygame和socket，然后用thread实现游戏界面和通信并发执行，

**Comment by crclz** [comment]
你可以用一台电脑，两个不同的端口来运行游戏

**Comment by dwr2001** [comment]
请问还有其他方法吗？我现在就是这样子的，但总是反应慢些就很快结束了
