### ISSUE TITLE
python打包exe

### ISSUE THREAD

**Issue by zxt539** [buaa21/summer2020#209]
python文件打包为exe文件时遇到下图问题，怎么解决？

<img width="693" alt="problem" src="https://user-images.githubusercontent.com/52772254/91822980-2420b300-ec6b-11ea-93af-ef9aab331bb5.PNG">

**Comment by orixing** [comment]
看一下环境变量PATH，试一下把python和pyinstaller的安装目录都添加进系统环境变量PATH里
