### ISSUE TITLE
为什么我使用C语言的Rectangle画矩形框，一直报错，说是id returned 1 exit status。Rectangle就在第一个函数LRESULT中

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#21]
#include <windows.h>

/* This is where all the input to the window goes to */
LRESULT CALLBACK WndProc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) {
	PAINTSTRUCT pt;
	HDC hDC;
	switch(Message) {
		
		case WM_PAINT:
			hDC=BeginPaint(hwnd,&pt);//窗口可作用区域的标识 
			//画窗口的内容
			
                Rectangle(hDC,0,0,100,100);
			
			
			
			
			
			
			
			EndPaint(hwnd,&pt);
			break; 
		/* Upon destruction, tell the main thread to stop */
		
		case WM_DESTROY: {
			PostQuitMessage(0);
			break;
		}
		
		/* All other messages (a lot of them) are processed using default procedures */
		default:
			return DefWindowProc(hwnd, Message, wParam, lParam);
	}
	return 0;
}

/* The 'main' function of Win32 GUI programs: this is where execution starts */
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
	WNDCLASSEX wc; /* A properties struct of our window */
	HWND hwnd; /* A 'HANDLE', hence the H, or a pointer to our window */
	MSG msg; /* A temporary location for all messages */

	/* zero out the struct and set the stuff we want to modify */
	memset(&wc,0,sizeof(wc));
	wc.cbSize		 = sizeof(WNDCLASSEX);
	wc.lpfnWndProc	 = WndProc; /* This is where we will send messages to */
	wc.hInstance	 = hInstance;
	wc.hCursor		 = LoadCursor(NULL, IDC_ARROW);
	
	/* White, COLOR_WINDOW is just a #define for a system color, try Ctrl+Clicking it */
	wc.hbrBackground = (HBRUSH)(COLOR_WINDOW);//定义窗口背景颜色 
	wc.lpszClassName = "WindowClass";
	wc.hIcon		 = LoadIcon(NULL, IDI_APPLICATION); /* 底下任务栏中的图标*/
	wc.hIconSm		 = LoadIcon(NULL, IDI_APPLICATION); /* 打开页面条左上角的小图标 */

	if(!RegisterClassEx(&wc)) {
		MessageBox(NULL, "Window Registration Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
		return 0;
	}

	hwnd = CreateWindowEx(WS_EX_CLIENTEDGE,"WindowClass","俄罗斯方块",WS_VISIBLE|WS_OVERLAPPEDWINDOW,
		100, /* x */
		100, /* y */
		500, /* width */
		500, /* height */
		NULL,NULL,hInstance,NULL);

	if(hwnd == NULL) {
		MessageBox(NULL, "Window Creation Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
		return 0;
	}

	/*
		This is the heart of our program where all input is processed and 
		sent to WndProc. Note that GetMessage blocks code flow until it receives something, so
		this loop will not produce unreasonably high CPU usage
	*/
	while(GetMessage(&msg, NULL, 0, 0) > 0) { /* If no error is received... */
		TranslateMessage(&msg); /* Translate key codes to chars if present */
		DispatchMessage(&msg); /* Send it to WndProc */
	}
	return msg.wParam;
}

**Comment by Matrix53** [comment]
人生苦短，我用python

**Comment by Withinlover** [comment]
id returned 1 exit status是你上一个程序没有完全关闭
关了重新编译就好了

有的时候cmd的窗口关了但后台仍在运行
开任务管理器找一下就行

anyway，重启解决99%的问题

**Comment by Matrix53** [comment]
![Screenshot_2020-08-26-12-19-46-846_com android br](https://user-images.githubusercontent.com/55696968/91255146-b1a96200-e796-11ea-9c17-827aa0baefe9.jpg)
可以看看这个

**Comment by Fat-Fat-Lee** [comment]
关键是我已经把之前所有的·程序都关掉啦！！重启也不管事。是不是我的代码本身有问题啊。我只要把Rectangle删掉就不会有这样的问题，可以正常弹出页面框

**Comment by Fat-Fat-Lee** [comment]
#include <windows.h>

/* This is where all the input to the window goes to */
LRESULT CALLBACK WndProc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) {
	PAINTSTRUCT pt;
	HDC hDC;
	switch(Message) {
		
		case WM_PAINT:
			hDC=BeginPaint(hwnd,&pt);//窗口可作用区域的标识 
			//画窗口的内容
			
			
			
			
			
			
			
			EndPaint(hwnd,&pt);
			break; 
		/* Upon destruction, tell the main thread to stop */
		
		case WM_DESTROY: {
			PostQuitMessage(0);
			break;
		}
		
		/* All other messages (a lot of them) are processed using default procedures */
		default:
			return DefWindowProc(hwnd, Message, wParam, lParam);
	}
	return 0;
}

/* The 'main' function of Win32 GUI programs: this is where execution starts */
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
	WNDCLASSEX wc; /* A properties struct of our window */
	HWND hwnd; /* A 'HANDLE', hence the H, or a pointer to our window */
	MSG msg; /* A temporary location for all messages */

	/* zero out the struct and set the stuff we want to modify */
	memset(&wc,0,sizeof(wc));
	wc.cbSize		 = sizeof(WNDCLASSEX);
	wc.lpfnWndProc	 = WndProc; /* This is where we will send messages to */
	wc.hInstance	 = hInstance;
	wc.hCursor		 = LoadCursor(NULL, IDC_ARROW);
	
	/* White, COLOR_WINDOW is just a #define for a system color, try Ctrl+Clicking it */
	wc.hbrBackground = (HBRUSH)(COLOR_WINDOW);//定义窗口背景颜色 
	wc.lpszClassName = "WindowClass";
	wc.hIcon		 = LoadIcon(NULL, IDI_APPLICATION); /* 底下任务栏中的图标*/
	wc.hIconSm		 = LoadIcon(NULL, IDI_APPLICATION); /* 打开页面条左上角的小图标 */

	if(!RegisterClassEx(&wc)) {
		MessageBox(NULL, "Window Registration Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
		return 0;
	}

	hwnd = CreateWindowEx(WS_EX_CLIENTEDGE,"WindowClass","俄罗斯方块",WS_VISIBLE|WS_OVERLAPPEDWINDOW,
		100, /* x */
		100, /* y */
		500, /* width */
		500, /* height */
		NULL,NULL,hInstance,NULL);

	if(hwnd == NULL) {
		MessageBox(NULL, "Window Creation Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
		return 0;
	}

	/*
		This is the heart of our program where all input is processed and 
		sent to WndProc. Note that GetMessage blocks code flow until it receives something, so
		this loop will not produce unreasonably high CPU usage
	*/
	while(GetMessage(&msg, NULL, 0, 0) > 0) { /* If no error is received... */
		TranslateMessage(&msg); /* Translate key codes to chars if present */
		DispatchMessage(&msg); /* Send it to WndProc */
	}
	return msg.wParam;
}

**Comment by Fat-Fat-Lee** [comment]
之前发的那个不知道为什么复制上去有点不一样，老师们可以复制一下我新发的这个运行一下，不知道为啥一直Iid returned exit status   重启也不管用  麻烦老师们帮忙运行一下看看问题在哪里

**Comment by Fat-Fat-Lee** [comment]
#include <windows.h>

/* This is where all the input to the window goes to */
LRESULT CALLBACK WndProc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) {
PAINTSTRUCT pt;
HDC hDC;
switch(Message) {

	case WM_PAINT:
		hDC=BeginPaint(hwnd,&pt);//窗口可作用区域的标识 
		//画窗口的内容
		
		Rectangle(hDC,0,0,100,100); 
		
		
		
		
		
		EndPaint(hwnd,&pt);
		break; 
	/* Upon destruction, tell the main thread to stop */
	
	case WM_DESTROY: {
		PostQuitMessage(0);
		break;
	}
	
	/* All other messages (a lot of them) are processed using default procedures */
	default:
		return DefWindowProc(hwnd, Message, wParam, lParam);
}
return 0;
}


int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
 {
WNDCLASSEX wc; 
HWND hwnd;
MSG msg;

/* zero out the struct and set the stuff we want to modify */
memset(&wc,0,sizeof(wc));
wc.cbSize		 = sizeof(WNDCLASSEX);
wc.lpfnWndProc	 = WndProc; /* This is where we will send messages to */
wc.hInstance	 = hInstance;
wc.hCursor		 = LoadCursor(NULL, IDC_ARROW);

/* White, COLOR_WINDOW is just a #define for a system color, try Ctrl+Clicking it */
wc.hbrBackground = (HBRUSH)(COLOR_WINDOW);//定义窗口背景颜色 
wc.lpszClassName = "WindowClass";
wc.hIcon		 = LoadIcon(NULL, IDI_APPLICATION); /* 底下任务栏中的图标*/
wc.hIconSm		 = LoadIcon(NULL, IDI_APPLICATION); /* 打开页面条左上角的小图标 */

if(!RegisterClassEx(&wc)) {
	MessageBox(NULL, "Window Registration Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
	return 0;
}

hwnd = CreateWindowEx(WS_EX_CLIENTEDGE,"WindowClass","俄罗斯方块",WS_VISIBLE|WS_OVERLAPPEDWINDOW,
	100, /* x */
	100, /* y */
	500, /* width */
	500, /* height */
	NULL,NULL,hInstance,NULL);

if(hwnd == NULL) {
	MessageBox(NULL, "Window Creation Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
	return 0;
}

/*
	This is the heart of our program where all input is processed and 
	sent to WndProc. Note that GetMessage blocks code flow until it receives something, so
	this loop will not produce unreasonably high CPU usage
*/
while(GetMessage(&msg, NULL, 0, 0) > 0) { /* If no error is received... */
	TranslateMessage(&msg); /* Translate key codes to chars if present */
	DispatchMessage(&msg); /* Send it to WndProc */
}
return msg.wParam;
}

**Comment by Roycent** [comment]
编译选项中加入 -mwindows 即可解决
