### ISSUE TITLE
SwiftUI使用TextField后输入信息如何储存的问题

### ISSUE THREAD

**Issue by Guan-HM** [buaa21/summer2020#210]
在使用TextField后会产生一个用户输入界面，其中TextField的绑定参数是text: $tempName。我希望能将用户输入的信息储存到tempName中，然后调用一个函数将这个字符串放入一个类的数组中

代码如下
[month--final.zip](https://github.com/buaa21/summer2020/files/5154903/month--final.zip)

使用的View部分为文件ContentView中的add_event_window
想要调用的函数为event_list_view中的addEvent函数

**Comment by havesomecolo** [comment]
参考下这个看看：http://www.voidcn.com/article/p-kgnbsweh-bmc.html
