### ISSUE TITLE
SSLv3 SSLContext not available

### ISSUE THREAD

**Issue by Cirtl** [buaa21/summer2020#211]
AS中显示这样一个错误
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: SSLv3 SSLContext not available.
请问是jar包的版本不对吗

**Comment by Roycent** [comment]
比较简单的方法是换一个低版本的jdbc包（比如sqljdbc4）

**Comment by Cirtl** [comment]
我能找到的最老的版本就是这个了sqljdbc4-2.0.jar
然而还是出这个错误

**Comment by Cirtl** [comment]
总之无论如何是解决了（在网上找了一位博主的代码，复制了他的配置）
估计是我的jar包的问题
