### ISSUE TITLE
关于python中创建弹框的问题

### ISSUE THREAD

**Issue by dongcheng-shi** [buaa21/summer2020#212]
我用tkinter运行后出现两个弹框，一个是tk为标题的空白弹框，一个是我需要的提示框，上面写“（内容）”，请问怎么去掉那个空白弹框呢？

**Comment by buaa21** [comment]
信息太少，助教们无法准确地排查问题。

请新增一些信息，或者使用搜索引擎来搜索你需要的代码，将别人的代码与你的代码进行对比，理解某个语句干了什么事情。

**Comment by dongcheng-shi** [comment]
我用的是tkinter.messagebox.showinfo('（内容）','（内容）')

**Comment by PineZhuo** [comment]
添加root.withdraw()
```python
import tkinter as tk
import tkinter.messagebox
root = tk.Tk()
root.withdraw()
tk.messagebox.showinfo('标题','内容')
```

**Comment by dongcheng-shi** [comment]
好的解决了，谢谢
