### ISSUE TITLE
python出现AttributeError: 'builtin_function_or_method' object has no attribute 'top'的报错

### ISSUE THREAD

**Issue by Aresjiliu** [buaa21/summer2020#215]
![image](https://user-images.githubusercontent.com/58164412/91833077-cdba7100-ec78-11ea-8503-881d7d5b413b.png)
![image](https://user-images.githubusercontent.com/58164412/91833098-d448e880-ec78-11ea-9eb2-57232ad94161.png)

**Comment by crclz** [comment]
你在peachshooter类的self.top = 100 那个地方打一个断点，然后调试，看看self.rect的值是什么，自行查看一下有什么问题
