### ISSUE TITLE
python打包exe

### ISSUE THREAD

**Issue by heartworm1** [buaa21/summer2020#216]
请问python文件里面用绝对路径还是相对路径。绝对路径的话在其他电脑上执行不了好像，但相对路径本机都执行不了。

**Comment by Withinlover** [comment]
其实是无所谓的（

绝对路径和相对路径都可以打包，只不过用绝对路径的话必须把音频，图片也打包进入exe文件。不然换台电脑肯定运行不了（除非两台电脑建立一模一样的目录

关于如何在打包过程中添加其他文件：[pyinstaller --add-data命令](https://pyinstaller.readthedocs.io/en/v4.0/man/pyinstaller.html?highlight=--add-data#what-to-bundle-where-to-search)

anyway，相对路径本机执行不了可能是pycharm配置的问题。我一开始用的默认配置使用Virtualenv的时候是没法用相对路径的，后来我把代码保留了一下，删了项目用Exisiting interpreter重建一个项目就好了
