### ISSUE TITLE
pygame播放音效有明显延迟的问题

### ISSUE THREAD

**Issue by MychaelH** [buaa21/summer2020#217]
使用以下方式播放，有明显的延迟
```python
sound = pygame.mixer.Sound('./sound_effect/ding.wav')
sound.play()
```

**Comment by crclz** [comment]
希望这个解决了你的问题 https://stackoverflow.com/questions/18273722/pygame-sound-delay/36366595

**Comment by Zehong3351** [comment]
感觉应该调一下参数，减低你缓冲区的大小，减缓延迟的问题。 
例如：进口pygame的
pygame.mixer.init（频率= 22050，大小= -16，渠道= 2，缓冲= 512）
S = pygame.mixer.Sound（'snare.wav'）
s.play（循环= 0，MAXTIME = 0，fade_ms = 0）

**Comment by orixing** [comment]
这个问题昨天有人问过我，
![5A948439A6F9E946FAE99C8BAF21B3AA](https://user-images.githubusercontent.com/52653490/91930958-c052c480-ed14-11ea-888b-cc5b8cd2888c.jpg)
