### ISSUE TITLE
半成品再审核

### ISSUE THREAD

**Issue by 19231136** [buaa21/summer2020#218]
黑窗口  https://www.bilibili.com/video/BV1eT4y1w7w3/
GUI  https://www.bilibili.com/video/BV1654y1275W/
第一次学做GUI，会继续优化

**Comment by buaa21** [comment]
是高工的吗

**Comment by 19231136** [comment]
是啊

**Comment by PineZhuo** [comment]
UI还有很大的改进空间，继续加油吧！

**Comment by songyou21** [comment]
不错。基本达到暑期实践的目的了。继续加油。答辩时可以把两个代码对照着讲讲，分析其优缺点。

**Comment by 19231136** [comment]
谢谢助教和老师
