### ISSUE TITLE
pycharm文件调用失败

### ISSUE THREAD

**Issue by ljr19231244** [buaa21/summer2020#219]
![Q@K0AN@7NLZ6)J7`~)PD}46](https://user-images.githubusercontent.com/70185522/91852423-6827ae00-ec93-11ea-8a2f-cacf9b78655f.png)
我的constants里面是一些常数，使用import调用时提示No module named constants，并且显示为灰色，constants带有红色波浪线

**Comment by PineZhuo** [comment]
把constants文件改为.py文件
