### ISSUE TITLE
C语言开发代码行数

### ISSUE THREAD

**Issue by SilentElias** [buaa21/summer2020#22]
请问如果是使用C开发是一定要达到1000行吗，目前考虑制作小游戏但有可能达不到1000行的数量

**Comment by orixing** [comment]
给出的c语言1000行是为了让你们对我们预期的要求有个概念，要有一定的工作量，一定的复杂度。代码不够可以考虑增加一些新机制，新内容丰富自己的游戏

**Comment by songyou21** [comment]
1000行，是根据工作十天，平均每天100行来估算的。
有一定工作量即可，完成一个有成就的作品，不辜负这金秋时节的十天训练，不负韶华，即美好！
