### ISSUE TITLE
Python Tkinter库的Label标签控件怎么更新？

### ISSUE THREAD

**Issue by Neal2020GitHub** [buaa21/summer2020#221]
![微信截图_20200901214915](https://user-images.githubusercontent.com/70187327/91861131-0ec57c00-ec9f-11ea-9748-c9b04c5bfaca.png)

Scores：这里我用的是Label，想问一下这个score怎么随着分数改变而更新，就是旧的要整个
删掉，然后重新生成一个新的

**Comment by crclz** [comment]
https://www.delftstack.com/howto/python-tkinter/how-to-change-the-tkinter-label-text/

**Comment by Neal2020GitHub** [comment]
> label123.configure(text="aaa")

谢谢，我用StringVar()成功了
