### ISSUE TITLE
python打包问题

### ISSUE THREAD

**Issue by 1921zzk** [buaa21/summer2020#225]
![批注 2020-09-01 230911](https://user-images.githubusercontent.com/70182551/91870172-4cc79d80-eca9-11ea-90cc-4d4b01d3d2a1.png)
将py文件（含图片音乐和字体文件)打包成exe文件以后运行时报错，已经试过重新下载系统dll文件，但还是无法解决。

**Comment by crclz** [comment]
偏方：在打包的时候，加上这个参数：`--noupx`
https://stackoverflow.com/questions/38811966/error-when-creating-executable-file-with-pyinstaller

**Comment by 1921zzk** [comment]
好的，我试试

**Comment by Zehong3351** [comment]
试一下这个指令：pyinstaller -F -i ico图标 python文件
