### ISSUE TITLE
c#创建数据库

### ISSUE THREAD

**Issue by Ocean326** [buaa21/summer2020#227]
问题1：每次都报错
由于目标计算机积极拒绝，无法连接。 192.168.1.4:3306
问题2：这个创建数据库userID以及PWD在换一台电脑之后还能否继续使用？

**Comment by Ocean326** [comment]
using MySql.Data.MySqlClient;
private void CreateSQL()
        {
            MySqlConnection conn = new MySqlConnection("Data Source=localhost;Persist Security Info=yes; " +
                                                   "UserId=root; PWD=123456");
            MySqlCommand cmd = new MySqlCommand("CREATE DATABASE yiersan;", conn);

            conn.Open();

           
            try
            {
                cmd.ExecuteNonQuery();
                conn.Close();
                Console.WriteLine("建立数据库成功");
            }
            catch (Exception)
            {
                conn.Close();
                Console.WriteLine("建立数据库失败，已存在了");
                //throw;
            }



        }

**Comment by crclz** [comment]
你有运行mysql实例吗？应该首先在自己的电脑上运行mysql。

首先在mysql官网下载mysql，然后启动，并且用workbench链接mysql以确认mysql可用。
用户名和密码是预先由mysql配置文件决定的，和客户端（c#）无关。

**Comment by songoku1994** [comment]
这个报错可能是因为你mysql没有运行
