### ISSUE TITLE
python设计的游戏护盾一直存在

### ISSUE THREAD

**Issue by 19231219lsm** [buaa21/summer2020#228]
elif event.type==SHIELD_TIME:
                shields.active=False
                me.wudi=False
                pygame.time.set_timer(SHIELD_TIME,0)

           if shields.active:
                me.wudi = True
                shields.move((me.rect.left-25,me.rect.top-6))
                shields_hit = pygame.sprite.spritecollide(shields, enemies, False, pygame.sprite.collide_mask)
                pygame.time.set_timer(SHIELD_TIME,10*1000)
                if shields_hit:
                    shields.hit = True
                if shields.hit:
                    if switch_images:
                        screen.blit(shields.image2, shields.rect)
                    else:
                        screen.blit(shields.image1, shields.rect)
                    shields.hit = False

                else:
                    screen.blit(shields.image1, shields.rect)不知道这边哪里有问题，护盾并没有在10s后取消

**Comment by Lighten-w** [comment]
一般这种情况，代码逻辑出问题的可能性比较大，建议仔细排查

**Comment by songoku1994** [comment]
emmm这可能你得自己先办法debug了
