### ISSUE TITLE
pygame的npc运动问题

### ISSUE THREAD

**Issue by buaa-gavin** [buaa21/summer2020#229]
做的吃豆人，npc方向控制用的random函数随机上下左右，结果npc在游戏开始后没多久就在地图边界上卡着了，有没有什么方法让npc运动得智能一点。

**Comment by SeventhGX** [comment]
参考思路：
1、对于每个npc，在地图上指定若干点，让它在这些点间以随机顺序移动
2、让npc始终向着玩家移动
可以考虑把npc分成两类，分别按不同的逻辑移动
需要解决的问题就是如何找到地图上任意两点之间的路线

**Comment by SeventhGX** [comment]
或者也可以进行结合，npc全部按第1条提到的方法移动，但当玩家进入到npc附近一定范围时开始追踪玩家，当追踪一段时间后取消追踪，返回设定的路径

**Comment by orixing** [comment]
可以把每一个分叉点设置为点，然后路径长度为边的权值来找最短路径
