### ISSUE TITLE
C语言中的button组件如何接受鼠标右键信息

### ISSUE THREAD

**Issue by RuQ7** [buaa21/summer2020#23]
用C语言中的HWND类型生成了按钮窗口，但只能检测到左键点击的信息，并且在按钮上右击时，无法捕获到鼠标信息，请教右击按钮时，返回的message是哪种信息，或者如何捕获在按钮上的鼠标右键信息。如下
```c
LRESULT CALLBACK WndProc(
    HWND hWnd,
    UINT message,
    WPARAM wParam,
    LPARAM lParam)
{
     switch (message)
    {
        case WM_RBUTTONDOWN: \\右键点击时
        {
         ...
        }
        break;
        default:
            return DefWindowProc(hWnd, message, wParam, lParam);
    }
}
```

**Comment by RuQ7** [comment]
或者如何自定义一个message信息满足需求

**Comment by havesomecolo** [comment]
按钮控件的左键单击消息是默认的，直接classwizard添加即可。
右键消息按钮控件默认是不支持的，需要自己处理。
两种办法：
1. 派生一个自己的按钮类，并绑定指定控件。在自定义按钮类中处理wm_rbuttondown消息。
2. 在对话框所在类cxxxdlg里面重载 pretranslatemessage，并在其中这样处理消息：
bool cxxxdlg::pretranslatemessage（msg *pmsg）
{
// todo: 在此添加专用代码和/或调用基类
if(pmsg->message==wm_rbuttondown)       //可以改为任何消息
{
crect r;
::getwindowrect(getdlgitem(idc_00)->getsafehwnd(),&r);   //得到button所在的rect
point pt;
::getcursorpos(&pt);             //得到鼠标动作的位置
if (ptinrect(&r,pt))        //判断鼠标动作是否在button范围之内     
{
afxmessagebox(_t("右键单击"));
}
}
return cdialog::pretranslatemessage(pmsg);
}
网上搜的，试试看行不行

**Comment by buaa21** [comment]
建议使用热门的技术开发桌面app https://github.com/buaa21/summer2020/blob/master/README.md#%E6%A1%8C%E9%9D%A2%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91
