### ISSUE TITLE
winform中用SQL语句更新一个int类型的值

### ISSUE THREAD

**Issue by Z8232000** [buaa21/summer2020#230]
用一个int类型的值score去更新一个数据库中的int值scores,
SQL语句应该怎么写？引号，加号等问题不会处理。

**Comment by SeventhGX** [comment]
[参考](https://blog.csdn.net/weixin_44458191/article/details/86501064)

**Comment by Z8232000** [comment]
<img width="402" alt="微信图片_20200902104554" src="https://user-images.githubusercontent.com/70097338/91926321-98119880-ed09-11ea-8fea-98bc8fc2f1c8.png">
这样写为什么实现不了数据更新？
用Console.WriteLine调试了，score和check的值都没问题

**Comment by crclz** [comment]
> <img alt="微信图片_20200902104554" width="402" src="https://user-images.githubusercontent.com/70097338/91926321-98119880-ed09-11ea-8fea-98bc8fc2f1c8.png">
> 
> 这样写为什么实现不了数据更新？ 用Console.WriteLine调试了，score和check的值都没问题

因为你没有execute这个command
