### ISSUE TITLE
如何让vs一个项目下多个.c文件

### ISSUE THREAD

**Issue by xiao-binhan** [buaa21/summer2020#231]
头文件是每个.c文件里都要有吗

**Comment by PineZhuo** [comment]
创建一个工程项目，例如这个教程https://blog.csdn.net/iamsongyu/article/details/89630831
可以有多个.c文件，但是只能有一个main函数
头文件是看你的需求，，你在某个.c文件里调用了一些库函数，就需要引入包含这些库函数的头文件
