### ISSUE TITLE
使用unity时出现以下错误提示是什么原因呢？需要修改哪部分呢

### ISSUE THREAD

**Issue by JackeyloveRain** [buaa21/summer2020#232]
EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by SeventhGX** [comment]
能找到的信息都提示和[GUIUtility.ExitGUI();](https://forum.unity.com/threads/endlayoutgroup-beginlayoutgroup-must-be-called-first.523209/)有关，可以参考一下

**Comment by songoku1994** [comment]
参考下这个：https://forum.unity.com/threads/endlayoutgroup-beginlayoutgroup-must-be-called-first.523209/
