### ISSUE TITLE
C语言我用了fopen来打开txt文件，我想让这个文件直接被打开并弹出方便用户向里面输入内容而不是悄悄的在后台打开谁也看不见，要怎么做呢？

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#233]
![image](https://user-images.githubusercontent.com/70250586/91926608-2e45be80-ed0a-11ea-995f-2c47494d0d86.png)

**Comment by SeventhGX** [comment]
[用系统命令调用记事本打开txt文件](https://bbs.csdn.net/topics/80501257)
