### ISSUE TITLE
python打包问题

### ISSUE THREAD

**Issue by 1921zzk** [buaa21/summer2020#234]
将test.spec文件打包成的exe运行时遇到这样的问题，图中的test.py是我要打包的py文件，该如何解决。

**Comment by 1921zzk** [comment]
![微信图片_20200902105226](https://user-images.githubusercontent.com/70182551/91926831-b75cf580-ed0a-11ea-915f-1c8db6ee63d4.jpg)

**Comment by crclz** [comment]
建议先去网上下载一份别人写的某小游戏的代码，然后参照教程用pyinstaller打包，看看有无问题。

然后再来打包你自己的

**Comment by 1921zzk** [comment]
打包没有图片和音乐的小游戏没有问题，我这个包含音乐和图片还有字体，但是已经尝试加入字体，音乐和图片一起打包还是运行错误。

**Comment by crclz** [comment]
你去搜索一下：pyinstaller打包资源文件
