### ISSUE TITLE
软件设计说明书

### ISSUE THREAD

**Issue by heartworm1** [buaa21/summer2020#235]
软件设计说明书中程序描述的性能该从哪些方面去分析？

**Comment by heartworm1** [comment]
还有算法的介绍是描述还是附上代码

**Comment by iceryang** [comment]
算法的描述，要写完成的功能，解决的问题，算法逻辑说出来，再用代码实现逻辑

**Comment by iceryang** [comment]
软件性能要求：

1、负载测试；通过自动化测试工具模拟程序或者软件系统在超强负荷条件下，观察系统各项性能指标的变化情况，一般与压力测试共同进行。

2、强度测试；指系统在资源条件很差工作环境下的运行情况，如人为限制网络带宽，内存等。

3、容量测试；一般指模拟用户不断增加时，确定系统可以处理同时在线的最大用户数量。https://wenku.baidu.com/view/86f7f0c6d5bbfd0a79567333.html
