### ISSUE TITLE
pygame开发游戏，pycharm上运行正常，打包成exe闪退怎么办？

### ISSUE THREAD

**Issue by 1907FB** [buaa21/summer2020#238]

**Comment by 1907FB** [comment]
游戏中包含了一些中文字体，和特殊字体，是不是没办法打包了？

**Comment by SeventhGX** [comment]
如果是字体问题试着参考一下[这个](https://blog.csdn.net/ckkling/article/details/100386155)？

**Comment by 1907FB** [comment]
> 如果是字体问题试着参考一下[这个](https://blog.csdn.net/ckkling/article/details/100386155)？

谢谢谢谢，我已经找到问题了，打包好像不支持mp3格式的音乐
