### ISSUE TITLE
怎样避免背景被清屏？

### ISSUE THREAD

**Issue by 19231134** [buaa21/summer2020#24]
可以用setbkcolor()为界面的不同区域设置不同背景颜色吗？怎样避免背景被清屏？

**Comment by buaa21** [comment]
不建议使用c/c++开发gui或者控制台ui的程序。

可以使用pygame或者c# winform

https://github.com/buaa21/summer2020/blob/master/README.md#%E6%A1%8C%E9%9D%A2%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91
