### ISSUE TITLE
C++中设置背景音乐

### ISSUE THREAD

**Issue by lyj2209914083** [buaa21/summer2020#240]
请问C++设置背景音乐
#include<windows.h>
#pragma comment(lib, "Winmm.lib")
int main()
{
PlaySound("文件绝对位置", NULL, SND_FILENAME | SND_ASYNC| SND_LOOP);
....
}
这样不行的话该如何改？

**Comment by PineZhuo** [comment]
1、头文件添加：#include <mmsystem.h>
2、添加链接windows的动态链接库WINMM.LIB。在编译器的设置中，添加链接-lwinmm
3、把路径里的中文改成英文
