### ISSUE TITLE
小程序没法修改代码

### ISSUE THREAD

**Issue by HenryDamon** [buaa21/summer2020#243]
修改后保存，一直弹出提示权限不足，请以管理员身份覆盖重试，但点击重试仍然重复跳出，点击另存为然后替换也不行

**Comment by HenryDamon** [comment]
只能另存为然后替换文件，算是变相能保存了

**Comment by HenryDamon** [comment]
![image](https://user-images.githubusercontent.com/68911150/91970283-01b19700-ed4a-11ea-9913-1abea9abd29b.png)

**Comment by HenryDamon** [comment]
最后新建文件然后导入可以修改，但是仍然无法新建和修改之前的

**Comment by Roycent** [comment]
找到那个文件，然后右键->属性->安全->编辑，然后把Users的“完全控制”中的“允许”项选上试试
