### ISSUE TITLE
半成品评审

### ISSUE THREAD

**Issue by RaymondKevin** [buaa21/summer2020#247]
是一个类似于Teambition的微信小程序
![扫码_搜索联合传播样式-白色版](https://user-images.githubusercontent.com/70182598/91971468-d0d26180-ed4b-11ea-8deb-138a510a74c1.png)

**Comment by RaymondKevin** [comment]
二维码加载好像有点困难，小程序的名称是TeamCloud（才发现早就已经有了个叫CloudTeam的 =_=）

**Comment by iceryang** [comment]
名字差不多没有问题，你可以对照对方，看有没有可以参照的改进。

**Comment by iceryang** [comment]
名字差不多没有问题，你可以对照对方，看有没有可以参照的改进。
