### ISSUE TITLE
pygame怎么弄游戏界面

### ISSUE THREAD

**Issue by cjwu-51** [buaa21/summer2020#249]

**Comment by PineZhuo** [comment]
麻烦详细描述你的需求、你做过的尝试、你遇到的问题。

**Comment by cjwu-51** [comment]
就是现在写出来的代码是运行之后游戏就直接开始了，我想在这个代码的基础上能够在运行程序之后能出来一个界面让我用鼠标点击开始游戏之类的，我想问一下有什么简单的方法能够实现这个需求

**Comment by songoku1994** [comment]
可以找一些pygame开始界面制作的教程，可以参考一下这个：https://blog.csdn.net/pianzang5201/article/details/78404711?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.channel_param&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.channel_param

**Comment by orixing** [comment]
在主循环前加一个和主循环类似的循环用来展示开始界面，点击开始后退出这个循环进入主循环
