### ISSUE TITLE
我想要创建win32项目，是应该在Dev C++创建项目中选择Windows Application吗？要是这样我怎么添加图片资源？旁边项目管理中并没有资源文件夹

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#25]
![image](https://user-images.githubusercontent.com/70250586/91290878-c7cf1680-e7c6-11ea-921e-360fa2f16250.png)
我要怎样才能添加额外的图片资源用来自定义窗口图标？

**Comment by Lighten-w** [comment]
如果想用c/cpp开发图形界面建议使用visual studio 或者 qt creator

**Comment by PineZhuo** [comment]
给出另一种解决思路，使用远程图片链接

**Comment by songoku1994** [comment]
开发桌面应用的话建议用qt creator，有比较详细的官方文档

**Comment by buaa21** [comment]
建议使用热门的技术开发桌面app https://github.com/buaa21/summer2020/blob/master/README.md#%E6%A1%8C%E9%9D%A2%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91
