### ISSUE TITLE
Java 怎么把菜单栏和游戏界面组合在一起

### ISSUE THREAD

**Issue by starrrrgazer** [buaa21/summer2020#250]
已经做好了菜单栏和游戏界面
![image](https://user-images.githubusercontent.com/70183278/91982943-8f4ab200-ed5d-11ea-8f5d-5a48aee34442.png)
但是我把游戏放到jpanel，再放到jframe（布局是null），之后add菜单栏，并没有成功，而是跳转到了一个container.class文件里。。。。

**Comment by crclz** [comment]
你先新开一个工程，创建一个背景为红色的jpanel为菜单栏，然后创建一个背景为蓝色的jpanel为游戏，然后尝试把它们弄成你想要的布局。

成功之后，再对原来的游戏工程进行调整。

**Comment by starrrrgazer** [comment]
emm。。。。我终于找到问题了，我忘了我写的菜单栏也是jframe了，所以无法再加入到jframe里，我把游戏放到jpanel就好了，谢谢
