### ISSUE TITLE
关于python打包的问题

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#251]
如题，用命令行窗口命令py -m pip install pyinstaller下载pyinstaller时，一直提示这样，请问是怎么回事？
![2376ced4b6d5b15247f0dfb8152d1bd](https://user-images.githubusercontent.com/70182453/91984747-db4a2680-ed5e-11ea-8e5f-5902da083484.png)

**Comment by Roycent** [comment]
网络问题，可以试一下 pip install pyinstaller -i https://mirrors.ustc.edu.cn/pypi/web/simple/

**Comment by hrx20000209** [comment]
现在是这样
![799a3d777e2052e6e6955107a8e94fe](https://user-images.githubusercontent.com/70182453/91990086-e0f63b00-ed63-11ea-9bce-ad4c4c9e225c.png)

**Comment by Roycent** [comment]
看一下最后一行显示的是什么，一般错误会在最后显示

**Comment by hrx20000209** [comment]
最后一行是这样
![e11b8b9483e2d7461f83f6b17744c18](https://user-images.githubusercontent.com/70182453/91997423-a80e9400-ed6c-11ea-8e12-d8fdff40e129.png)

**Comment by Roycent** [comment]
先安装一下wheel，然后再安装pyinstall试试

**Comment by hrx20000209** [comment]
安装好了，打包出来后的exe文件打开是这样的
![3d84c562b5d5e714f2bd23c35f6232d](https://user-images.githubusercontent.com/70182453/92000744-73044080-ed70-11ea-94ce-c326a3b9df4b.png)

**Comment by buaa21** [comment]
建议充分利用中文和英文的搜索引擎
