### ISSUE TITLE
pygame 打包问题

### ISSUE THREAD

**Issue by buaadzr** [buaa21/summer2020#252]
1.pygame打包后的程序需要与此前使用的游戏资源（图片，字体等）处于同一文件夹，才可正常工作（程序编写时，.py文件和资源处于同一文件下）
2.程序运行后出现第一个黑框输出“Hello pygame xxxxx”，之后才跳出游戏程序的窗口
如何解决或者这是正常现象吗？

**Comment by buaa21** [comment]
请在问题列表中搜索“打包”
