### ISSUE TITLE
用VS2019为什么可以Debug但是生成不了Release版本

### ISSUE THREAD

**Issue by BUAALX** [buaa21/summer2020#256]

**Comment by BUAALX** [comment]
![Uploading IMG_20200902_213716.jpg…]()
![Uploading IMG_20200902_213741.jpg…]()

**Comment by PineZhuo** [comment]
报错是什么呢？生成release可以看一下这个教程https://blog.csdn.net/cxs5534/article/details/106591233/

**Comment by BUAALX** [comment]
报错主要是一些loadimage 与outtextxy

**Comment by BUAALX** [comment]
按照文章修改后仍有：没有与参数列表匹配的重载函数loadimage与outtextxy的实例

**Comment by BUAALX** [comment]
已解决，改为多字符集
