### ISSUE TITLE
pygame如何自动关闭界面

### ISSUE THREAD

**Issue by huahuaxiaomuzhu** [buaa21/summer2020#26]
执行sys.exit()后界面无响应

**Comment by Matrix53** [comment]
有代码吗

**Comment by huahuaxiaomuzhu** [comment]
os.system('python PVE.py')
pygame.quit()
sys.exit()
是不是因为前边的os?

**Comment by orixing** [comment]
是想关闭执行os.system的这个页面吗？尝试捕获一下sys.exit()的异常，或者如果是要直接退出，不执行后续任何代码的话可以用os._exit

**Comment by huahuaxiaomuzhu** [comment]
os.system('python PVE.py')
打开新页面之后执行os.system的页面就无响应了，后边的os._exit似乎没有执行

**Comment by huahuaxiaomuzhu** [comment]
#include<stdlib.h>
int main(){
    system("python start.py");
    exit(1);
}
C语言执行完system命令之后也不执行exit(1)，是做不到吗？

**Comment by Matrix53** [comment]
c语言的话，你的start.py执行完毕之后才会执行exit，是不是start.py还没执行完

**Comment by huahuaxiaomuzhu** [comment]
是的是的，我明白了，谢谢
