### ISSUE TITLE
软件规格需求说明书 3.2.2 写作疑问

### ISSUE THREAD

**Issue by Withinlover** [buaa21/summer2020#260]
开发的是小游戏，从头到尾用到的模块都是密不可分的，将模块单独拿出来的话本身并不能正常运行

这样的情况，如何分模块的给出用例图。

或者说，应当把整个游戏当成一个模块，进行笼统的介绍？

**Comment by iceryang** [comment]
如果没有独立的功能区分，先试着用流程化的分析。不一定都是用例，只要逻辑清晰。复杂游戏设计再用用例。
