### ISSUE TITLE
算法问题

### ISSUE THREAD

**Issue by BUAAhuangsh** [buaa21/summer2020#263]
如何实现在m个不同的数字中随机选出n个不相同的数字

**Comment by SeventhGX** [comment]
最基本的思路，用时间戳作为随机数种子，生成1-m的随机数，结果是几就选第几个数字，重复n次
同时记录每次生成的结果，每生成一个新的就在已经生成的结果里进行比对，如果重复了就再生成一次

**Comment by crclz** [comment]
如果是python的话，建议查看`random.sample`

**Comment by IAmParasite** [comment]
可以维护一个set进行对比...

**Comment by songoku1994** [comment]
参考一下这个，感觉网上其实蛮多的：https://blog.csdn.net/qq_39197555/article/details/89402853
