### ISSUE TITLE
关于算法

### ISSUE THREAD

**Issue by shadowight** [buaa21/summer2020#265]
使用历史启发算法时，能否用别的替代numpy库，还是说只能使用numpy来处理

**Comment by SeventhGX** [comment]
是因为什么原因不想用numpy呢
确实存在一些启发式算法的[框架](https://www.zhihu.com/question/49098839)，但其中也很有可能调用了numpy

**Comment by songoku1994** [comment]
可以用别的库，具体看你需求，numpy应该基本够了
