### ISSUE TITLE
如何使文本换行

### ISSUE THREAD

**Issue by mono-jiarui** [buaa21/summer2020#266]
![$U7DIB)OBC %731D%HQ24$Q](https://user-images.githubusercontent.com/70185522/92062116-847a3680-edca-11ea-86ec-b32e743797cd.png)
在屏幕上打出文字内容会超出界面，如何换行，我使用\n在屏幕上出现的是一个小方块而不是换行
代码如下，text5内容我随便打的
text5 = font.render('465\n1984649736279\n259825626\n13673976', True, (0, 0, 0))
screen.fill((250, 240, 230))
screen.blit(text5, (100, 300))
pygame.display.flip()

**Comment by mono-jiarui** [comment]
使用的是pycharm，python语言

**Comment by SeventhGX** [comment]
我比较推荐分成多个text，分别显示
各个text的定位可以用一个基础值+若干相对偏移来决定
