### ISSUE TITLE
在pygame中调用tkinter的问题

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#267]
因为pygame只支持一个窗口，因此想要加入“设置”窗口就只能采用tkinter。
我在pygame的window上建立了一个按钮，通过点击它打开tkinter的窗口。
但是现在这个窗口只能打开一次，之后再点击按钮则没有反应了。
请问可不可以重复触发这个窗口呢？

**Comment by orixing** [comment]
能贴一下窗口部分的代码吗

**Comment by hrx20000209** [comment]
pygame窗口部分的吗？
比较长
