### ISSUE TITLE
关于打包的问题，没有搜索到这种情况

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#276]
cmd中pyinstaller运行成功，点击dist里面的exe文件之后弹出了cmd窗口，然后过一段时间就弹出了这个。
![618ad498ed8e7de1507d36050afe8a6](https://user-images.githubusercontent.com/70182453/92091744-beb3fa00-ee03-11ea-981a-c01cff0171c4.png)

**Comment by crclz** [comment]
怎么搜索不到？百度或者bing搜索`pyinstaller vcruntime140`
