### ISSUE TITLE
mac如何实现windows中<conio.h>的getch()函数

### ISSUE THREAD

**Issue by jianhong1009** [buaa21/summer2020#28]
mac如何实现windows中<conio.h>的getch()函数, mac上没有<conio.h>头文件

**Comment by Lighten-w** [comment]
可以考虑使用c/cpp标准库中的函数代替，eg: getchar or cin 等

**Comment by jianhong1009** [comment]
可是getchar有回显，还得输入enter后才会继续执行，getch没回显没缓冲

**Comment by orixing** [comment]
可以用Ncurses库
https://rhardih.io/2010/04/using-ncurses-in-c-for-text-user-interfaces-featuring-xcode/

**Comment by crclz** [comment]
https://blog.csdn.net/dshf_1/article/details/86773054 善用搜索引擎。不知道这个链接是不是你想要的

**Comment by jianhong1009** [comment]
这个csdn的链接之前看过了，尝试过，但是它只能实现无缓存的getchar，即比如输入字符a后，不用按下enter就能继续执行程序，但是a还是会显示在屏幕上，而getch的话，输入a后，a不会显示在屏幕上（无回显）

**Comment by orixing** [comment]
Ncurses的noecho()可以实现取消回显
