### ISSUE TITLE
visual studio输出窗口怎样关闭

### ISSUE THREAD

**Issue by XuanMing66** [buaa21/summer2020#282]
请问我用visual studio生成的程序它在加载图片之前会先跳出来一个黑色的输出窗口，请问这个东西怎样去掉，语言为c语言、c++

**Comment by BFlameSwift** [comment]
launch.json 文件下的这一行 ture改成false（应该是
"externalConsole": false,// 调试时是否显示控制台窗口，一般设置为true显示控制台

**Comment by XuanMing66** [comment]
额，我在我的这个项目里面没有找到这个文件
