### ISSUE TITLE
为什么在程序的多个函数括号后面都出现了报错expected '=', ',', ';', 'asm' or '__attribute__' before '{' token？？我查看了我的函数书写格式明明没有问题啊？是跟头文件有关吗？

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#29]
`//函数实现
#include"eluosihead.h"
//背景数组
int g_arrBackground[20][10];
int g_arrSquare[2][4]; 
 
void OnPaint(HDC hDC)
{
	//创建兼容性内存DC
	HDC HMemDC=CreateCompatibleDC(hDC); 
	//创建兼容性位图
	HBITMAP hBitmapBack=CreateCompatibleBitmap(hDC,320,645);  
	//把编号和位图关联起来
	SelectObject(HMemDC,hBitmapBack); 
	
	PaintSquare(HMemDC);
	
	BitBlt(hDC,0,0,300,600,HMemDC,0,0,SRCCOPY);

	DeleteObject(hBitmapBack);
	DeleteDC(HMemDC);
	
}

// 初始化函数 
void OnCreate()
{
	srand((unsigned int)time(0));
	CreateRandomSquare(); 
	
} 

//显示方块 
void PaintSquare(HDC HMemDC)
{
	int i,j,k;
	//画大方块
	Rectangle(HMemDC,0,0,300,600); 
	//画小方块，遍历
	for(i=0;i<20;i++)
	{
		for(j=0;j<10;j++)
		{
			if(g_arrBackground[i][j]==1)
				Rectangle(HMemDC,j*30,i*30,j*30+30,i*30+30);// 
		}
	} 
	
 } 
 
 
 //创建随机块
void CreateRandomSquare()
{
	int nindex=rand();
	switch(nindex%7)
	{
		case 0:
			g_arrSquare[0][0]=1,g_arrSquare[0][1]=1,g_arrSquare[0][2]=1,g_arrSquare[0][3]=1;
			g_arrSquare[1][0]=0,g_arrSquare[1][1]=0,g_arrSquare[1][2]=0,g_arrSquare[1][3]=0;
			break;
		case 1:
			g_arrSquare[0][0]=0,g_arrSquare[0][1]=1,g_arrSquare[0][2]=1,g_arrSquare[0][3]=0;
			g_arrSquare[1][0]=1,g_arrSquare[1][1]=1,g_arrSquare[1][2]=0,g_arrSquare[1][3]=0;
			break;
		case 2:
			g_arrSquare[0][0]=1,g_arrSquare[0][1]=0,g_arrSquare[0][2]=0,g_arrSquare[0][3]=0;
			g_arrSquare[1][0]=1,g_arrSquare[1][1]=1,g_arrSquare[1][2]=1,g_arrSquare[1][3]=0;
			break;
		case 3:
			g_arrSquare[0][0]=0,g_arrSquare[0][1]=0,g_arrSquare[0][2]=1,g_arrSquare[0][3]=0;
			g_arrSquare[1][0]=1,g_arrSquare[1][1]=1,g_arrSquare[1][2]=1,g_arrSquare[1][3]=0;
			break;
		case 4:
			g_arrSquare[0][0]=0,g_arrSquare[0][1]=1,g_arrSquare[0][2]=1,g_arrSquare[0][3]=0;
			g_arrSquare[1][0]=1,g_arrSquare[1][1]=1,g_arrSquare[1][2]=0,g_arrSquare[1][3]=0;
			break;
		case 5:
			g_arrSquare[0][0]=0,g_arrSquare[0][1]=1,g_arrSquare[0][2]=1,g_arrSquare[0][3]=0;
			g_arrSquare[1][0]=0,g_arrSquare[1][1]=,g_arrSquare[1][2]=1,g_arrSquare[1][3]=0;
			break;
		case 6:
			g_arrSquare[0][0]=1,g_arrSquare[0][1]=1,g_arrSquare[0][2]=1,g_arrSquare[0][3]=1;
			g_arrSquare[1][0]=0,g_arrSquare[1][1]=0,g_arrSquare[1][2]=0,g_arrSquare[1][3]=0;
			break;
		
	}
	return;
 } 
 
//随机块贴入背景 
void CopySquareToBack()
{
	int i,j;
	for(i=0;i<2;i++)
	{
		for(j=0;j<4;j++)
		{
			g_arrBackground[i][j+3]=g_arrSquare[i][j]; 
		}
	}
	
 }	 
 `
![image](https://user-images.githubusercontent.com/70250586/91309072-beec3e00-e7e2-11ea-9ce3-8a35b7f881df.png)

**Comment by crclz** [comment]
你用控制变量法测试一下：
把代码换成
```c++
#include "eluosihead.h"

int main(){
}
```

如果还出错，就说明头文件有问题，去检查一下头文件是否缺少大括号等结构性的字符。

**Comment by Fat-Fat-Lee** [comment]
哦~原来如此！！！！！头文件里少加了分号！多谢助教！！！！
