### ISSUE TITLE
每发布一个问题最长时间多久会得到回复呢？因为一直得不到解决的话，代码就会一直卡住无法进行下去，再加上时间很紧，所以想了解一下。

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#32]

**Comment by crclz** [comment]
我们去年要求2000行的时候，可没有这种答疑资源。所以，同学们应当积极搜索网络，而不是完全依赖于答疑。更不能把作品的进度过度依赖于答疑。

另外你可以看到，那些卡住的问题，大多都是用c/c++来写图形界面/桌面app的问题。

一个重要的原因是，我们助教也不太会这些冷门的技术。如果采用的是swing/winform/wpf，就没有这么多问题了。一方面这些开发手段成熟、易用（隐藏了底层细节），另一方面网上可供搜索的资料多，并且助教也更加熟悉这些框架。

明天会针对这些情况做一个针对各分类的开发教程，防止同学们浪费时间。

**Comment by crclz** [comment]
对于桌面程序的开发指引，请看 https://github.com/buaa21/summer2020#%E6%A1%8C%E9%9D%A2%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91
