### ISSUE TITLE
python 文件处理

### ISSUE THREAD

**Issue by ZC-tan** [buaa21/summer2020#35]
源代码：
mainCharacter = pygame.image.load("pngs\\mainCIdle.png")
**pngs文件与主程序同个目录**
出现错误提示：
Traceback (most recent call last):
  File "c:\Users\tanzc\Desktop\VSCode\Rogue\main.py", line 12, in <module>
    mainCharacter = pygame.image.load("pngs\\mainCIdle.png")
pygame.error: Couldn't open pngs\mainCIdle.png

如果使用完整的path信息却可以运行
mainCharacter = pygame.image.load("C:\\Users\\tanzc\\Desktop\\VSCode\\Rogue\\pngs\\mainCIdle.png")
这是否代表如果这个程序让其他电脑使用就无法正常运行？有什么办法处理吗？

**Comment by Matrix53** [comment]
可以使用os.getcwd()获取当前工作路径

**Comment by ZC-tan** [comment]
好的谢谢
