### ISSUE TITLE
java安装配置不成功

### ISSUE THREAD

**Issue by lzh490120893** [buaa21/summer2020#36]
按照PPT步骤安装和配置后，输入javac并没有显示javac的用法

**Comment by Lighten-w** [comment]
建议检查环境变量是否配置正确，以及添加上输出截图

**Comment by crclz** [comment]
建议：
1. 对于这个问题，请检查是否正确地在环境变量PATH里面添加了javac所在的目录
1. 使用一个IDE，例如IDEA、Eclipse。IDE里面有编译的一些功能，避免了手动命令行编译
2. 充分利用搜索引擎寻找教程
