### ISSUE TITLE
Python全局变量的引用 - global关键字

### ISSUE THREAD

**Issue by Withinlover** [buaa21/summer2020#38]
RT，在代码实现的过程中发现的问题（示例代码经过简化

```python

# Constants
Position = [0, 0]

def Test():
    Position = [2, 2]
    print(Position)

def Debug():
    print(Position)

def main():
    Test()
    Debug()

if __name__ == '__main__':
    main()

```

输出的结果是：

```text
[2, 2]
[0, 0]
```

初步判断是在执行Test函数时，在函数内部将Position当作了一个新的局部变量

其中一个解决方案是在引用前加上 global 关键字，改写为

```python
def Test():
    global Position
    Position = [2, 2]
    print(Position)
```

然而在参考实际的工程代码时，发现几乎没有用到过global关键字
<del>[随手找的代码](https://github.com/Zikian/PyMario/blob/master/data/menu.py)</del>
[刚刚找错错了这个才是主程序](https://github.com/Zikian/PyMario/blob/master/data/main.py)
寻求一个替代的方案（

写全局变量的目的就是为了多个函数调用同一个变量时可以方便一点
但是添加global关键字明显违背了这一初衷（因为这样子每个函数前面都有一个类似定义的过程

**Comment by PineZhuo** [comment]
[[工程上几乎不使用是因为，在工程上，python多使用面向对象的思想进行编程，和c语言面向过程的编程是不同的。用面向对象的思想编写你的思路，代码如下，可以看出，self.position就是在Main类里的一个类似于全局变量的存在，而在test方法里的position，则是函数中的局部变量，python面向对象的思想和做法可以参考菜鸟教程](https://www.runoob.com/python/python-object.html)
```
class Main():
    def __init__(self):
        self.position = [0, 0]
    
    def Test(self):
        self.position = [2, 2]
        print(self.position)
        position = [3,3] #局部变量
        print(position)

    def Debug(self):
        print(self.position)

if __name__ == '__main__':
    m1 = Main()#创建Main类的一个对象
    m1.Test()
    m1.Debug()
```
