### ISSUE TITLE
vs新建项目出现问题，找不到exe文件

### ISSUE THREAD

**Issue by Rander-sun** [buaa21/summer2020#39]
![H PX6_ QIHWLL6B%W645X U](https://user-images.githubusercontent.com/70186286/91386583-e9330f80-e865-11ea-89ea-84315c9ff92d.png)
如图，该怎么新建项目才不会出现这种情况？

**Comment by Rander-sun** [comment]
是vs2019版

**Comment by crclz** [comment]
1. 看看那个exe是不是确实在那里
2. 选择一个无空格的目录来创建工程。同时，工程目录和命名也别有空格
