### ISSUE TITLE
微信小程序，多列选择器.js中为什么直接修改timeIndex不行，必须var data并赋值？

### ISSUE THREAD

**Issue by HenryDamon** [buaa21/summer2020#40]
以下为涉及该问题的.js代码，斜线部分为什么不能少？

Page({
  **data:** {
    timeArray:[['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23'],['00','05','10','15','20','25','30','35','40','45','50','55']，['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23'], ['00','05','10','15','20','25','30','35','40','45','50','55'],],
    timeIndex: [12, 0, 12,0],
  },

  **bindTimeColumnChange: function (e)** {
    _var data = {
      timeArray: this.data.timeArray,
      timeIndex: this.data.timeIndex
    };
    data.timeIndex[e.detail.column] = e.detail.value;_
    if(!e.detail.column) data.timeIndex[2] = data.timeIndex[0];
    this.setData(data);
  },
})

**Comment by crclz** [comment]
任何对于数据的修改都应该通过this.setData来进行修改，否则会造成数据与视图的不一致。this.setData会通知视图，让视图重新渲染改变的数据。

对于这个问题，你只是要修改数组的某一项，不用这么麻烦，只需要用路径的形式给出修改的操作。

https://blog.csdn.net/qq_42817227/article/details/84834210 
> Object 以 key: value 的形式表示，将 this.data 中的 key 对应的值改变成 value。
其中 key 可以以数据路径的形式给出，支持改变数组中的某一项或对象的某个属性，如 array[2].message，a.b.c.d，并且不需要在 this.data 中预先定义。

**Comment by HenryDamon** [comment]
unknown: Unexpected token, expected , (56:50)
> 56 |     if(e.detail.column==0) this.setData({timeIndex[2] : timeIndex[0]});

提示2前面的中括号有问题

**Comment by IAmParasite** [comment]
及时查看微信的官方文档，95%的问题都会被解决的
