### ISSUE TITLE
QT生成rcc文件

### ISSUE THREAD

**Issue by GCZYABC** [buaa21/summer2020#43]
使用cmd让QT生成rcc文件时提示rcc不是内部或外部命令，请问该怎么解决

**Comment by crclz** [comment]
善用搜索引擎。去搜索 ”rcc不是内部或外部命令“。
https://blog.csdn.net/zhangbinsijifeng/article/details/46604855 ，不知道有没有用。
初步估计是rcc.exe所在目录没有被添加到环境变量PATH

**Comment by GCZYABC** [comment]
emmm就是没看懂这个
配置好环境变量后还是不行
