### ISSUE TITLE
制作手机APP需要学习什么语言，安装什么软件？

### ISSUE THREAD

**Issue by 19373054** [buaa21/summer2020#44]
对于软件制作0基础，只会c语言，所以对于本次作业毫无头绪，希望高颜值小哥们介绍一下手机APP制作，所需要学习的东西

**Comment by havesomecolo** [comment]
安卓一般用java。 要善用网络资源，比方上mooc搜一下就有很多教app开发的课程：https://www.icourse163.org/course/HNJDZY-1206305815

**Comment by orixing** [comment]
ios系统的app开发可以用Xcode，语言是Swift或ObjectiveC
Java是Android开发的官方语言，被Android Studio所支持。可以考虑自学java语言和Android Studio
