### ISSUE TITLE
安卓平台手机APP如何实现不同设备间的数据共享

### ISSUE THREAD

**Issue by Cirtl** [buaa21/summer2020#46]
希望在一个设备中输入数据然后其他所有安装此APP的设备均可得到此数据。需要联网吗，最后答辩又该如何演示？

**Comment by crclz** [comment]
需要使用服务端+数据库。
最广泛、经典的架构是B/S架构：browser - server。其内部的组成架构是这样的：浏览器 - 服务端 - 数据库。

现在的手机app（qq wx 贴吧），采用的是上述架构的变种（把浏览器换成手机app）：手机app - 服务端 - 数据库。

如果你没有制作交互式网站的基础，建议先学习制作交互式网站，掌握这些基础。

如果你想要在没有这些基础之前开发手机app，那么就应该选择开发那些不需要联网使用的app，例如一个待办清单管理工具、一个提醒工具、一个图片处理软件……

**Comment by Cirtl** [comment]
谢谢

**Comment by havesomecolo** [comment]
到阿里云或者别的云平台租用数据库，然后app都连接这个数据库进行数据存储和查询。不过这样成本比较高

**Comment by Cirtl** [comment]
请问如果租用数据库的话是否还需要搭建B/S架构

**Comment by crclz** [comment]
@Cirtl 你可以租用阿里云10元一个月的服务器，然后在上面安装数据库。然后就用Android程序直接链接数据库，就不用C/S架构了。但这样你的应用程序不安全，但是在小学期这个安全问题不是特别大。

另外你可以用自己的电脑搭建数据库，然后手机链接内网数据库。

**Comment by Cirtl** [comment]
谢谢
