### ISSUE TITLE
我想让窗口接收键盘消息之后，在窗口上画个方块。可为啥我一按键盘它就闪退了呢？   

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#47]
我把画方块的指令放在WP_PAINT下面就会正常画方块
我把画方块的指令放在WP_KEYDOWN下面随便按一个键就会自动退出。
![image](https://user-images.githubusercontent.com/70250586/91413751-273c2d80-e87e-11ea-987f-c93a8e269a92.png)

`#include "eluosihead.h"
/* This is where all the input to the window goes to */

LRESULT CALLBACK WndProc(HWND hwnd, UINT Message, WPARAM wParam, LPARAM lParam) //参数分别为句柄、消息、按键标识符、lParam同前 
{
	PAINTSTRUCT pt;
	HDC hDC;
	switch(Message) 
	{
		case WM_CREATE://窗口创建初期只产生一次，用于游戏初始化 
			OnCreate();
			break; 
		
		case WM_TIMER:
			break; 
			
		
		case WM_PAINT://窗口可作用区域的标识 ,画窗口内容 
			hDC=BeginPaint(hwnd,&pt);
			OnPaint(hDC);	
			EndPaint(hwnd,&pt);
			break; 
		/* Upon destruction, tell the main thread to stop */
		
		case WM_KEYDOWN://判断按键内容，做出反应 
			Rectangle(hDC,60,60,100,100); 
			switch(wParam)
			{
				case VK_RETURN: 
				
					OnReturn(hwnd);
					break;
				case VK_LEFT:
					break;
				case VK_RIGHT:
					break;
				case VK_UP:
					break;
				case VK_DOWN:
					break;
				case 65://向左旋转 (A)
					break;
				case 68://向右旋转 (D)
					break; 
				
			}
			 
		 
		case WM_DESTROY: 
			KillTimer(hwnd,DEF_TIMER1);
			PostQuitMessage(0);
			break;
		
		/* All other messages (a lot of them) are processed using default procedures */
		default:
			return DefWindowProc(hwnd, Message, wParam, lParam);
	}
	return 0;
}

/* The 'main' function of Win32 GUI programs: this is where execution starts */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
	WNDCLASSEX wc; /* A properties struct of our window */
	HWND hwnd; /* A 'HANDLE', hence the H, or a pointer to our window */
	MSG msg; /* A temporary location for all messages */

	/* zero out the struct and set the stuff we want to modify */
	memset(&wc,0,sizeof(wc));
	wc.cbSize		 = sizeof(WNDCLASSEX);
	wc.lpfnWndProc	 = WndProc; /* This is where we will send messages to */
	wc.hInstance	 = hInstance;
	wc.hCursor		 = LoadCursor(NULL, IDC_ARROW);
	
	/* White, COLOR_WINDOW is just a #define for a system color, try Ctrl+Clicking it */
	wc.hbrBackground = (HBRUSH)(COLOR_WINDOW);//定义窗口背景颜色 
	wc.lpszClassName = "WindowClass";
	wc.hIcon		 = LoadIcon(NULL, IDI_APPLICATION); /* 底下任务栏中的图标*/
	wc.hIconSm		 = LoadIcon(NULL, IDI_APPLICATION); /* 打开页面条左上角的小图标 */

	if(!RegisterClassEx(&wc)) {
		MessageBox(NULL, "Window Registration Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
		return 0;
	}

	hwnd = CreateWindowEx(WS_EX_CLIENTEDGE,"WindowClass","俄罗斯方块",WS_VISIBLE|WS_OVERLAPPEDWINDOW,
		100, /* x */
		100, /* y */
		320, /* width */
		645, /* height */
		NULL,NULL,hInstance,NULL);

	if(hwnd == NULL) {
		MessageBox(NULL, "Window Creation Failed!","Error!",MB_ICONEXCLAMATION|MB_OK);
		return 0;
	}

	/*
		This is the heart of our program where all input is processed and 
		sent to WndProc. Note that GetMessage blocks code flow until it receives something, so
		this loop will not produce unreasonably high CPU usage
	*/
	while(GetMessage(&msg, NULL, 0, 0) > 0) { /* If no error is received... */
		TranslateMessage(&msg); /* Translate key codes to chars if present */
		DispatchMessage(&msg); /* Send it to WndProc */
	}
	return msg.wParam;
}`

**Comment by Fat-Fat-Lee** [comment]
我查了一下说这是WM_KEYDOWN响应有问题。不知道有什么好的解决方法吗？麻烦助教了。

**Comment by buaa21** [comment]
请使用热门的技术来开发桌面app
https://github.com/buaa21/summer2020/blob/master/README.md#%E6%A1%8C%E9%9D%A2%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91
