### ISSUE TITLE
python如何将数据保存到本机

### ISSUE THREAD

**Issue by MissTini** [buaa21/summer2020#48]
用python开发一个exe小游戏，想把历史最高分等记录保存到本机，使下次打开时前几次的数据能够被读取，该怎么办呀

**Comment by crclz** [comment]
需要有存储数据的手段。
1. 将需要保存的数据放入一个对象里面（常常使用dict）
2. 将dict转换为json字符串。
3. 将json字符串保存在文件

读取时：
1. 从文件读取json字符串
2. 将json字符串反序列化成对象

你可以搜索以下，python读取、保存json

**Comment by MissTini** [comment]
学到了，谢谢！

**Comment by IAmParasite** [comment]
https://www.liaoxuefeng.com/wiki/1016959663602400/1017606916795776
可以看一下这个教程，希望对你有帮助
