### ISSUE TITLE
kotlin中在Activity中创建Fragment后getActivity为null

### ISSUE THREAD

**Issue by Bazoka13** [buaa21/summer2020#50]
我在MenuActivity.kt中编写函数使得按下Button时可以创建新的problemFragment（val one）并replace，但是当我调用 one.activity时返回了null，val创建后需要手动onAttach吗，我尝试使用one.onAttach(Menuactivity)（虽然弃用了），会报错为"Classifier 'MenuActivity' does not have a companion object, and thus must be initialized here"
```kotlin
private fun initView() {
        val one = ProblemFragment()
        if(one.activity!=null){
            val two = TutorialFragment()
            supportFragmentManager.beginTransaction().replace(R.id.index_content_fl,two).commit()
        } else supportFragmentManager.beginTransaction().replace(R.id.index_content_fl,one).commit()
    }
```
if 的两种显示结果用来判断是否为null
[https://github.com/Bazoka13/summer2020-work-/tree/master/OJ4thinhand/app/src/main/java/com/example/oj4thinhand](仓库)关于MenuActivity和ProblemFragment的文件在仓库里

**Comment by buaa21** [comment]
抱歉，可能助教们都不太会kotlin
