### ISSUE TITLE
关于pygame库和pymunk库的一个问题

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#51]
我想用python制作一个篮球类型的小游戏。用pygame库插入了一个图片，想对这个图片用pymunk库，方便后续物理引擎的处理（球体的碰撞以及球每个时刻的速度计算等）。请问可以做到吗？还是只能使用pymunk库自带的画图功能？

**Comment by orixing** [comment]
需要用pymunk对pygame的球体进行一个“建模”的操作，然后用pymunk的模型控制图片的移动。
如果我没记错pymunk和pygame的坐标是不一样的，需要进行转换

**Comment by hrx20000209** [comment]
是先用pygame.image.load导入图片之后，用pymunk建立物理模型，再对这个图片用spcae.debug_draw画出来吗？

**Comment by orixing** [comment]
我个人觉得也可以尝试将物理模型和图片分开，通过物理模型的运动来控制pygame图片运动

**Comment by hrx20000209** [comment]
想请问一下具体的操作，网上找到的pymunk的代码和注释都很杂乱

**Comment by orixing** [comment]
http://www.pymunk.org/en/latest/examples.html
官方文档给出的实例
http://www.pymunk.org/en/latest/pymunk.html
官方文档的API
我个人考虑的实现方法就是用pymunk建模后，通过模型的移动参数控制图片移动
https://blog.csdn.net/marble_xu/article/details/102079236

**Comment by hrx20000209** [comment]
那最后建立好了模型之后，物理模型可以跟图片一起用键盘输入进行控制吗？

**Comment by orixing** [comment]
这就不晓得了，我貌似没听说过控制pymunk模型的方法，但应该是可以实现的，建议去翻翻官方文档
