### ISSUE TITLE
Python单文件与多文件问题

### ISSUE THREAD

**Issue by buaa-gavin** [buaa21/summer2020#52]
如题
看了不少项目，有单文件的也有多文件的，请问在什么情况下需要多个文件呢？
（本人做的小游戏）

**Comment by buaa21** [comment]
我没用过pygame。但是一般的开发python，不可能把所有函数都放在一个文件里，所以常常把函数放在不同的文件里面，来方便管理。至于pygame，可以听听其他助教怎么说

**Comment by songoku1994** [comment]
我的理解是你可以把不同组件写在不同py文件里，然后有个主py用来控制整个游戏的运行

**Comment by orixing** [comment]
个人建议每一个主要功能作为一个文件，全部功能全部写在一个文件里很不利于后续开发和添加新内容
