### ISSUE TITLE
Visual stdio community下载一直出现错误，让检查网络连接，但是网络明明没有问题。

### ISSUE THREAD

**Issue by Fat-Fat-Lee** [buaa21/summer2020#53]
![image](https://user-images.githubusercontent.com/70250586/91422439-bef34900-e889-11ea-9b10-045c6188f8c6.png)

**Comment by crclz** [comment]
你去下个professional的安装包运行试试，或者再重启。如果还是有问题，就去找一下下载离线安装包的方法。
