### ISSUE TITLE
为什么VS2019在这里调试都过不了？

### ISSUE THREAD

**Issue by async222** [buaa21/summer2020#54]
![B}(A64`Q5}H3Z)NLKTV%V~Q(1)](https://user-images.githubusercontent.com/70182966/91423585-4324dc80-e848-11ea-8b33-f08dcb852fb5.png)

**Comment by buaa21** [comment]
不建议使用原生WindowsAPI开发桌面app
参考
https://github.com/buaa21/summer2020#%E6%A1%8C%E9%9D%A2%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91

**Comment by buaa21** [comment]
当前问题的可能原因是没有main函数

**Comment by async222** [comment]
谢谢老师，问题解决了，因为开始创建的工程属性是控制台而不是窗口，改过来就可以运行了。
