### ISSUE TITLE
如何快速学习面向对象

### ISSUE THREAD

**Issue by dwr2001** [buaa21/summer2020#55]
在我的游戏中，玩家主体是一个类，具体的单人或双人玩家就是具体对象，可是在pygame键盘事件上他们的代码一样，也就是要按下的键是一样的，如何改变这种现状？我想玩家1用上下左右键，玩家2用wsad键，玩家3用5213键，这是要重载吗

**Comment by Withinlover** [comment]
先写一个玩家类，比如Player，存放三个玩家公共的属性

然后针对每个玩家，在单独写一个游戏角色类来继承这个类
比如Mario，Luigi。在初始化/声明的时候可以继承Player
然后就可以单独写移动操作了吧（

<del>以上全部口胡</del>
<del>我正打算这么写所以我也不知道行不行得通</del>

然后就可以写了（只有3个玩家应该可以这么干吧

**Comment by Matrix53** [comment]
我觉得可以在类中多加一个实例属性，当这个实例属性为x时，执行x的动作

**Comment by orixing** [comment]
感觉楼上的方法可以，类中加一个属性表示玩家编号，移动方法根据不同编号做不同处理

**Comment by dwr2001** [comment]
那就是说在一个类中写if else句判断x的实例属性再来选择性的操作上下左右键，wsad键，5213键吗？

**Comment by orixing** [comment]
对

**Comment by dwr2001** [comment]
哦那我懂了，多谢！

**Comment by orixing** [comment]
比如监听到w按键，那么只有x=2的对象进行移动

**Comment by dwr2001** [comment]
也行，我想的是存在x =2就是存在第二玩家，才进入w等按键的监听中，否则不监听
