### ISSUE TITLE
半成品评审

### ISSUE THREAD

**Issue by huahuaxiaomuzhu** [buaa21/summer2020#57]
~~链接https://www.bilibili.com/video/BV1Df4y1Q7YC/~~
https://www.bilibili.com/video/BV1AC4y1b7KM/ （更新的版本）

待完善的功能：
1.历史胜负统计
2.PVE和PVP模式中的“提示”功能，即让AI代替落子一回合（已实现）
3.一些音效（如果有必要的话）
4.回合限制时间

**Comment by orixing** [comment]
界面可以进一步改善，比如悔棋，开始等设计成按钮。以及内容方面略显单薄，可以考虑在ai方面继续努力或者添加新的游戏要素

**Comment by huahuaxiaomuzhu** [comment]
稿件已经更新，实现了按钮的开始界面以及按钮形式的悔棋功能，同时保留了拖拽形式的悔棋功能

**Comment by PineZhuo** [comment]
棋盘的格数可以再多一些。以及卡顿问题可能需要着重解决

**Comment by huahuaxiaomuzhu** [comment]
https://www.bilibili.com/video/BV1AC4y1b7KM/
更新的版本

**Comment by Zehong3351** [comment]
我觉得人下棋的时候，如果能加上时间限制，应该更好一些。

**Comment by songyou21** [comment]
四子棋的规则（玩法）是什么？在首页加点文字说明一下（20个字以内）。
首页的三个菜单（缩写的英文）是什么意思？
功能还比较简单，UI还比较简陋。

**Comment by huahuaxiaomuzhu** [comment]
https://www.bilibili.com/video/BV1jZ4y1T7sV
更新的版本
