### ISSUE TITLE
C语言加载的图片不显示的问题

### ISSUE THREAD

**Issue by XuanMing66** [buaa21/summer2020#58]
求问：采用visual studio，用C语言在显示控制台加载一张图片，方式为：
IMAGE 123;
loadimage(&123, L"123.jpg", 30, 15);
putimage(0, 0, &123);

但是图片没能成功显示，本该是图片的地方变成了黑屏，请问该咋整

**Comment by PineZhuo** [comment]
图片路径是否正确？如果相对路径无法判断的话，建议使用绝对路径试试。
