### ISSUE TITLE
关于python编程的project和file的问题

### ISSUE THREAD

**Issue by TheSaint-LazareStation** [buaa21/summer2020#59]
请问在写程序的过程中应该怎样将一个文件分成一个project下的多个文件呢？具体一点说，是不是将一个程序中除了主函数的每个函数分别置于不同的.py文件中（都在一个project里）就可以了呢？

**Comment by orixing** [comment]
不知道你要的是不是这个https://www.runoob.com/python/python-modules.html
建议可以按照功能将程序拆分成多个文件，利于编写与后期维护

**Comment by crclz** [comment]
当你感觉一个文件里面函数太多了，就应该拆分这个文件
