### ISSUE TITLE
写这个作业用的工具有限制吗

### ISSUE THREAD

**Issue by ssharco** [buaa21/summer2020#6]
以及用的语言一定是c++吗（因为公告里好像没写别的）

**Comment by havesomecolo** [comment]
什么语言都行的。27号还教python呢

**Comment by ssharco** [comment]
> 什么语言都行的。27号还教python呢

啊太好了~~
谢谢老师~

**Comment by Withinlover** [comment]
能用QT嘛.......然后其他的开源框架/代码能不能直接拿来用

**Comment by ssharco** [comment]
> 能用QT嘛.......然后其他的开源框架/代码能不能直接拿来用

是不是说，可以用工具，但不能用现成的框架

**Comment by Withinlover** [comment]
> > 能用QT嘛.......然后其他的开源框架/代码能不能直接拿来用
> 
> 是不是说，可以用工具，但不能用现成的框架

emmm，可能有误解。我不是助教（
我只是借这个问题多问两句（

**Comment by ssharco** [comment]
> > > 能用QT嘛.......然后其他的开源框架/代码能不能直接拿来用
> > 
> > 
> > 是不是说，可以用工具，但不能用现成的框架
> 
> emmm，可能有误解。我不是助教（
> 我只是借这个问题多问两句（

hh 
还是谢谢你的补充~

**Comment by crclz** [comment]
@ssharco 我代替老师来答一波吧。框架是可以用的，例如Web的Spring Asp.Net Django, 例如桌面app的Winform WPF QT。但是，请注意，不能用模板（例如wordpress），例如不能基于wordpress写几个插件，就说整个网站是你自己写的。

**Comment by ssharco** [comment]
> @ssharco 我代替老师来答一波吧。框架是可以用的，例如Web的Spring Asp.Net Django, 例如桌面app的Winform WPF QT。但是，请注意，不能用模板（例如wordpress），例如不能基于wordpress写几个插件，就说整个网站是你自己写的。

啊这样 我想我应该 懂了
谢谢老师~~

**Comment by crclz** [comment]
@ssharco [如何辨别如何辨别用户是同学/助教和老师](https://github.com/buaa21/summer2020/blob/master/%E5%8A%A9%E6%95%99%E6%98%B5%E7%A7%B0%E5%AF%B9%E5%BA%94%E8%A1%A8.md#%E5%A6%82%E4%BD%95%E8%BE%A8%E5%88%AB%E7%94%A8%E6%88%B7%E6%98%AF%E5%90%8C%E5%AD%A6%E5%8A%A9%E6%95%99%E5%92%8C%E8%80%81%E5%B8%88)

**Comment by ssharco** [comment]
> @ssharco [如何辨别如何辨别用户是同学/助教和老师](https://github.com/buaa21/summer2020/blob/master/%E5%8A%A9%E6%95%99%E6%98%B5%E7%A7%B0%E5%AF%B9%E5%BA%94%E8%A1%A8.md#%E5%A6%82%E4%BD%95%E8%BE%A8%E5%88%AB%E7%94%A8%E6%88%B7%E6%98%AF%E5%90%8C%E5%AD%A6%E5%8A%A9%E6%95%99%E5%92%8C%E8%80%81%E5%B8%88)

谢谢热心的助教老师~~~
QWQ
