### ISSUE TITLE
Java静态对象数组初始化后所有存储对象都相同了，请问如何解决

### ISSUE THREAD

**Issue by cynic-1** [buaa21/summer2020#60]
/**
 * 由于代码位于不同文件，所以仅附上部分代码
 */
private final static  Player [] playersArray = {new Player("A"),
            new Player("B"), new Player("C"), new Player("D")};

public static Player[] getPlayersArray() {
        return playersArray;
    }

 public static void main(String[] args) {
        Manager.init();
        Iterator it = all.iterator();
        int i = 1;
        System.out.println(getPlayersArray()[0]);
        System.out.println(getPlayersArray()[1]);
        System.out.println(getPlayersArray()[2]);
        System.out.println(getPlayersArray()[3]);
        while(it.hasNext()) {
            System.out.println((Mahjong)it.next() + " " + i++);
        }
        Manager.startGame();

    }
/*
 * result:
 * player D: 
 * player D: 
 * player D: 
 * player D: 
 */

**Comment by PineZhuo** [comment]
不是很清楚是不是别的地方有问题，按照你的代码，我大致复现了一下,输出是没有问题的
```java
class Player
{
	public String name = null;
	public Player(String name) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
}
public class Oj_exam_1_1 {
	private final static Player [] playersArray = {new Player("A"),
			new Player("B"), new Player("C"), new Player("D")};
	public static Player[] getPlayersArray() {
		return playersArray;
	}
	public static void main(String[] args) {
		System.out.println(getPlayersArray()[0].getName());
		System.out.println(getPlayersArray()[1].getName());
		System.out.println(getPlayersArray()[2].getName());
		System.out.println(getPlayersArray()[3].getName());
	}
}
```
输出：
A
B
C
D

**Comment by cynic-1** [comment]
对，我也觉得很奇怪，看上去代码没啥问题

**Comment by PineZhuo** [comment]
如果可以的话，贴一下Player类的代码吧

**Comment by cynic-1** [comment]
就是有点长
public class Player {
    private static String name = null;
    private boolean isDealer = false; // 是否是“庄家”
    private boolean isGone = false;
    private boolean isRobot = true;
    private static Suit withoutSuit = Suit.CHARACTER;
    // A lot of insertion and removal
    private static LinkedList<Mahjong> mahjongsInHand = new LinkedList<>();
    private static ArrayList<Mahjong> mahjongsDiscarded = new ArrayList<>();
    private Mahjong currentDraw = null;
    private Mahjong currentDiscard = null;
    /**
     *  When you peng or gang, the mahjongs you used to
     *  hold will be removed from MahjongInHand, and be
     *  added to pengMahjongs or gangMahjongs.
     */
    private static ArrayList<PengMahjong> pengMahjongs = new ArrayList<>();
    private static ArrayList<GangMahjong> gangMahjongs = new ArrayList<>();

    public Player(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
    public void setDealer(boolean isdealer) {
        this.isDealer = isdealer;
    }

    public boolean getDealer() {
        return this.isDealer;
    }

    public void setGone(boolean isgone) {
        this.isGone = isgone;
    }

    public boolean getGone() {
        return isGone;
    }

    public void setRobot(boolean isRobot) {
        this.isRobot = isRobot;
    }

    public boolean getRobot() {
        return isRobot;
    }

    public void setWithoutSuit(Suit withoutSuit) {
        this.withoutSuit = withoutSuit;
    }

    public List getPengMahjongs() {
        return pengMahjongs;
    }

    public List getGangMahjongs() {
        return gangMahjongs;
    }

    public List getMahjongInHand() {
        return mahjongsInHand;
    }

    public List getMahjongDiscarded() {
        return mahjongsDiscarded;
    }

    public void setCurrentDiscard(Mahjong mahjong) {
        currentDiscard = mahjong;
    }

    public Mahjong getCurrentDiscard() {
        return currentDiscard;
    }

    public void drawMahjong(Iterator it) {
        if (! isEnd()) {
            this.currentDraw = (Mahjong)it.next();
        } else {
            //Manager.blackEnd();
        }
        mahjongsInHand.add(currentDraw);
        System.out.println(this + "draw " + mahjongsInHand.size());

    }

    /**
     * Ask the player to choose one Mahjong to discard,
     * then remove the mahjong from mahjongInHand and set it currentDiscard.
     *
     * If the player's mahjongInHand includes withoutSuit(hasWithout),
     * then he cannot discard other suits' mahjong.
     *
     * If there is nobody peng, gang or hu,
     * then the currentDiscarded will be put into mahjongsdiscarded
     */
    public void discardMahjong() {
        int numChooseDiscard = askDiscard(this);
        switch (numChooseDiscard) {
            case 1:
                // set the currentDiscard and remove the mahjong from MahjongInHand in one line
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(0));
                break;
            case 2:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(1));
                break;
            case 3:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(2));
                break;
            case 4:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(3));
                break;
            case 5:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(4));
                break;
            case 6:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(5));
                break;
            case 7:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(6));
                break;
            case 8:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(7));
                break;
            case 9:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(8));
                break;
            case 10:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(9));
                break;
            case 11:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(10));
                break;
            case 12:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(11));
                break;
            case 13:
                this.setCurrentDiscard((Mahjong) (this.getMahjongInHand()).remove(12));
                break;
        }
        //if (askForSkill(this.currentDiscard) != null) return;
        this.mahjongsDiscarded.add(this.currentDiscard);
    }

    public void chooseWithout() {
        //if (player.isRobot) chooseWithoutAlgorithm();
        System.out.println("enter chooseWithout");
        int numChooseWithout = askChooseWithout(this);
        switch(numChooseWithout) {
            case 1:
                this.setWithoutSuit(Suit.CHARACTER);
                break;
            case 2:
                this.setWithoutSuit(Suit.BAMBOO);
                break;
            case 3:
                this.setWithoutSuit(Suit.DOT);
                break;
            default: System.err.println("method askChooseWithout has bugs");
        }
}
    public static boolean hasWithout() {
        Iterator it = mahjongsInHand.iterator();
        while(it.hasNext()) {
            if (((Mahjong)it.next()).getSuit() == withoutSuit) {
                return true;
            }
        }
        return false;
    }

    public void run() {
        System.out.println("------new round------");
        this.drawMahjong(getIterator());
        this.discardMahjong();
    }

    public String toString() {
        return "player " +  name + ": ";
    }

    public void showHand() {
        Iterator it = mahjongsInHand.iterator();
        while(it.hasNext()) {
            System.out.print(it.next() + " ");
        }
    }
}

**Comment by PineZhuo** [comment]
Player类的name属性不可以用static，因为如果用了static，它就是一个类变量，是这个类中所有的对象所共有，且共同操作的一个属性，也就是说，所有的Player对象都可以对它进行修改，你可以理解为它是所有Player类的对象的一个“全局变量”

**Comment by PineZhuo** [comment]
一般什么时候用static，比如说你需要计算所有玩家的数量，设置一个static属性，每new一个玩家，数量++。而name是每个玩家自己独有的属性，因此不可以static

**Comment by cynic-1** [comment]
哦哦哦对我确实概念有点混了，麻烦您了
