### ISSUE TITLE
OpenCV 处理图像的一般流程

### ISSUE THREAD

**Issue by Alex-Mufeng** [buaa21/summer2020#63]
我今天看了很多opencv-python的程序（车牌识别、掩模、人脸识别等），他们基本都用到了高斯模糊、膨胀腐蚀等图像操作，但是我看到的资料（官方文档）也没讲为什么使用他们。我想要深入学习下opencv 有没有合适的教程或者资料获取方式呢。一般了解一个全新的python库，我应该如何快速上手呢？

**Comment by crclz** [comment]
1. opencv对于小学期来说，技术风险较高。建议让作品更加偏向业务
2. opencv我不了解，但是了解一个python库的途径一般是看官方教程、动手写、遇到问题查文档和博客
3. 对于xx识别技术，现在最好的解决方案应该是神经网络，这个也需要大量相关的知识。具体的学习请见这个讲座 https://www.bilibili.com/video/BV1rD4y1U7mr 北航自控协会请了2位大佬来讲NLP和CV的科研，里面提到了一些入门课程

**Comment by PineZhuo** [comment]
如果想要了解为什么要使用xx操作，以及计算机视觉的更深层次内容，可以学习斯坦福大学的CS231n课程，b站上有大佬翻译的[视频](https://www.bilibili.com/video/av86713932)，知乎上有大佬翻译的[官方授权笔记](https://zhuanlan.zhihu.com/p/21930884)，这是[官方配套练习](http://cs231n.stanford.edu/syllabus.html)。当然，非常不建议小学期学这个，感兴趣的话可以在小学期结束之后学习。
