### ISSUE TITLE
pycharm中的unresolved reference警告

### ISSUE THREAD

**Issue by zyqzyq007** [buaa21/summer2020#65]
在pathon和pygame库正常写代码时，总是显示unresolved reference，根据网络上提示的操作也没有消除unresolved reference，如何才能消除unresolved reference?

**Comment by PineZhuo** [comment]
消除unresolved reference的方法有很多，而且每个人的情况不一定一样，一般网上能搜到的方法都是解决方法之一，所以根据能搜索到的所有方法一个一个试吧（在以后的学习中，会有非常多非常多这种经历的）
