### ISSUE TITLE
C语言 getch()读取操作时的缓冲区问题

### ISSUE THREAD

**Issue by y573082640** [buaa21/summer2020#66]
助教さん，一次循环中，用C的getch()函数读取键盘方向键操作后，如何清除因多次按方向键而残留的操作呢（防止下一次循环读取这些操作）？

**Comment by orixing** [comment]
尝试清空输入缓冲区试试？ fflush(stdin)或 rewind(stdin)

**Comment by crclz** [comment]
使用`kbhit`来检测键盘。https://www.cnblogs.com/hookjc/p/13182951.html

**Comment by y573082640** [comment]
谢谢助教，已解决
