### ISSUE TITLE
python PIL.image 怎样通过 numpy.array()  转换成 矩阵数据

### ISSUE THREAD

**Issue by puffyyy** [buaa21/summer2020#67]
#### 代码
```
from PIL import Image
from numpy import array

im = Image.open('G:\\Code\\minesweeping\\test\\pika.jpg')
width = im.size[0]
height = im.size[1]
im = im.convert('RGB')

# a
 arr = array(im) 
# b
'''
arr = []
for x in range(width):
    for y in range(height):
        r, g, b = im.getpixel((x,y))
        rgb = (r, g, b)
        arr.append(rgb)
'''
# c
print(arr)
```

为什么 ab段代码 能实现bc段的功能  `numpy.array()`怎么读取的`image` 的数据

附调试时 `im` 的属性
![11645f3447d345ad23ca824c1bb3c5e](https://user-images.githubusercontent.com/63792704/91445104-418b0100-e8a8-11ea-936f-3eea97901a3b.png)
![cd348b481546fb361a65c61a0aabe8a](https://user-images.githubusercontent.com/63792704/91444834-e35e1e00-e8a7-11ea-97b4-3c0a41bebef7.png)

感谢答疑！

**Comment by buaa21** [comment]
这是1.16版本添加的功能。http://effbot.org/zone/pil-changes-116.htm
