### ISSUE TITLE
easyX透明贴图技术

### ISSUE THREAD

**Issue by DYY-Drummer** [buaa21/summer2020#68]
想要找做透明贴图用的（游戏物品）那种图片素材，就是一个原图加一个黑白背景图片掩码的一对图片，上哪去找呀？

 或者说有什么办法能把普通的网页图片做成虚背景的游戏贴图直接使用吗

**Comment by orixing** [comment]
一般的图片素材网站都是透明背景，网上找一找就有（去年我用的现在貌似找不到了），实在不行可以自己抠图，

**Comment by crclz** [comment]
重复的问题 #30
