### ISSUE TITLE
用c写小游戏用其它语言做界面

### ISSUE THREAD

**Issue by young-hs** [buaa21/summer2020#70]
想写一个有用户界面的棋类小游戏，现在只会C语言，能否用C写游戏，自学一点其他语言做UI呢？如果可以，怎么把二者连接起来呢？

**Comment by crclz** [comment]
“连接”的方法倒是有，c#可以P/Invoke。但是极度不推荐！！！！！！！
建议整个程序使用一种语言来做。建议使用pygame或者winform来做。
https://github.com/buaa21/summer2020#%E5%BC%80%E5%8F%91%E6%8C%87%E5%BC%95
