### ISSUE TITLE
Eclipse安装非常非常缓慢？

### ISSUE THREAD

**Issue by aurora-cccyr** [buaa21/summer2020#72]
官网下载了Eclipse IDE for Java EE Developers，安装奇慢无比，跟死了一样，安装一个小时进度大概60%，请问这正常吗，是网速的问题还是配置或者别的什么问题呢（抓狂😭

**Comment by PineZhuo** [comment]
一般不是网速的问题，可以试试在在线安装插件的Install窗口，将Contact all update sites during install to find required software 前面的选项去掉。

**Comment by cynic-1** [comment]
试试国内镜像。比如阿里云、清华云

**Comment by orixing** [comment]
如果我没记错，可能你会在99%卡很久lol

**Comment by Zehong3351** [comment]
可以选用国内的镜像，安装的时候不要全部都勾选

**Comment by songoku1994** [comment]
试试看清华的镜像
