### ISSUE TITLE
请问一下制作小游戏，pygame和pyglet库有什么区别？

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#74]
如题，想要制作一个小游戏，会发生球体的碰撞，需要用到pymunk库建立物理模型，同时用pygame或者pyglet库将物理模型变成图片。
pymunk的资料有限，在b站上找到了pymunk与pyglet一起使用的例子。而pymunk与pygame的例子都比较杂乱，可参考的较少。
想请问一下二者之间的区别大吗？

**Comment by Zehong3351** [comment]
如果你从不打算在游戏本身中绘制任何矢量图形或图元，并且坚持从磁盘加载图像，则Pyglet是很好的(对于2D游戏)。它也更方便快捷，因为不需要编写自己的游戏循环，不用担心速度，时间和响应速度。 但是，如果你是想即时生成图形，然后将它们保存为变量或文件，则pyglet变得相当复杂，因为需要开始使用低级别的OpenGL函数。
我给你找了一个讲解pymunk的应用案例，你看一下，感觉应该对你有帮助。https://blog.csdn.net/qq_37963615/article/details/99327611

**Comment by orixing** [comment]
pymunk官方文档有很详细的例子http://www.pymunk.org/en/latest/
pyglet和pygame都比较适合初学者做游戏，都非常好上手

**Comment by hrx20000209** [comment]
我看过CDSN上的那个教程，但是它里面的这一行代码：
`
# 在pygame上创建画板
draw_options = pymunk.pygame_util.DrawOptions(screen)
`
我用pycharm输入之后显示的是这样的：
`
Traceback (most recent call last):
  File "C:/pycharm/Code/main.py", line 64, in <module>
    sys.exit(main())
  File "C:/pycharm/Code/main.py", line 40, in main
    draw_options = pymunk.pygame_util.DrawOptions(screen)
AttributeError: module 'pymunk' has no attribute 'pygame_util'
`
结果无法运行

**Comment by orixing** [comment]
貌似需要单独安装？
http://www.pymunk.org/en/latest/pymunk.pyglet_util.html
http://www.pymunk.org/en/latest/pymunk.pygame_util.html
大概是提供对于pygame或pyglet的支持

**Comment by hrx20000209** [comment]
解决了，这个要单独调用pymunk.pygame_util库，应该是跟pymunk库一起安装好了的，谢谢！
