### ISSUE TITLE
python的pygame模块键盘事件监控

### ISSUE THREAD

**Issue by heartworm1** [buaa21/summer2020#75]
pygame可以同时监控多个键盘同时按下的事件吗

**Comment by PineZhuo** [comment]
所谓的“同时按下”，对于计算机来说也有时间差的，因此，如果需要控制“同时按下多个键才能触发某一功能”，可以保存一下几次按下的值，并进行判断。（然而这并不能保证他们是在很短的时间差内相继被按下，所以可以听听其他比较熟悉这方面技术的助教怎么说）

**Comment by orixing** [comment]
pygame.key.get_pressed()
get the state of all keyboard buttons
get_pressed() -> bools
Returns a sequence of boolean values representing the state of every key on the keyboard. Use the key constant values to index the array. A True value means the that button is pressed.

https://www.pygame.org/docs/ref/key.html#pygame.key.get_pressed

**Comment by Zehong3351** [comment]
推荐看看这篇博文
https://blog.csdn.net/u011367482/article/details/106173994?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~first_rank_v2~rank_v25-11-106173994.nonecase&utm_term=python%20%E6%8C%89%E9%94%AE%E7%9B%91%E5%90%AC%E5%A4%9A%E4%B8%AA%E6%8C%89%E9%94%AE%E5%90%8C%E6%97%B6%E6%8C%89%E4%B8%8B
