### ISSUE TITLE
关于Python多文件调用

### ISSUE THREAD

**Issue by longzhenren** [buaa21/summer2020#76]
rt
现在我有一个Main.py 用来作为主程序启动入口，在Main.py里仅有一个主函数用于输出欢迎界面和菜单 并根据输入判断启动哪个模块
所有的系统方法和自定义方法分别在两个py文件里，以import形式作为库调用，这两个没有主函数
而各个可以启动的模块分别在不同的.py文件里，都有各自的主函数
那么问题来了 怎么用Main.py启动其他的模块呢？
把主函数写在if __name__ == "__main__":下和写在def mian():下并用或不用if __name__ == "__main__"都有无法正确启动的模块

**Comment by PineZhuo** [comment]
可以启动的模块指的是程序里的某一个功能模块吗？如果是的话，不需要给他们各自安排主函数，封装一些类，把这些功能写在类中，在主函数里新建对象来调用相应功能即可

**Comment by IAmParasite** [comment]
可以在.py里面写一些类(函数)，不需要main函数，然后通过主函数import调用即可
主函数里面主要写一些业务逻辑
