### ISSUE TITLE
c和c++可以混用吗？

### ISSUE THREAD

**Issue by xingzhenyu21** [buaa21/summer2020#77]
如题

**Comment by PineZhuo** [comment]
如果要使用到面向对象，那么C是不可以使用的。如果仅仅是面向过程，C和C++有极高的相似性，大部分情况下都是可以混用的

**Comment by PineZhuo** [comment]
C++有更多的库和更多的用法，所以如果在.cpp中使用了C语言，那么大多数情况下是ok的。
