### ISSUE TITLE
python使用mysql数据库的情况下，能打包成exe在其他电脑正常运行吗？

### ISSUE THREAD

**Issue by SEchen76** [buaa21/summer2020#79]
因为我本地存储的数据在mysql的文件夹内，和源代码不在一个文件夹

**Comment by PineZhuo** [comment]
那么你可能需要把mysql部署到服务器上

**Comment by IAmParasite** [comment]
可以利用Python创建SQLite数据库，和源代码存在一起
参考一下链接：https://www.liaoxuefeng.com/wiki/1016959663602400/1017801397501728

**Comment by Zehong3351** [comment]
除非其他电脑已经有mysql，且创建好了相同名称的表并导入了数据。你可以将数据库的建表导入数据的指令写好，到时候直接在其他电脑中的mysql中运行就好了啊。

**Comment by Roycent** [comment]
如果是本地软件，不需要用户间交互数据的，的确可以使用本地的SQLite。如果只有比较简单的类似存档的东西，甚至可以只使用文本文档或者自定文件格式来存储数据。
