### ISSUE TITLE
python开发代码量

### ISSUE THREAD

**Issue by heartworm1** [buaa21/summer2020#8]
请问使用python开发的代码量也要达到1000行以上吗

**Comment by laneseal** [comment]
Python 程序有其代码量少的优势，如果用的好，项目完成情况好，也未必非要1000行吧，请其他老师补充说明。

**Comment by havesomecolo** [comment]
作品完成度高的，代码量可以酌情放宽

**Comment by orixing** [comment]
有效代码量高，内容丰富在最后评价的时候肯定会更有优势，只要能完整实现，功能/内容足够丰富即可
