### ISSUE TITLE
c语言，vs，怎么用多个源文件写程序

### ISSUE THREAD

**Issue by Rander-sun** [buaa21/summer2020#80]
以前学习c语言的时候都是把程序写在一个文件里，老师说最好把程序写成多个源文件，请问应该用vs怎样操作？怎样编译？怎样一起运行？

**Comment by IAmParasite** [comment]
大型软件肯定是多个人文件写的，你可以编写.h头文件，在头部引入即可

**Comment by PineZhuo** [comment]
参考一下这两篇教程
https://zhidao.baidu.com/question/380986064.html
https://jingyan.baidu.com/article/77b8dc7fe591076175eab64b.html

**Comment by Rander-sun** [comment]
是只要把源文件放到一个文件夹里，编译/运行的时候就可以直接一起编译/运行吗？

**Comment by PineZhuo** [comment]
编译并运行main函数所在的文件即可
