### ISSUE TITLE
关于python程序中调用其他.py文件时的问题

### ISSUE THREAD

**Issue by mengliuchang** [buaa21/summer2020#82]
**文件存储结构如下：**
main.py
source(文件夹)
     tools.py
     setup.py
**代码如下：**
`from source import tools, setup`
报错信息如下：
Traceback (most recent call last):
  File "c:\Users\lenovo\Desktop\SuperMario\main.py", line 3, in <module>
    from source import tools, setup
使用VS code编辑器，求助为什么不能调用

**Comment by PineZhuo** [comment]
可以看看这个教程
https://blog.csdn.net/lwgkzl/article/details/81161985

**Comment by PineZhuo** [comment]
from xxx import yyy用来引用xxx文件里的类yyy

**Comment by crclz** [comment]
我测试了没问题啊。python3.7版本  https://gist.github.com/crclz/6118bc9a74a78f771b5504153199715c

**Comment by SeventhGX** [comment]
试试在控制台运行一下？如果能运行那可能是编译器的原因（至少我在测试的时候没问题）
