### ISSUE TITLE
想做一个app app上传两张图片到服务器,服务器通过python处理两张图片之后返回一张图片到手机后显示

### ISSUE THREAD

**Issue by Costwen** [buaa21/summer2020#83]
处理方法有哪些呢？
现在打算的是用xampp创建一个数据库 然后手机上传的图片存储到数据库中

然后服务器收到图片之后处理两张图片,然后获得一张新的图片，新的图片也存储在数据库中 

然后手机读取数据库的图片的url显示

**Comment by songoku1994** [comment]
如果原来的两张图片不需要保留下的话，其实应该不需要把这两张也存起来，存最后生成的图片就可以了。如果记录里要显示出某张图片的两个来源图，那可以就一起存了。

**Comment by crclz** [comment]
数据库只能由你的服务端服务程序（例如django）来访问。客户端与服务器通信，服务器再与数据库通信。

所以，你的数据库表结构应该是：pictires（id 自增, data: blob）

服务程序（django）应当提供两个接口：
1. 获取图片的接口（ GET /pictures/{id} ）。如果用户访问/pictures/123，那么服务程序就应该首先去数据库里面取id为123的图片，然后将图片返回给用户。
2. 处理图片的接口。( POST /picture-process )，这个接口接收2个图片，然后再调用处理图片的模块进行处理，最后把生成的图片存储到数据库里面，并返回图片的id给客户端。客户端拿到id，就可以访问 /pictures/{id} 来获取处理后的图片。
