### ISSUE TITLE
winform中返回上一个窗体

### ISSUE THREAD

**Issue by Z8232000** [buaa21/summer2020#84]
在返回的过程中只能关闭当前窗体而没有打开上一个窗体
源码是
 private void returntohome_Click(object sender, EventArgs e)
        {
			Form1 F1 = new Form1();
			F1.Show();  
			this.Close();
		}
请问有什么问题

**Comment by songoku1994** [comment]
看看这篇文章有没有帮助：https://blog.csdn.net/cun_king/article/details/107865118

**Comment by crclz** [comment]
[WinformGoBack.zip](https://github.com/buaa21/summer2020/files/5140502/WinformGoBack.zip)
这是示例
