### ISSUE TITLE
unity制作2d小游戏的无尽模式

### ISSUE THREAD

**Issue by suixinsuixin** [buaa21/summer2020#85]
无尽模式地图可以几张来回重复，然后提升速度来提高难度吗？还是纯随机地图比较好？随机的话，是不是应该直接生成一整张接替图。随机生成地图的教程没有看懂……

**Comment by PineZhuo** [comment]
都可以。但是随机地图的趣味性肯定更高，有能力的话，随机地图+加速也会更加好玩。没有看懂可以多花时间去看懂，多看点随机地图的demo什么的。

**Comment by songoku1994** [comment]
从工程量来说一般复杂的方案带来的效果比较好，你可以尽量多加进一些玩法和模式

**Comment by orixing** [comment]
看你自己的能力和精力来选择吧，如果有智能生成地图和敌人的话肯定是更好的
