### ISSUE TITLE
小程序.js修改值失败

### ISSUE THREAD

**Issue by HenryDamon** [buaa21/summer2020#86]
//plans是二维数组，想修改plans[index]中的isday数值
//var istoday = plans[index].istoday; 再修改动态变量istoday也不行
onShow: function () {
    var plans = wx.getStorageSync('plans');
    if (plans) {
      console.log({plans});
      this.setData({plans: plans});
    }
    var that = this;
    plans.forEach(function(item, index){
      if(.....){
        that.setData({[plans[index].istoday] : true});
      } 
  },
})

**Comment by Roycent** [comment]
确认一下在page里面定义并初始化这个plans变量了吗？如果没有定义的话，是无法正常使用setData的

**Comment by HenryDamon** [comment]
初始化了

> 确认一下在page里面定义并初始化这个plans变量了吗？如果没有定义的话，是无法正常使用setData的

**Comment by Roycent** [comment]
初始化的代码能贴一下不，或者来QQ找一下我？plans也不是一个二维数组呀，而是一个一维的自定义对象数组

**Comment by crclz** [comment]
❌ `that.setData({[plans[index].istoday] : true});`
✔ `that.setData({'[plans[index].istoday]' : true});`

**Comment by HenryDamon** [comment]
最终解决方式：
var nowistoday='plans['+index+'].istoday';
that.setData({[nowistoday]: true});
