### ISSUE TITLE
pycharm 调用递归程序栈区溢出

### ISSUE THREAD

**Issue by maxweaker** [buaa21/summer2020#88]
编写解数独的程序时出现“Process finished with exit code -1073741571 (0xC00000FD)”的提示，使用import sys
sys.setrecursionlimit(100000) 方法后仍然没有作用

**Comment by PineZhuo** [comment]
python递归的深度可能被设备的CPU和内存限制，可以尝试一下尾递归

**Comment by PineZhuo** [comment]
并确认递归确实设置了正确的停止条件

**Comment by maxweaker** [comment]
递归函数在三个位置调用自身，请问这样的函数能否改成尾递归

**Comment by songoku1994** [comment]
我觉得可能是终止条件没有设置好

**Comment by maxweaker** [comment]
我用空白的数独测试，设置填写30个数字终止，程序正常，设置35个数字终止时就会栈溢出，所以我认为可能不是终止条件的问题

**Comment by PineZhuo** [comment]
如果有三次调用的话，那我不是很清楚，可以等看看有没有其他助教知道

**Comment by maxweaker** [comment]
已解决 将递归函数改为循环
