### ISSUE TITLE
使用pycharm过程总是弹出这个界面（见图片）

### ISSUE THREAD

**Issue by ljr19231244** [buaa21/summer2020#89]
![_7%9FVQ @LLFY(R 2X7UHLC](https://user-images.githubusercontent.com/70185522/91538260-2670cd80-e94a-11ea-92a1-f9cc5a5db94a.png)
不知道如何解决

**Comment by crclz** [comment]
这个是python的安装程序（或者卸载程序），你试试把python卸载+重装

**Comment by PineZhuo** [comment]
也可以查一下你是否配置了python解释器，File->Setting->Project interpreter查一下

**Comment by ljr19231244** [comment]
python是昨天刚刚跟一位助教一起卸载重新安装的，应该不会出问题吧...

**Comment by PineZhuo** [comment]
如果是空的，可以参考#90里的回答试试

**Comment by ljr19231244** [comment]
![4$%_36{SCHV0907`LC~U3O8](https://user-images.githubusercontent.com/70185522/91540120-e8c17400-e94c-11ea-9344-af00c0bf18e6.png)
解释器配置应该没问题呀

**Comment by PineZhuo** [comment]
运行有问题吗？如果没问题先暂时cancel忽视它吧（捂脸）。或者尝试重新指定安装目录，重新配置环境变量，重启等等
