### ISSUE TITLE
可以用树莓派开发无人机航拍图像识别系统嘛？

### ISSUE THREAD

**Issue by Alex-Mufeng** [buaa21/summer2020#9]
我打算使用树莓派，学习python语言和opencv库完成（2020CADC对地侦察与打击）比赛项目中识别数字部分。这个可以算是人工智能类嘛？如果能做出来，展示形式希望用树莓派展示可以嘛？

**Comment by laneseal** [comment]
不限语言，不限平台，关键在于设计，能完整设计出有一定难度的程序即可。

**Comment by havesomecolo** [comment]
可以的，做好了应该会有不错的效果
