### ISSUE TITLE
pycharm运行时弹出Edit configuration,无法运行，前几次还好好的，突然就这样了

### ISSUE THREAD

**Issue by 19231219lsm** [buaa21/summer2020#90]
pycharm运行时弹出Edit configuration,无法运行，前几次还好好的，突然就这样了

**Comment by PineZhuo** [comment]
可能是你没有配置python解释器，File->Setting->Project interpreter配置你的解释器，例如我的就是python 3.7
![image](https://user-images.githubusercontent.com/42902711/91539233-96cc1e80-e94b-11ea-852d-5e1c20d3669b.png)

**Comment by 19231219lsm** [comment]
谢谢，已经解决
