### ISSUE TITLE
visual studio 2019无法编译

### ISSUE THREAD

**Issue by 19231136** [buaa21/summer2020#91]
一直用dev-c++，为了用easyx新下载的visual studio2019。
在dev-c++通过的程序在这显示图片这个...
用过了网上说的方法，也加了#define _CRT_SECURE_NO_WARNINGS还是没用
![批注 2020-08-28 163306](https://user-images.githubusercontent.com/70182793/91539643-37224300-e94c-11ea-9ae5-9fdf7661347c.jpg)

**Comment by PineZhuo** [comment]
这个教程或许可以参考
https://blog.csdn.net/wwwlyj123321/article/details/79202752

**Comment by PineZhuo** [comment]
它的报错是找不到.exe，证明它已经生成.exe了，下一步要执行exe的时候找不到。应该不是编译的问题。
