### ISSUE TITLE
Wpf 实现richtextbox为空时提示文字  输入后删除

### ISSUE THREAD

**Issue by Ocean326** [buaa21/summer2020#93]
现在已经实现为空时可以在richtextbox中写入提示文字
但这种实现方式写入后的文字需要手动输入

已知Textbox可以通过插入Textblock的方式实现空时有提示文字，输入后自动消失。

但不知怎么应用到Richtextbox上

**Comment by crclz** [comment]
在html里面叫placeholder，在wpf这个东西应该叫Watermark。
https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-add-a-watermark-to-a-textbox

**Comment by Ocean326** [comment]
感谢！已解决√
最后用的是visualbrush当background
 <RichTextBox x:Name="Note" BorderThickness="0"  TextChanged="Note_TextRead">
                <RichTextBox.Background>
                    <VisualBrush  ViewportUnits="Absolute" Viewport="6 3 100 50"  Opacity="0.4"  Stretch="None" AlignmentX="Left" AlignmentY="Top">
                        <VisualBrush.Visual >
                            <TextBlock x:Name="tip" Text="Start here..." FontSize="{Binding Path=FontSize, ElementName=Note}" Margin="10 0 0 0 "/>
                        </VisualBrush.Visual>
                    </VisualBrush>
                </RichTextBox.Background>
            </RichTextBox>
