### ISSUE TITLE
用AndroidStudio进行Java编程的时候，部分压缩包无法打开，是不是必须要下载JDK

### ISSUE THREAD

**Issue by 19373054** [buaa21/summer2020#94]
才下载好AndroidStudio，安装完成，打开软件之后，还需要下载东西，但是它提示我下载的东西无法安装。
是不是电脑里必须下载JDK才能进行Java开发。

**Comment by 19373054** [comment]
![image](https://user-images.githubusercontent.com/70183292/91554279-655e4d80-e961-11ea-9a7b-cae9d90cf77a.png)

**Comment by crclz** [comment]
我没开发过Android app，但是看你这个提示，应该是gradle未安装。你去手动安装一下gradle。jdk也要安装。

**Comment by Roycent** [comment]
首先，安装Android Studio的过程已经在课上大概讲解过并且PPT也发到群里了。
关于JDK：Android Studio会自带一个JDK，不自己手动安装JDK也可以正常使用。但是还是推荐自己手动安装一个JDK并使用。
关于Gradle：理论上来讲这个下载过程是自动的，而且不需要任何科学上网工具。但是如果你的网络环境较差、多次尝试都无法自动下载，可以手动下载安装并配置Gradle。
