### ISSUE TITLE
想用python开发一个类似的小游戏，想知道能否实现以及代码复杂度是否达标

### ISSUE THREAD

**Issue by hrx20000209** [buaa21/summer2020#95]
https://www.bilibili.com/video/BV17V411S7uZ
视频中的是手机上的，我想用python做一个在pc端运行的投篮小游戏。
操作方式类似flappy bird，一个键控制球的弹跳，篮筐在两边交替出现，高度随机。
想请问一下代码复杂度是否足够？后续考虑加入更多的功能，如按钮开关、排名等。
目前也遇到了很多问题，我想用pymunk建立物理模型，提高游戏的物理引擎性能，但是感觉难以和pygame的库结合起来，通过键盘对球进行控制。
所以第二个问题就是想知道这个小游戏能否实现？

**Comment by crclz** [comment]
【传话】

某老师：如果物理引擎是直接调用的，那复杂度不太够，多加点功能

某助教：感觉可以想办法加点别的东西，只是这样看起来有点单调，但和pymunk结合的话我就不清楚了，pymunk的官方文档里有专门和pygame交互的api

**Comment by orixing** [comment]
没错某助教就是俺XD
可以尝试先去做，个人认为难点是pymunk和pygame图片的结合，这个可以去官方文档http://www.pymunk.org/en/latest/pymunk.pygame_util.html
这里找找有没有办法
另一个是鼠标控制pymunk，这个我不太清楚能否实现，按理说是可以的

内容方面，如果只是做到视频中这样个人感觉有那么点单薄了，想办法加入一些内容或者创新一下玩法
