### ISSUE TITLE
python插入文字为什么显示不出来

### ISSUE THREAD

**Issue by jingyou574066976** [buaa21/summer2020#96]
![微信图片_20200828192236](https://user-images.githubusercontent.com/70198335/91555584-de5ea480-e963-11ea-80db-b303e8d23a14.png)
就如图所示 也不会报错 但是那个文字就在exe上没有显示 应该怎么让他出来呢

**Comment by PineZhuo** [comment]
可以把显示象棋的图片的代码注释掉，看看是不是图片挡住了

**Comment by jingyou574066976** [comment]
> 可以把显示象棋的图片的代码注释掉，看看是不是图片挡住了
![微信截图_20200828195733](https://user-images.githubusercontent.com/70198335/91558336-bb82bf00-e968-11ea-84bb-27316ba9b5b9.png)
ba把棋子注释就出这个问题 但是我又找不到这个在哪/捂脸 然后把那个文字换到别的地方然后放大都没用

**Comment by PineZhuo** [comment]
象棋盘呢？那张图片注释掉看看

**Comment by jingyou574066976** [comment]
> 象棋盘呢？那张图片注释掉看看

啊啊我知道了 我那个背景色覆盖了全部把字挡住了 辛苦助教啦
