### ISSUE TITLE
我用C语言实现飞机大战的飞机爆炸效果时发现：爆炸效果有时有有时没有。

### ISSUE THREAD

**Issue by BUAALX** [buaa21/summer2020#97]
我的思路是在血量为0的飞机的坐标直接通过putimage()来将爆炸效果图贴上，但在运行时发现有时可见，有时不可见，而且有的爆炸会发现有明显的图片的更改

**Comment by IAmParasite** [comment]
能贴一下代码嘛...这样我们也不清楚哪里出问题哦

**Comment by BUAALX** [comment]
![无标题](https://user-images.githubusercontent.com/70186579/91578208-71a3d400-e97c-11ea-939d-9ecf27b4a8bd.png)

**Comment by BUAALX** [comment]
这是更改飞机情况的代码

**Comment by orixing** [comment]
虽然跟你问的问题无关但为啥不在运行的时候就把图片加载好而是一次爆炸一次加载

**Comment by IAmParasite** [comment]
你来找一个具体的助教帮你看一下哪里有问题趴，找我也行!这样代码看不全也没办法判断的哦

**Comment by BUAALX** [comment]
好的,老师
