### ISSUE TITLE
winform调试的问题

### ISSUE THREAD

**Issue by Z8232000** [buaa21/summer2020#98]
调试的时候不知道怎么在断点处停止
运行窗体后直接继续进行下去了
在网络上并没有搜索到相关的调试教程
希望能给一个能学习调试的网址

**Comment by Z8232000** [comment]
用的是VS

**Comment by crclz** [comment]
调试很简单啊，和在devc++、codeblocks里面调试c语言代码一样，不需要单独学习。
第一步就是打断点，第二部就是F5调试，然后程序运行到断点就会自动中断

**Comment by PineZhuo** [comment]
没有写过C#，但是同一个ide的调试方法应该是一样的。VS的调试可以看这个教程https://jingyan.baidu.com/article/d45ad148999dd069552b8098.html

**Comment by crclz** [comment]
![image](https://user-images.githubusercontent.com/54950573/91575935-1ffa4a00-e97a-11ea-9bb0-8b8cbd19c781.png)
首先确认你是不是点的`调试`。

第二，你可以在上方工具栏点击项目，然后点击最下方的xxx属性那里。进去之后，把类型改成控制台程序。然后你就可以结合`Console.WriteLine`输出调试信息了
![image](https://user-images.githubusercontent.com/54950573/91576816-6ea7e400-e97a-11ea-9bd3-bbd994a4c4cb.png)
