### ISSUE TITLE
通过百度添加一个第三方功能，找不到文件位置

### ISSUE THREAD

**Issue by ljr19231244** [buaa21/summer2020#99]
![GU`A71}HKKC98G()@798BQG](https://user-images.githubusercontent.com/70185522/91567264-7023dd00-e977-11ea-92b7-b61772d9e824.png)
![F3TM DAT139%H57ZVQ~T)RY](https://user-images.githubusercontent.com/70185522/91567270-70bc7380-e977-11ea-9bd8-ae8e547c8be3.png)
![RW{I0~OV FPG}U0TNCLUOB](https://user-images.githubusercontent.com/70185522/91567274-71eda080-e977-11ea-9e78-e63eb47edae0.png)
图一是我在pycharm中安装autopep8的过程，未发现文件位置
图二图三是百度的方法

**Comment by IAmParasite** [comment]
你这个应该是安装了虚拟环境吧，如果是virtualenv生成的文件夹中寻找一下

**Comment by crclz** [comment]
我参考的是这篇教程 https://www.cnblogs.com/xiao-apple36/p/9242069.html
idea成功进行了PEP8风格提示与纠正
